// AUTO-GENERATED route manifest (P2.2).
//
// Replaces ~110 hand-wired <Route> lines + static imports in App.jsx with a
// data-driven, lazily-loaded table so every page is its own bundle chunk.
//
// These legacy lesson pages still render their own chrome; they are superseded
// by the spine-driven /learn routes as content migrates in P5, at which point
// the lessonRoutes array shrinks to empty and this file is removed.
import { lazy } from 'react';

// Utility + course-index pages.
export const pageRoutes = [
  { path: 'dashboard', Component: lazy(() => import('../pages/Dashboard.jsx')) },
  { path: 'glossary', Component: lazy(() => import('../pages/Glossary.jsx')) },
  { path: 'certificate', Component: lazy(() => import('../pages/Certificate.jsx')) },
  { path: 'search', Component: lazy(() => import('../pages/SearchResults.jsx')) },
  { path: 'cheatsheets', Component: lazy(() => import('../pages/CheatSheets.jsx')) },
  { path: 'it-models', Component: lazy(() => import('../pages/ITModels.jsx')) },
  { path: 'port-lookup', Component: lazy(() => import('../pages/PortLookup.jsx')) },
  { path: 'vmware-setup', Component: lazy(() => import('../pages/VmwareSetup.jsx')) },
  { path: 'windows', Component: lazy(() => import('../pages/Windows.jsx')) },
  { path: 'windows-server-2025', Component: lazy(() => import('../pages/WindowsServer2025.jsx')) },
  { path: 'linux', Component: lazy(() => import('../pages/Linux.jsx')) },
  { path: 'unix', Component: lazy(() => import('../pages/Unix.jsx')) },
  { path: 'networking', Component: lazy(() => import('../pages/Networking.jsx')) },
  { path: 'python', Component: lazy(() => import('../pages/Python.jsx')) },
  { path: 'cybersecurity', Component: lazy(() => import('../pages/Cybersecurity.jsx')) },
  { path: 'powershell', Component: lazy(() => import('../pages/PowerShell.jsx')) },
  { path: 'devops', Component: lazy(() => import('../pages/DevOps.jsx')) },
  { path: 'troubleshooting', Component: lazy(() => import('../pages/Troubleshooting.jsx')) },
];

// Legacy self-rendering lesson pages (URLs preserved exactly).
export const lessonRoutes = [
  { path: 'windows/architecture', Component: lazy(() => import('../pages/lessons/WindowsArchitecture.jsx')) },
  { path: 'windows/permissions', Component: lazy(() => import('../pages/lessons/WindowsPermissions.jsx')) },
  { path: 'windows/registry', Component: lazy(() => import('../pages/lessons/WindowsRegistry.jsx')) },
  { path: 'windows/processes', Component: lazy(() => import('../pages/lessons/WindowsProcesses.jsx')) },
  { path: 'windows/networking', Component: lazy(() => import('../pages/lessons/WindowsNetworking.jsx')) },
  { path: 'windows/event-viewer', Component: lazy(() => import('../pages/lessons/WindowsEventViewer.jsx')) },
  { path: 'windows-server-2025/intro', Component: lazy(() => import('../pages/lessons/WS2025Intro.jsx')) },
  { path: 'windows-server-2025/active-directory', Component: lazy(() => import('../pages/lessons/ActiveDirectory.jsx')) },
  { path: 'windows-server-2025/dhcp', Component: lazy(() => import('../pages/lessons/DHCP.jsx')) },
  { path: 'windows-server-2025/dns', Component: lazy(() => import('../pages/lessons/DNS.jsx')) },
  { path: 'windows-server-2025/group-policy', Component: lazy(() => import('../pages/lessons/GroupPolicy.jsx')) },
  { path: 'windows-server-2025/hyper-v', Component: lazy(() => import('../pages/lessons/HyperV.jsx')) },
  { path: 'windows-server-2025/file-services', Component: lazy(() => import('../pages/lessons/WS2025FileServices.jsx')) },
  { path: 'windows-server-2025/firewall', Component: lazy(() => import('../pages/lessons/WindowsFirewall.jsx')) },
  { path: 'windows-server-2025/rds', Component: lazy(() => import('../pages/lessons/WS2025RDS.jsx')) },
  { path: 'windows-server-2025/backup', Component: lazy(() => import('../pages/lessons/WS2025Backup.jsx')) },
  { path: 'windows-server-2025/wac', Component: lazy(() => import('../pages/lessons/WS2025WAC.jsx')) },
  { path: 'windows-server-2025/hardening', Component: lazy(() => import('../pages/lessons/WS2025Hardening.jsx')) },
  { path: 'unix/philosophy', Component: lazy(() => import('../pages/lessons/UnixPhilosophy.jsx')) },
  { path: 'unix/posix-shell', Component: lazy(() => import('../pages/lessons/UnixPOSIXShell.jsx')) },
  { path: 'unix/bsd', Component: lazy(() => import('../pages/lessons/UnixBSD.jsx')) },
  { path: 'unix/permissions', Component: lazy(() => import('../pages/lessons/UnixPermissions.jsx')) },
  { path: 'unix/processes', Component: lazy(() => import('../pages/lessons/UnixProcesses.jsx')) },
  { path: 'linux/filesystem', Component: lazy(() => import('../pages/lessons/LinuxFilesystem.jsx')) },
  { path: 'linux/shell', Component: lazy(() => import('../pages/lessons/LinuxShell.jsx')) },
  { path: 'linux/permissions', Component: lazy(() => import('../pages/lessons/LinuxPermissions.jsx')) },
  { path: 'linux/packages', Component: lazy(() => import('../pages/lessons/LinuxPackages.jsx')) },
  { path: 'linux/systemd', Component: lazy(() => import('../pages/lessons/LinuxSystemd.jsx')) },
  { path: 'linux/networking', Component: lazy(() => import('../pages/lessons/LinuxNetworking.jsx')) },
  { path: 'linux/ssh', Component: lazy(() => import('../pages/lessons/LinuxSSH.jsx')) },
  { path: 'linux/firewall', Component: lazy(() => import('../pages/lessons/LinuxFirewall.jsx')) },
  { path: 'linux/disk', Component: lazy(() => import('../pages/lessons/LinuxDisk.jsx')) },
  { path: 'linux/hardening', Component: lazy(() => import('../pages/lessons/LinuxHardening.jsx')) },
  { path: 'networking/osi-model', Component: lazy(() => import('../pages/lessons/OSIModel.jsx')) },
  { path: 'networking/tcp-ip', Component: lazy(() => import('../pages/lessons/TCPIP.jsx')) },
  { path: 'networking/subnetting', Component: lazy(() => import('../pages/lessons/NetworkingSubnetting.jsx')) },
  { path: 'networking/vlans', Component: lazy(() => import('../pages/lessons/NetworkingVLANs.jsx')) },
  { path: 'networking/routing', Component: lazy(() => import('../pages/lessons/NetworkingRouting.jsx')) },
  { path: 'networking/dns', Component: lazy(() => import('../pages/lessons/NetworkingDNS.jsx')) },
  { path: 'networking/troubleshooting', Component: lazy(() => import('../pages/lessons/NetworkingTroubleshootingLesson.jsx')) },
  { path: 'networking/wireless', Component: lazy(() => import('../pages/lessons/NetworkingWireless.jsx')) },
  { path: 'powershell/fundamentals', Component: lazy(() => import('../pages/lessons/PowerShellFundamentals.jsx')) },
  { path: 'powershell/pipeline', Component: lazy(() => import('../pages/lessons/PowerShellPipeline.jsx')) },
  { path: 'powershell/scripting', Component: lazy(() => import('../pages/lessons/PowerShellScripting.jsx')) },
  { path: 'powershell/active-directory', Component: lazy(() => import('../pages/lessons/PSActiveDirectory.jsx')) },
  { path: 'powershell/remoting', Component: lazy(() => import('../pages/lessons/PSRemoting.jsx')) },
  { path: 'powershell/filesystem', Component: lazy(() => import('../pages/lessons/PSFilesystem.jsx')) },
  { path: 'powershell/dsc', Component: lazy(() => import('../pages/lessons/PSDSC.jsx')) },
  { path: 'powershell/reporting', Component: lazy(() => import('../pages/lessons/PSReporting.jsx')) },
  { path: 'cybersecurity/cia-triad', Component: lazy(() => import('../pages/lessons/CIATriad.jsx')) },
  { path: 'cybersecurity/threat-modelling', Component: lazy(() => import('../pages/lessons/ThreatModelling.jsx')) },
  { path: 'cybersecurity/windows-hardening', Component: lazy(() => import('../pages/lessons/CybersecurityWindowsHardening.jsx')) },
  { path: 'cybersecurity/linux-hardening', Component: lazy(() => import('../pages/lessons/CybersecurityLinuxHardening.jsx')) },
  { path: 'cybersecurity/firewall', Component: lazy(() => import('../pages/lessons/CybersecurityFirewall.jsx')) },
  { path: 'cybersecurity/pki', Component: lazy(() => import('../pages/lessons/CybersecurityPKI.jsx')) },
  { path: 'cybersecurity/ids-siem', Component: lazy(() => import('../pages/lessons/CybersecurityIDSSIEM.jsx')) },
  { path: 'cybersecurity/vuln-scanning', Component: lazy(() => import('../pages/lessons/CybersecurityVulnScanning.jsx')) },
  { path: 'cybersecurity/incident-response', Component: lazy(() => import('../pages/lessons/CybersecurityIncidentResponse.jsx')) },
  { path: 'cybersecurity/ad-security', Component: lazy(() => import('../pages/lessons/CybersecurityADSecurity.jsx')) },
  { path: 'python/basics', Component: lazy(() => import('../pages/lessons/PythonBasics.jsx')) },
  { path: 'python/filesystem', Component: lazy(() => import('../pages/lessons/PythonAutomation.jsx')) },
  { path: 'python/subprocess', Component: lazy(() => import('../pages/lessons/PythonSubprocess.jsx')) },
  { path: 'python/networking', Component: lazy(() => import('../pages/lessons/PythonNetworking.jsx')) },
  { path: 'python/log-parsing', Component: lazy(() => import('../pages/lessons/PythonLogParsing.jsx')) },
  { path: 'python/scheduling', Component: lazy(() => import('../pages/lessons/PythonScheduling.jsx')) },
  { path: 'python/monitoring', Component: lazy(() => import('../pages/lessons/PythonMonitoring.jsx')) },
  { path: 'python/ansible', Component: lazy(() => import('../pages/lessons/PythonAnsible.jsx')) },
  { path: 'python/cli-tool', Component: lazy(() => import('../pages/lessons/PythonCLITool.jsx')) },
  { path: 'devops/principles', Component: lazy(() => import('../pages/lessons/DevOpsPrinciples.jsx')) },
  { path: 'devops/git', Component: lazy(() => import('../pages/lessons/DevOpsGit.jsx')) },
  { path: 'devops/docker', Component: lazy(() => import('../pages/lessons/DockerContainers.jsx')) },
  { path: 'devops/cicd', Component: lazy(() => import('../pages/lessons/DevOpsCICD.jsx')) },
  { path: 'devops/terraform', Component: lazy(() => import('../pages/lessons/DevOpsTerraform.jsx')) },
  { path: 'devops/ansible', Component: lazy(() => import('../pages/lessons/DevOpsAnsible.jsx')) },
  { path: 'devops/kubernetes', Component: lazy(() => import('../pages/lessons/DevOpsKubernetes.jsx')) },
  { path: 'devops/monitoring', Component: lazy(() => import('../pages/lessons/DevOpsMonitoring.jsx')) },
  { path: 'troubleshooting/methodology', Component: lazy(() => import('../pages/lessons/TroubleshootingMethodology.jsx')) },
  { path: 'troubleshooting/windows', Component: lazy(() => import('../pages/lessons/WindowsTroubleshooting.jsx')) },
  { path: 'troubleshooting/linux', Component: lazy(() => import('../pages/lessons/LinuxTroubleshooting.jsx')) },
  { path: 'troubleshooting/networking', Component: lazy(() => import('../pages/lessons/TroubleshootingNetworking.jsx')) },
  { path: 'troubleshooting/active-directory', Component: lazy(() => import('../pages/lessons/TroubleshootingActiveDirectory.jsx')) },
  { path: 'troubleshooting/performance', Component: lazy(() => import('../pages/lessons/TroubleshootingPerformance.jsx')) },
];

// Section "coming soon" placeholders for not-yet-authored sub-paths.
export const placeholderRoutes = [
  { path: 'windows/:lesson', title: 'Windows Desktop — lesson coming soon' },
  { path: 'windows-server-2025/:lesson', title: 'Windows Server 2025 — lesson coming soon' },
  { path: 'unix/:lesson', title: 'Unix — lesson coming soon' },
  { path: 'linux/:lesson', title: 'Linux — lesson coming soon' },
  { path: 'networking/:lesson', title: 'Networking — lesson coming soon' },
  { path: 'powershell/:lesson', title: 'PowerShell — lesson coming soon' },
  { path: 'cybersecurity/:lesson', title: 'Cybersecurity — lesson coming soon' },
  { path: 'python/:lesson', title: 'Python — lesson coming soon' },
  { path: 'devops/:lesson', title: 'DevOps — lesson coming soon' },
  { path: 'troubleshooting/:lesson', title: 'Troubleshooting — lesson coming soon' },
];
