#!/usr/bin/env python3
"""Expand the existing p28 (CompTIA A+) manifest: append 3 lessons per course.
Loads scripts/manifests/p28.json, appends, writes back (existing ids untouched)."""
import json, pathlib
MAN = pathlib.Path('/home/claude/it-academy/scripts/manifests/p28.json')
man = json.loads(MAN.read_text())

def L(id,slug,title,minutes,xp,intro,sections,practice,quiz):
    return {"id":id,"slug":slug,"title":title,"minutes":minutes,"xp":xp,"content":{"intro":intro,"sections":sections,"practice":practice},"quiz":quiz}
def S(h,p=None,ul=None,note=None,code=None):
    d={"h":h}
    if p:d["p"]=p if isinstance(p,list) else [p]
    if ul:d["ul"]=ul
    if code:d["code"]=code
    if note:d["note"]=note
    return d
def Q(p,o,ci,ex):return{"p":p,"o":o,"ci":ci,"ex":ex}

NEW = {
 "ca-hardware":[
  L("ca-hw-04","display-video","Display & Video",18,50,
   "Monitors and graphics: display technologies, resolutions, and the video connectors A+ tests.",
   [S("Display types",ul=[{"b":"LCD (LED-backlit):","t":"most common; IPS = better color/angles, TN = faster/cheaper."},{"b":"OLED:","t":"per-pixel light, deep blacks."},{"b":"Projectors:","t":"lumens = brightness."}]),
    S("Resolution & specs",ul=["Resolution (1080p, 1440p, 4K), refresh rate (Hz), aspect ratio","Response time matters for gaming"]),
    S("Video connectors",note={"kind":"tip","text":"HDMI and DisplayPort carry audio+video; VGA/DVI are legacy (DVI can be digital)."})],
   "Match IPS, TN, and OLED to: best color, fastest response, deepest blacks.",
   [Q("Which panel type has the best color/viewing angles?",["TN","IPS","VGA","CRT"],1,"IPS offers superior color and angles."),
    Q("Which connector is digital and carries audio?",["VGA","HDMI","PS/2","Serial"],1,"HDMI carries digital audio + video."),
    Q("Projector brightness is measured in…",["Hz","Lumens","DPI","Watts"],1,"Lumens measure projector brightness.")]),
  L("ca-hw-05","printers","Printers & Multifunction Devices",20,55,
   "Printer types and the laser imaging process — a classic A+ topic tested in detail.",
   [S("Printer types",ul=[{"b":"Laser:","t":"toner + fusing; fast, sharp text."},{"b":"Inkjet:","t":"liquid ink; good photos."},{"b":"Thermal:","t":"heat-sensitive paper (receipts)."},{"b":"Impact:","t":"multipart forms."},{"b":"3D:","t":"filament/resin."}]),
    S("Laser imaging — 7 steps",ul=["Processing → Charging → Exposing → Developing → Transferring → Fusing → Cleaning"],note={"kind":"tip","text":"Memorize the order; questions ask 'what happens after exposing?' (developing)."}),
    S("Maintenance",p="Laser: replace toner, use a maintenance kit. Inkjet: clean/align heads. Keep firmware updated.")],
   "List the seven steps of the laser printing process in order.",
   [Q("Which printer uses toner and a fusing step?",["Inkjet","Laser","Thermal","Impact"],1,"Laser printers fuse toner to paper."),
    Q("The step right after Exposing is…",["Charging","Developing","Fusing","Cleaning"],1,"Developing follows exposing."),
    Q("Receipts commonly use which printer?",["Laser","Thermal","3D","Impact"],1,"Thermal printers use heat-sensitive paper.")]),
  L("ca-hw-06","custom-raid","Custom Configurations & RAID",18,50,
   "Purpose-built PCs and redundant storage arrays.",
   [S("Custom builds",ul=[{"b":"Workstation:","t":"more CPU/RAM/GPU (CAD, virtualization)."},{"b":"NAS:","t":"storage + RAID."},{"b":"Thin client:","t":"minimal, connects to server."}]),
    S("RAID levels",ul=[{"b":"RAID 0:","t":"stripe — speed, no redundancy."},{"b":"RAID 1:","t":"mirror — redundancy."},{"b":"RAID 5:","t":"stripe + parity (3+ disks)."},{"b":"RAID 10:","t":"mirror + stripe."}],note={"kind":"warn","text":"RAID is not a backup — it protects against disk failure, not deletion/ransomware."}),
    S("Choosing",p="RAID 1 for simple redundancy; RAID 5 balances capacity and protection; RAID 10 for performance + redundancy.")],
   "Which RAID gives redundancy with only two disks, and which needs at least three?",
   [Q("RAID 0 provides…",["Redundancy","Speed, no redundancy","Parity","A backup"],1,"Striping boosts speed but has no redundancy."),
    Q("RAID 5 requires at least…",["1 disk","2 disks","3 disks","5 disks"],2,"RAID 5 needs 3+ disks for parity."),
    Q("RAID is not a substitute for…",["Speed","Backups","A GPU","Cooling"],1,"RAID isn't a backup.")]),
 ],
 "ca-net":[
  L("ca-net-04","devices","Network Devices",18,50,
   "The boxes that build a network — know what each does.",
   [S("Core devices",ul=[{"b":"Switch:","t":"connects LAN devices (MAC-based)."},{"b":"Router:","t":"connects networks, routes by IP."},{"b":"Access point:","t":"adds Wi-Fi."},{"b":"Firewall:","t":"filters traffic."},{"b":"Modem:","t":"ISP↔digital signal."}]),
    S("Extras",ul=["PoE delivers power over Ethernet (APs, cameras)","A combo SOHO router bundles router+switch+AP+firewall"]),
    S("When to use",note={"kind":"info","text":"Out of ports? Add a switch. Need Wi-Fi? Add an AP. Segment/secure? Firewall/VLAN."})],
   "Name the device that routes between networks vs the one that connects devices on the same LAN.",
   [Q("Which device connects LAN devices by MAC address?",["Router","Switch","Modem","Firewall"],1,"A switch forwards by MAC on the LAN."),
    Q("Power over Ethernet (PoE) is useful for…",["Cooling","APs and IP cameras","Monitors","Printers only"],1,"PoE powers APs/cameras over the data cable."),
    Q("Which connects two different networks?",["Switch","Router","Hub","Repeater"],1,"Routers route between networks.")]),
  L("ca-net-05","tcpip-services","TCP/IP & Network Services",20,55,
   "The services that make IP networks usable.",
   [S("Core services",ul=[{"b":"DNS:","t":"names → IPs."},{"b":"DHCP:","t":"auto IP assignment."},{"b":"NAT:","t":"many private IPs share one public IP."}]),
    S("Segmentation & remote",ul=[{"b":"VLAN:","t":"logical network separation on a switch."},{"b":"VPN:","t":"encrypted tunnel over the internet."}]),
    S("Addressing recap",note={"kind":"tip","text":"APIPA (169.254.x) = no DHCP. Loopback = 127.0.0.1."})],
   "Explain what NAT does and why home networks rely on it.",
   [Q("NAT lets…",["Names resolve","Many private IPs share one public IP","Wi-Fi work","Disks mirror"],1,"NAT maps private IPs to a public one."),
    Q("A VLAN provides…",["Encryption","Logical network separation","More storage","Faster CPU"],1,"VLANs segment a network logically."),
    Q("169.254.x.x indicates…",["Static IP","No DHCP (APIPA)","A VPN","Loopback"],1,"APIPA means no DHCP lease.")]),
  L("ca-net-06","internet-types","Internet Connection Types",16,50,
   "How sites and homes connect to the internet.",
   [S("Wired",ul=[{"b":"Fiber:","t":"fastest, symmetrical."},{"b":"Cable:","t":"coax, shared."},{"b":"DSL:","t":"phone line, distance-limited."}]),
    S("Wireless/other",ul=[{"b":"Cellular:","t":"4G/5G, mobile."},{"b":"Satellite:","t":"remote areas, higher latency."},{"b":"Fixed wireless","t":"— line-of-sight."}]),
    S("Choosing",note={"kind":"info","text":"Fiber where available; satellite/cellular for remote sites where wired isn't feasible."})],
   "Which connection type has the highest latency, and which is fastest/symmetrical?",
   [Q("The fastest, typically symmetrical option is…",["DSL","Cable","Fiber","Satellite"],2,"Fiber is fastest and symmetrical."),
    Q("Which has the highest latency?",["Fiber","Cable","Satellite","DSL"],2,"Satellite has high latency."),
    Q("DSL runs over…",["Coax","Phone lines","Fiber","Cellular"],1,"DSL uses telephone lines.")]),
 ],
 "ca-mc":[
  L("ca-mc-04","mobile-connectivity","Mobile Connectivity & Email",18,50,
   "Connecting mobile devices and configuring email — frequent help-desk tasks.",
   [S("Connectivity",ul=[{"b":"Bluetooth:","t":"pair, enter PIN, test."},{"b":"Hotspot/tethering","t":"shares cellular."},{"b":"Airplane mode","t":"toggles radios."}]),
    S("Email setup",ul=[{"b":"IMAP (143/993):","t":"syncs across devices."},{"b":"POP3 (110/995):","t":"downloads, single device."},{"b":"Exchange/ActiveSync","t":"— corporate, full sync."}],note={"kind":"tip","text":"Use IMAP/Exchange for multi-device sync; secure ports (993/995) use TLS."}),
    S("Steps",p="Verify server names/ports, credentials, and TLS. For corporate mail, the device may need to accept an MDM/security policy.")],
   "A user wants email on phone and laptop kept in sync — IMAP or POP3, and which secure port?",
   [Q("Which protocol keeps mail synced across devices?",["POP3","IMAP","SMTP-only","FTP"],1,"IMAP syncs across devices."),
    Q("Secure IMAP uses port…",["143","993","110","25"],1,"IMAP over TLS is 993."),
    Q("Pairing a Bluetooth headset requires…",["An IP","Pairing/PIN","A VLAN","NAT"],1,"Bluetooth devices pair (often with a PIN).")]),
  L("ca-mc-05","mobile-sync-security","Mobile Sync & Security",18,50,
   "Keeping mobile data synced and secure across the fleet.",
   [S("Synchronization",ul=["Cloud sync (contacts, photos, files)","Sync to desktop or over Wi-Fi","Watch data-cap and battery impact"]),
    S("Mobile security",ul=[{"b":"Screen lock + biometrics","t":""},{"b":"Remote wipe/locate","t":"for lost devices."},{"b":"MDM:","t":"enforces policy, app control."}]),
    S("Corporate",note={"kind":"info","text":"BYOD often uses containerization to separate work and personal data."})],
   "List three controls that protect a lost corporate phone.",
   [Q("Which centrally enforces mobile security policy?",["DNS","MDM","NAT","RAID"],1,"MDM manages/secures devices."),
    Q("Best protection for a lost phone's data…",["Louder ring","Remote wipe + encryption","New case","Bigger battery"],1,"Remote wipe + encryption protect data."),
    Q("BYOD work/personal separation uses…",["Containerization","RAID","VGA","PoE"],0,"Containerization isolates work data.")]),
  L("ca-mc-06","laptop-hardware","Laptop Hardware",18,50,
   "Laptop-specific components and field-replaceable parts.",
   [S("Replaceable parts",ul=["Battery (Li-ion), RAM (SODIMM), storage (M.2/2.5\")","Keyboard, screen, Wi-Fi card"]),
    S("Special features",ul=["Function-key toggles (display, wireless, brightness)","Docking stations / port replicators"]),
    S("Handling",note={"kind":"warn","text":"Power off and remove the battery (if removable) before internal work; use ESD protection."})],
   "Name three field-replaceable laptop parts.",
   [Q("Laptop memory modules are…",["DIMM","SODIMM","DDR only","NVMe"],1,"Laptops use SODIMM."),
    Q("Before internal laptop work you should…",["Nothing","Power off + ESD precautions","Increase brightness","Update apps"],1,"Power down and use ESD protection."),
    Q("A docking station provides…",["More CPU","Additional ports/connectivity","RAID","A GPU"],1,"Docks expand ports/connectivity.")]),
 ],
 "ca-os":[
  L("ca-os-04","macos-linux","macOS & Linux Basics",18,50,
   "A+ covers Windows plus core macOS and Linux awareness.",
   [S("macOS",ul=["Finder, Spotlight, Mission Control","Time Machine backups","Disk Utility, Keychain"]),
    S("Linux",ul=[{"b":"Distros:","t":"Ubuntu, Fedora, etc."},{"b":"Shell + package managers","t":"(apt, yum/dnf)."}]),
    S("Common Linux commands",code="ls / cd / pwd     # navigate\nsudo <cmd>        # elevate\napt install pkg   # install (Debian/Ubuntu)\nchmod / chown     # permissions\nps / top          # processes")],
   "Give the macOS backup tool and a Debian/Ubuntu package-install command.",
   [Q("The macOS backup tool is…",["File History","Time Machine","rsync only","OneDrive"],1,"Time Machine backs up macOS."),
    Q("Install a package on Ubuntu with…",["yum install","apt install","brew only","choco"],1,"apt is Debian/Ubuntu's manager."),
    Q("Elevate a single Linux command with…",["run","sudo","admin","elevate"],1,"sudo runs a command as root.")]),
  L("ca-os-05","windows-networking","Windows Networking Configuration",18,50,
   "Configuring and sharing on a Windows network.",
   [S("IP configuration",ul=["DHCP (automatic) vs static IP","ipconfig to view/renew","Network profiles: Private vs Public"]),
    S("Sharing",ul=["File/printer sharing, mapped drives (net use)","Share vs NTFS permissions (most restrictive wins)"]),
    S("Remote",note={"kind":"tip","text":"Enable Remote Desktop only when needed; it uses port 3389."})],
   "When combining Share and NTFS permissions, which effective permission applies?",
   [Q("A static IP is set when…",["Always","DHCP is unavailable or a server needs a fixed address","Never","Only on laptops"],1,"Servers/printers often need fixed IPs."),
    Q("Combining Share + NTFS permissions, the effective right is…",["Most permissive","Most restrictive","Share only","NTFS only"],1,"The most restrictive of the two applies."),
    Q("Remote Desktop uses port…",["22","3389","443","80"],1,"RDP is 3389.")]),
  L("ca-os-06","users-security","OS Security & User Management",18,50,
   "Local accounts, groups, and permission models.",
   [S("Accounts & groups",ul=["Standard vs Administrator","Groups simplify permission assignment","UAC prompts for elevation"]),
    S("Permissions",ul=[{"b":"NTFS:","t":"granular, local + network."},{"b":"Share:","t":"network only."},{"b":"Principle of least privilege","t":""}]),
    S("Hardening",note={"kind":"tip","text":"Rename/disable default admin, enforce strong passwords + lockout, keep patched."})],
   "Explain least privilege and how groups make it easier to apply.",
   [Q("UAC exists to…",["Speed boot","Require elevation for admin changes","Play sounds","Map drives"],1,"UAC gates administrative actions."),
    Q("Assigning permissions to groups (not individuals)…",["Is slower","Simplifies management","Removes security","Needs RAID"],1,"Groups scale permission management."),
    Q("Least privilege means users get…",["Full admin","Only needed access","No access","Random access"],1,"Only the access required.")]),
 ],
 "ca-sec":[
  L("ca-sec-04","wireless-auth","Wireless Security & Authentication",18,55,
   "Securing Wi-Fi and the authentication concepts A+ expects.",
   [S("Wireless security",ul=[{"b":"WPA3 > WPA2-AES","t":"; avoid WEP/TKIP."},{"b":"Enterprise (802.1X/RADIUS)","t":"vs personal (PSK)."}]),
    S("Authentication concepts",ul=[{"b":"MFA:","t":"something you know/have/are."},{"b":"SSO:","t":"one login, many apps."},{"b":"AAA:","t":"authentication, authorization, accounting."}]),
    S("Best practice",note={"kind":"warn","text":"Change default SSID/admin password; use a strong passphrase or enterprise auth."})],
   "Differentiate WPA2-Personal (PSK) from WPA2-Enterprise (RADIUS).",
   [Q("The strongest listed Wi-Fi security is…",["WEP","WPA","WPA2-TKIP","WPA3"],3,"WPA3 is strongest."),
    Q("Enterprise Wi-Fi auth commonly uses…",["A single PSK","RADIUS/802.1X","No auth","MAC only"],1,"802.1X/RADIUS authenticates each user."),
    Q("MFA combines factors like…",["Two passwords","Password + phone code","Two usernames","Two SSIDs"],1,"Different factor types (know/have/are).")]),
  L("ca-sec-05","malware-removal","Malware Removal Process",18,55,
   "CompTIA's structured 7-step malware removal procedure — tested in order.",
   [S("The 7 steps",ul=["1. Investigate & verify symptoms","2. Quarantine the system","3. Disable System Restore (Windows)","4. Remediate — update tools, scan & remove","5. Schedule scans & run updates","6. Re-enable System Restore & create a restore point","7. Educate the end user"],note={"kind":"tip","text":"Disable System Restore BEFORE cleaning so malware isn't preserved in restore points."}),
    S("Why the order",p="Quarantine stops spread; disabling restore prevents reinfection from snapshots; education prevents recurrence."),
    S("If cleaning fails",p="Reimage from a known-good image and restore data from clean backups.")],
   "Why do you disable System Restore before remediation, and re-enable it after?",
   [Q("Step 2 of malware removal is…",["Educate user","Quarantine the system","Reimage","Buy AV"],1,"Quarantine to stop spread."),
    Q("You disable System Restore to…",["Save space","Avoid preserving malware in restore points","Speed boot","Free RAM"],1,"So infected snapshots aren't kept."),
    Q("The final step is always…",["Reboot","Educate the end user","Format","Escalate"],1,"User education prevents recurrence.")]),
  L("ca-sec-06","social-engineering","Social Engineering & Common Threats",18,55,
   "The attacks that target people and networks.",
   [S("Social engineering",ul=[{"b":"Phishing / spear phishing / whaling","t":""},{"b":"Vishing (voice), smishing (SMS)","t":""},{"b":"Tailgating, shoulder surfing, dumpster diving","t":""}]),
    S("Network attacks",ul=[{"b":"DoS/DDoS:","t":"overwhelm a service."},{"b":"MITM:","t":"intercept traffic."},{"b":"Zero-day:","t":"unknown vulnerability."}]),
    S("Defense",note={"kind":"tip","text":"User training + MFA + patching defeat most of these."})],
   "Match: fake call, fake SMS, targeting executives — to vishing, smishing, whaling.",
   [Q("Phishing aimed at executives is…",["Vishing","Whaling","Smishing","Tailgating"],1,"Whaling targets high-value execs."),
    Q("Intercepting traffic between two parties is…",["DoS","Man-in-the-middle","Phishing","Zero-day"],1,"MITM intercepts communications."),
    Q("A DDoS attack aims to…",["Steal a password","Overwhelm a service","Encrypt files","Clone a drive"],1,"DDoS exhausts a service's capacity.")]),
 ],
 "ca-ts":[
  L("ca-ts-04","network-ts","Network Troubleshooting",18,55,
   "Diagnose connectivity like a tech using the standard tools.",
   [S("Symptoms",ul=[{"b":"No connectivity:","t":"cable/adapter, DHCP (APIPA), gateway."},{"b":"Slow:","t":"congestion, Wi-Fi signal, duplex."},{"b":"Intermittent:","t":"interference, failing hardware."}]),
    S("Tools",code="ipconfig /all      # addressing/DNS\nping <host>        # reachability\ntracert <host>     # path/hops\nnslookup <name>    # DNS"),
    S("Method",note={"kind":"tip","text":"Test gateway → public IP → name. If IP works but names fail, it's DNS."})],
   "A user can ping 8.8.8.8 but no websites load — what's the likely cause and fix?",
   [Q("A 169.254 address means…",["Static IP","No DHCP","A VPN","Loopback"],1,"APIPA = no DHCP lease."),
    Q("Ping by IP works but names fail →",["Bad cable","DNS issue","Dead NIC","Low RAM"],1,"Name resolution (DNS) is failing."),
    Q("Which tool shows the path/hops to a host?",["ping","tracert","ipconfig","chkdsk"],1,"tracert traces the route.")]),
  L("ca-ts-05","printer-ts","Printer Troubleshooting",16,50,
   "Resolve the most common printing problems.",
   [S("Symptoms → fixes",ul=[{"b":"No print:","t":"offline, queue stuck, connectivity — restart spooler."},{"b":"Streaks/faded (laser):","t":"toner low, dirty drum."},{"b":"Paper jams:","t":"rollers, wrong paper, debris."}]),
    S("Print spooler",p="A stuck queue blocks all jobs — restart the Print Spooler service (clears queued jobs; warn users)."),
    S("Connectivity",note={"kind":"info","text":"Network printer offline for everyone → check the printer's power/network/IP, not one PC."})],
   "A shared printer shows offline for everyone — where do you look first?",
   [Q("A stuck print queue is cleared by…",["Reinstalling Windows","Restarting the Print Spooler","New toner","A reboot only"],1,"Restart the Print Spooler service."),
    Q("Faded laser output usually means…",["Low toner / dirty drum","A DNS issue","Bad RAM","Wrong driver only"],0,"Low toner or a dirty drum."),
    Q("Offline for everyone points to…",["One PC's driver","The printer/network","A user password","The monitor"],1,"A shared outage is printer/network-side.")]),
  L("ca-ts-06","mobile-security-ts","Mobile & Security Troubleshooting",16,50,
   "Common mobile and security-symptom fixes.",
   [S("Mobile issues",ul=[{"b":"Poor battery:","t":"background apps, old battery, brightness."},{"b":"No connectivity:","t":"airplane mode, re-pair, reset network."},{"b":"Slow/overheating:","t":"close apps, update, check storage."}]),
    S("Security symptoms",ul=["Pop-ups/redirects, high data use, unknown apps → scan for malware","Fake security alerts → don't click; remove the app"]),
    S("Method",note={"kind":"tip","text":"Reproduce, check recent installs/changes, update, then apply the 6-step method."})],
   "A phone suddenly has high data use and pop-ups — what do you suspect and do?",
   [Q("Rapid battery drain is often caused by…",["A DNS issue","Background apps / aging battery","RAID","A firewall"],1,"Background apps or a worn battery."),
    Q("Pop-ups + high data use on mobile suggest…",["A GPU fault","Malware/adware","Low volume","A dead SIM"],1,"Likely malware/adware — scan/remove."),
    Q("For no Wi-Fi on a phone, first try…",["Reinstall OS","Toggle airplane mode / reset network","Replace screen","New SIM"],1,"Toggle radios / reset network settings.")]),
 ],
}

added = 0
by_id = {c["id"]: c for c in man["courses"]}
for cid, lessons in NEW.items():
    if cid in by_id:
        by_id[cid]["lessons"].extend(lessons)
        added += len(lessons)
MAN.write_text(json.dumps(man, ensure_ascii=False))
print("appended", added, "lessons; totals:",
      sum(len(c["lessons"]) for c in man["courses"]), "lessons,",
      sum(len(l["quiz"]) for c in man["courses"] for l in c["lessons"]), "quizzes")
