#!/usr/bin/env python3
import json, pathlib
OUT = pathlib.Path('/home/claude/it-academy/scripts/manifests/p28.json')
man = {"courses": []}
def L(id,slug,title,minutes,xp,intro,sections,practice,quiz):
    return {"id":id,"slug":slug,"title":title,"minutes":minutes,"xp":xp,"content":{"intro":intro,"sections":sections,"practice":practice},"quiz":quiz}
def S(h,p=None,ul=None,note=None,code=None):
    d={"h":h}
    if p:d["p"]=p if isinstance(p,list) else [p]
    if ul:d["ul"]=ul
    if code:d["code"]=code
    if note:d["note"]=note
    return d
def Q(p,o,ci,ex):return{"p":p,"o":o,"ci":ci,"ex":ex}
def C(area,id,slug,title,icon,order,module_id,desc,lessons):
    return {"area":area,"id":id,"slug":slug,"title":title,"icon":icon,"order":order,
            "module_id":module_id,"difficulty":"beginner","description":desc,"lessons":lessons}

hardware = C("ca-hardware","ca-hardware","ca-hardware","CompTIA A+: PC Hardware","🧩",1,"ca-hw-m1",
 "Core 1 hardware: the CPU, motherboard, memory, storage, power, and the connectors that tie a PC together.",[
  L("ca-hw-01","cpu-motherboard","CPUs & Motherboards",20,50,
   "The CPU executes instructions; the motherboard connects everything. A+ expects you to identify sockets, chipsets, and form factors.",
   [S("The CPU",ul=[{"b":"Cores/threads:","t":"parallel work; more cores help multitasking."},{"b":"Clock speed (GHz):","t":"cycles per second."},{"b":"Cache:","t":"fast on-die memory (L1/L2/L3)."},{"b":"Sockets:","t":"Intel LGA vs AMD AM4/AM5 — CPU must match the socket."}]),
    S("The motherboard",ul=[{"b":"Form factors:","t":"ATX, microATX, Mini-ITX (size/expansion trade-off)."},{"b":"Chipset:","t":"controls I/O between CPU, RAM, and buses."},{"b":"Expansion:","t":"PCIe slots (x16 for GPUs, x1 for cards)."}],note={"kind":"tip","text":"Match CPU socket, RAM type, and form factor to the case/PSU before buying."}),
    S("Cooling",p="CPUs need cooling — heatsink + fan (air) or liquid. Apply thermal paste between CPU and heatsink; overheating causes throttling and shutdowns.")],
   "List the three things that must be compatible between a CPU and a motherboard.",
   [Q("A CPU must match the motherboard's…",["Color","Socket","Fan brand","Case size"],1,"The socket (LGA/AM4/AM5) must match the CPU."),
    Q("Which form factor is the largest with the most expansion?",["Mini-ITX","microATX","ATX","Nano-ITX"],2,"ATX is the largest common form factor."),
    Q("A GPU typically uses which slot?",["PCIe x1","PCIe x16","RAM slot","SATA"],1,"Graphics cards use the PCIe x16 slot.")]),
  L("ca-hw-02","memory-storage","Memory & Storage",20,50,
   "RAM holds data the CPU is actively using; storage keeps it long-term. Know the types and their speeds.",
   [S("RAM",ul=[{"b":"DDR generations:","t":"DDR3/DDR4/DDR5 — not interchangeable (different notches)."},{"b":"DIMM vs SODIMM:","t":"desktop vs laptop modules."},{"b":"Channels:","t":"dual-channel (matched pairs) boosts bandwidth."}]),
    S("Storage",ul=[{"b":"HDD:","t":"spinning platters, cheap capacity, slower."},{"b":"SSD (SATA):","t":"no moving parts, much faster."},{"b":"NVMe (M.2):","t":"SSD over PCIe — fastest common storage."}],note={"kind":"info","text":"RAM is volatile (lost on power off); storage is non-volatile."}),
    S("Interfaces",p="SATA connects HDDs/SSDs (data + power cables). M.2 slots take NVMe or SATA modules directly on the board.")],
   "Rank HDD, SATA SSD, and NVMe SSD from slowest to fastest.",
   [Q("Which is volatile (cleared on power off)?",["SSD","HDD","RAM","NVMe"],2,"RAM is volatile working memory."),
    Q("The fastest common storage interface is…",["SATA HDD","SATA SSD","NVMe (M.2)","USB 2.0"],2,"NVMe over PCIe is fastest."),
    Q("Dual-channel RAM requires…",["One stick","Matched pairs","DDR3 only","An SSD"],1,"Matched pairs enable dual-channel bandwidth.")]),
  L("ca-hw-03","power-connectors","Power, Connectors & Peripherals",20,50,
   "The PSU powers everything; ports and connectors link peripherals. A+ tests connector identification.",
   [S("Power supply (PSU)",ul=[{"b":"Wattage:","t":"must exceed total system draw (GPU-heavy builds need more)."},{"b":"Rails/connectors:","t":"24-pin board, CPU 8-pin, PCIe for GPU, SATA for drives."},{"b":"Efficiency:","t":"80 PLUS ratings."}],note={"kind":"warn","text":"Never open a PSU — capacitors can hold a dangerous charge even unplugged."}),
    S("Common ports",ul=[{"b":"Video:","t":"HDMI, DisplayPort, VGA (legacy), DVI."},{"b":"USB:","t":"USB-A, USB-C; USB 3.x is faster (often blue)."},{"b":"Network:","t":"RJ-45 (Ethernet)."}]),
    S("Peripherals",p="Know input (keyboard, mouse, scanner) vs output (monitor, printer) and how they connect (USB, Bluetooth, wireless dongles).")],
   "Name the PSU connector used for the motherboard, the CPU, and a GPU.",
   [Q("The main motherboard power connector is…",["8-pin","24-pin","SATA","Molex"],1,"The 24-pin ATX connector powers the board."),
    Q("Which port is network (Ethernet)?",["RJ-11","RJ-45","HDMI","USB-C"],1,"RJ-45 is the Ethernet connector."),
    Q("You should never open a PSU because…",["It voids nothing","Capacitors can hold a charge","It's glued","It has no parts"],1,"Stored charge in capacitors is a shock hazard.")]),
 ])

networking = C("ca-net","ca-net","ca-net","CompTIA A+: Networking Basics","🌐",2,"ca-net-m1",
 "Core 1 networking at A+ depth: addressing, ports and protocols, cabling, and small-office/home wireless.",[
  L("ca-net-01","fundamentals","Networking Fundamentals",20,50,
   "How devices find and talk to each other: IP addresses, ports, and the common protocols A+ expects you to recall.",
   [S("Addressing",ul=[{"b":"IPv4:","t":"four octets, e.g. 192.168.1.10."},{"b":"Private ranges:","t":"10.x, 172.16–31.x, 192.168.x (home/office)."},{"b":"DHCP/DNS:","t":"DHCP assigns IPs; DNS resolves names to IPs."}]),
    S("Common ports",ul=["HTTP 80 / HTTPS 443","DNS 53","DHCP 67/68","SSH 22 / RDP 3389","SMTP 25 / IMAP 143 / POP3 110"],note={"kind":"tip","text":"A+ expects these port numbers from memory."}),
    S("TCP vs UDP",p="TCP is reliable/ordered (web, email); UDP is fast/connectionless (streaming, DNS queries).")],
   "Write the port numbers for HTTPS, DNS, SSH, and RDP.",
   [Q("HTTPS uses port…",["80","443","22","53"],1,"HTTPS is 443."),
    Q("Which assigns IP addresses automatically?",["DNS","DHCP","RDP","SMTP"],1,"DHCP hands out IP leases."),
    Q("RDP (Remote Desktop) uses port…",["22","3389","443","25"],1,"RDP is TCP 3389.")]),
  L("ca-net-02","cabling","Cabling & Connectors",18,50,
   "Copper and fiber carry the network. Know the categories, connectors, and when to use each.",
   [S("Copper (twisted pair)",ul=[{"b":"Cat 5e:","t":"1 Gbps."},{"b":"Cat 6/6a:","t":"up to 10 Gbps (6a longer runs)."},{"b":"Connector:","t":"RJ-45."}]),
    S("Fiber",ul=[{"b":"Single-mode:","t":"long distance."},{"b":"Multi-mode:","t":"shorter runs, cheaper."},{"b":"Immune to EMI","t":"— good near interference."}]),
    S("Coax & other",p="Coaxial (RG-6) for cable internet/TV. Know max copper run ~100 m before signal loss.")],
   "Which cable category would you choose for a 10 Gbps run, and what connector does it use?",
   [Q("Twisted-pair copper uses which connector?",["RJ-11","RJ-45","SC","BNC"],1,"RJ-45 terminates twisted-pair Ethernet."),
    Q("For the longest distance, choose…",["Cat 5e","Multi-mode fiber","Single-mode fiber","Coax"],2,"Single-mode fiber carries longest."),
    Q("Max recommended copper Ethernet run is about…",["10 m","100 m","1 km","500 m"],1,"~100 m before signal degrades.")]),
  L("ca-net-03","wireless-soho","Wireless & SOHO Networks",20,50,
   "Setting up and securing a small-office/home network — the everyday tech task A+ centers on.",
   [S("Wi-Fi standards",ul=[{"b":"802.11n/ac/ax:","t":"ax (Wi-Fi 6) is newest/fastest."},{"b":"Bands:","t":"2.4 GHz (range) vs 5 GHz (speed)."}]),
    S("Securing the network",ul=[{"b":"WPA2/WPA3:","t":"use WPA3 or WPA2-AES; never WEP."},{"b":"Change defaults:","t":"admin password + SSID."},{"b":"Guest network:","t":"isolate visitors."}],note={"kind":"warn","text":"WEP is broken — never use it."}),
    S("SOHO setup",p="A combo router does routing, switching, Wi-Fi, DHCP, and NAT. Port forwarding exposes an internal service; enable a firewall.")],
   "List three steps to secure a new home router.",
   [Q("The strongest listed Wi-Fi security is…",["WEP","WPA","WPA2","WPA3"],3,"WPA3 is the current strongest."),
    Q("Which band offers more range (less speed)?",["5 GHz","2.4 GHz","6 GHz","60 GHz"],1,"2.4 GHz reaches farther."),
    Q("First thing to change on a new router…",["Wall color","Default admin password","Nothing","The cable"],1,"Change default admin credentials immediately.")]),
 ])

mobilecloud = C("ca-mc","ca-mc","ca-mc","CompTIA A+: Mobile, Virtualization & Cloud","📱",3,"ca-mc-m1",
 "Mobile device support plus the virtualization and cloud concepts now core to Core 1.",[
  L("ca-mc-01","mobile","Mobile Devices",18,50,
   "Laptops and phones have their own components, connectors, and sync/security needs.",
   [S("Laptop specifics",ul=[{"b":"SODIMM RAM, M.2 storage","t":"— smaller modules."},{"b":"Display types:","t":"IPS, OLED; digitizer for touch."},{"b":"Function keys","t":"toggle Wi-Fi, brightness, external display."}]),
    S("Connectivity & sync",ul=["Bluetooth for peripherals","Hotspot/tethering shares cellular","Sync to cloud (contacts, photos) across devices"]),
    S("Mobile security",note={"kind":"tip","text":"Screen lock, biometrics, remote wipe, and encryption protect lost devices."})],
   "Name two components that differ physically between a laptop and a desktop.",
   [Q("Laptop RAM modules are called…",["DIMM","SODIMM","NVMe","RJ-45"],1,"Laptops use smaller SODIMM modules."),
    Q("Sharing a phone's cellular data to a laptop is…",["Tethering/hotspot","DNS","RDP","NAT"],0,"Tethering/hotspot shares the connection."),
    Q("Best protection for a lost phone's data…",["Louder ringtone","Remote wipe + encryption","Bigger screen","New SIM"],1,"Remote wipe and encryption protect data.")]),
  L("ca-mc-02","virtualization","Virtualization",18,50,
   "One physical machine runs multiple virtual machines via a hypervisor — foundational to modern IT.",
   [S("Hypervisors",ul=[{"b":"Type 1 (bare-metal):","t":"runs on hardware (ESXi, Hyper-V) — servers."},{"b":"Type 2 (hosted):","t":"runs on an OS (VirtualBox, VMware Workstation) — desktops."}]),
    S("Why virtualize",ul=["Consolidate servers","Isolate/sandbox testing","Snapshots for quick rollback"]),
    S("Requirements",note={"kind":"info","text":"Need CPU virtualization (Intel VT-x/AMD-V) enabled in BIOS, plus enough RAM/CPU for each VM."})],
   "Give an example of a Type 1 and a Type 2 hypervisor.",
   [Q("A bare-metal (Type 1) hypervisor…",["Runs on an OS","Runs directly on hardware","Is a browser","Needs no CPU"],1,"Type 1 runs directly on hardware."),
    Q("VirtualBox on your Windows laptop is…",["Type 1","Type 2","A firewall","A NIC"],1,"Hosted on an OS = Type 2."),
    Q("Which BIOS feature must be enabled for VMs?",["Secure Boot only","CPU virtualization (VT-x/AMD-V)","RAID","Fast boot"],1,"Hardware virtualization must be enabled.")]),
  L("ca-mc-03","cloud","Cloud Concepts",18,50,
   "Cloud delivers computing over the internet. A+ expects the service and deployment models.",
   [S("Service models",ul=[{"b":"IaaS:","t":"VMs/storage (you manage the OS up)."},{"b":"PaaS:","t":"a platform to deploy apps."},{"b":"SaaS:","t":"finished apps (M365, Gmail)."}]),
    S("Deployment models",ul=[{"b":"Public:","t":"shared provider (AWS/Azure)."},{"b":"Private:","t":"dedicated."},{"b":"Hybrid:","t":"mix."}]),
    S("Cloud traits",note={"kind":"info","text":"On-demand, elastic (scale up/down), measured/pay-as-you-go, accessible anywhere."})],
   "Classify Microsoft 365, an Azure VM, and a managed app platform as SaaS/IaaS/PaaS.",
   [Q("Microsoft 365 (finished apps) is…",["IaaS","PaaS","SaaS","On-prem"],2,"Ready-to-use apps = SaaS."),
    Q("Renting a bare VM in the cloud is…",["IaaS","SaaS","PaaS","LAN"],0,"Infrastructure (VMs) = IaaS."),
    Q("'Scale up/down on demand' describes…",["Elasticity","Latency","A firewall","A driver"],0,"Elasticity is on-demand scaling.")]),
 ])

os = C("ca-os","ca-os","ca-os","CompTIA A+: Operating Systems","🪟",4,"ca-os-m1",
 "Core 2 operating systems: types, installation, Windows configuration, and the command line.",[
  L("ca-os-01","types-install","OS Types & Installation",20,50,
   "Know the major operating systems and how they're installed and organized.",
   [S("Major OSes",ul=[{"b":"Windows:","t":"most common desktop; editions (Home/Pro)."},{"b":"macOS:","t":"Apple hardware."},{"b":"Linux:","t":"open-source; many distros."},{"b":"Mobile:","t":"Android, iOS."}]),
    S("Install types",ul=[{"b":"Clean install","t":"wipes and installs fresh."},{"b":"Upgrade","t":"keeps files/apps."},{"b":"Image/deployment","t":"clone a standard build."}]),
    S("File systems",note={"kind":"info","text":"Windows uses NTFS (permissions, journaling); exFAT/FAT32 for removable media; Linux uses ext4."})],
   "When would you choose a clean install over an in-place upgrade?",
   [Q("Windows' primary file system is…",["FAT32","NTFS","ext4","APFS"],1,"NTFS is Windows' default."),
    Q("A clean install…",["Keeps all apps","Wipes and installs fresh","Only updates drivers","Is an upgrade"],1,"Clean install wipes the target."),
    Q("Best file system for a cross-platform USB drive…",["NTFS","ext4","exFAT","APFS"],2,"exFAT works across OSes for large files.")]),
  L("ca-os-02","windows-config","Windows Configuration",20,50,
   "The Windows tools A+ techs use daily to configure and manage a system.",
   [S("Key tools",ul=[{"b":"Control Panel / Settings","t":"— system config."},{"b":"Task Manager","t":"— processes, startup, performance."},{"b":"Device Manager","t":"— drivers/hardware."},{"b":"Disk Management","t":"— partitions/volumes."}]),
    S("User & system",ul=["User accounts & UAC (elevation)","Services (services.msc)","Event Viewer for logs"]),
    S("Updates",note={"kind":"tip","text":"Keep Windows Update current; drivers via Device Manager or vendor."})],
   "Which tool would you open to disable a startup program, and which to update a driver?",
   [Q("Disable a startup app with…",["Device Manager","Task Manager","Disk Management","Event Viewer"],1,"Task Manager's Startup tab."),
    Q("Update a hardware driver in…",["Task Manager","Device Manager","Control Panel > Sound","Notepad"],1,"Device Manager manages drivers."),
    Q("UAC prompts exist to…",["Slow you down","Require elevation for admin changes","Play sounds","Update apps"],1,"UAC gates administrative actions.")]),
  L("ca-os-03","command-line","Command-Line Basics",20,50,
   "A+ expects core commands in Windows (and awareness of Linux equivalents).",
   [S("Windows CLI",code="dir            # list files\ncd folder      # change directory\nipconfig /all  # network config\nping host      # test connectivity\nsfc /scannow   # repair system files\nchkdsk /f      # check disk"),
    S("Networking checks",ul=["ipconfig / ping / tracert / nslookup","netstat for connections"]),
    S("Linux equivalents",note={"kind":"info","text":"ls, cd, ifconfig/ip, ping, cat — transferable concepts."})],
   "Write the Windows commands to view IP config and to repair system files.",
   [Q("Which lists a directory in Windows CMD?",["ls","dir","cat","pwd"],1,"dir lists files in CMD."),
    Q("Repair corrupted system files with…",["chkdsk","sfc /scannow","ping","dir"],1,"sfc /scannow verifies/repairs system files."),
    Q("Show full network configuration with…",["ping","ipconfig /all","tracert","netstat"],1,"ipconfig /all shows adapter details.")]),
 ])

security = C("ca-sec","ca-sec","ca-sec","CompTIA A+: Security","🛡️",5,"ca-sec-m1",
 "Core 2 security: threats and malware, best practices, and protecting devices and data.",[
  L("ca-sec-01","threats-malware","Security Threats & Malware",20,55,
   "Recognize the threats A+ techs defend against and how malware spreads.",
   [S("Malware types",ul=[{"b":"Virus/worm:","t":"self-replicating."},{"b":"Trojan:","t":"disguised as legit."},{"b":"Ransomware:","t":"encrypts for payment."},{"b":"Spyware/keylogger:","t":"steals info."}]),
    S("Social engineering",ul=[{"b":"Phishing:","t":"fake emails/links."},{"b":"Tailgating, shoulder surfing","t":"— physical."},{"b":"Pretexting","t":"— a fabricated scenario."}],note={"kind":"warn","text":"The human is the most common attack vector — train users."}),
    S("Response",p="Isolate the machine, identify/quarantine, remediate (scan/clean or reimage), educate the user.")],
   "Match: encrypts files for payment; disguised as legitimate software; fake email to steal credentials.",
   [Q("Ransomware…",["Speeds the PC","Encrypts files for payment","Updates drivers","Is hardware"],1,"Ransomware extorts by encrypting data."),
    Q("A fake email to steal credentials is…",["Phishing","A trojan","A worm","Spam filter"],0,"That's phishing (social engineering)."),
    Q("The most common attack vector is…",["The CPU","The human user","The PSU","The monitor"],1,"Users are the top target.")]),
  L("ca-sec-02","best-practices","Security Best Practices",20,55,
   "Everyday hardening: authentication, least privilege, and safe configuration.",
   [S("Authentication",ul=[{"b":"Strong passwords + MFA","t":"— the biggest wins."},{"b":"Least privilege","t":"— users get only what they need."},{"b":"Account lockout","t":"— slows brute force."}]),
    S("System hardening",ul=["Patch/update promptly","Antivirus/anti-malware","Disable unused services/ports","Firewall on"]),
    S("Data handling",note={"kind":"tip","text":"Encrypt sensitive data (BitLocker), back up (3-2-1), and wipe drives before disposal."})],
   "Name the single highest-impact account-security control and one hardening step.",
   [Q("The biggest single account-security win is…",["A louder alarm","Multi-factor authentication","A bigger monitor","More RAM"],1,"MFA sharply reduces compromise."),
    Q("Least privilege means…",["Admin for everyone","Only the access needed","No passwords","Open firewall"],1,"Grant minimum necessary access."),
    Q("Before disposing of a drive you should…",["Paint it","Securely wipe/destroy it","Email it","Nothing"],1,"Wipe or destroy to prevent data recovery.")]),
  L("ca-sec-03","physical-data","Physical & Data Security",18,55,
   "Security isn't only digital — physical access and proper disposal matter.",
   [S("Physical controls",ul=["Locks, badge access, mantraps","Cable locks for laptops","Screen privacy filters"]),
    S("Data destruction",ul=[{"b":"Wipe:","t":"overwrite (reusable)."},{"b":"Degauss/shred:","t":"physical destruction."},{"b":"Certificate of destruction","t":"for compliance."}]),
    S("Backups",note={"kind":"info","text":"3-2-1: three copies, two media types, one offsite. Test restores."})],
   "Give a physical control and a compliant data-destruction method.",
   [Q("A cable lock protects against…",["Malware","Laptop theft","Phishing","Power surges"],1,"Physical theft of the device."),
    Q("The 3-2-1 rule refers to…",["Passwords","Backups","Ports","Cables"],1,"3 copies, 2 media, 1 offsite backups."),
    Q("Physically destroying a drive by magnetic field is…",["Wiping","Degaussing","Encrypting","Imaging"],1,"Degaussing erases magnetically.")]),
 ])

troubleshooting = C("ca-ts","ca-ts","ca-ts","CompTIA A+: Troubleshooting","🔧",6,"ca-ts-m1",
 "The A+ troubleshooting methodology plus the most common hardware and software issues.",[
  L("ca-ts-01","methodology","Troubleshooting Methodology",18,55,
   "A+ teaches a repeatable 6-step method — memorize the order.",
   [S("The 6 steps",ul=["1. Identify the problem","2. Establish a theory (probable cause)","3. Test the theory","4. Establish a plan and implement","5. Verify full functionality (+ preventive measures)","6. Document findings, actions, outcomes"],note={"kind":"tip","text":"Always back up before making changes, and change one thing at a time."}),
    S("Good habits",p="Ask what changed, reproduce the issue, and check the simple things first (power, cables, connectivity)."),
    S("Escalate",p="If it's beyond your scope or time, escalate with your notes — don't sit on a blocker.")],
   "List the six troubleshooting steps in order from memory.",
   [Q("The first step is…",["Fix it","Identify the problem","Document","Reboot"],1,"Start by identifying the problem."),
    Q("Verifying functionality happens…",["First","Before testing","After implementing the fix","Never"],2,"Verify after implementing the solution."),
    Q("The final step is always…",["Reboot","Document findings","Buy hardware","Escalate"],1,"Document the outcome.")]),
  L("ca-ts-02","hardware-issues","Common Hardware Issues",18,55,
   "Recognize the symptoms of frequent hardware failures.",
   [S("Symptoms → causes",ul=[{"b":"No power/POST:","t":"PSU, power, RAM seating."},{"b":"Random shutdowns:","t":"overheating, failing PSU."},{"b":"BSOD:","t":"driver/RAM/storage."},{"b":"Clicking drive:","t":"failing HDD — back up now."}]),
    S("Overheating",p="Dust buildup, failed fans, or dried thermal paste cause throttling/shutdowns — clean and reapply paste."),
    S("Display/peripherals",note={"kind":"info","text":"No display: reseat GPU/RAM, check cable/input. Dead USB: try another port, check Device Manager."})],
   "A PC shuts down randomly under load — list two likely hardware causes.",
   [Q("A clicking hard drive means…",["It's fine","Imminent failure — back up","Low RAM","A virus"],1,"Clicking indicates mechanical failure."),
    Q("Random shutdowns under load suggest…",["Overheating/PSU","A DNS issue","Wrong wallpaper","A full mailbox"],0,"Heat or a failing PSU."),
    Q("No display first steps…",["Reinstall Windows","Reseat GPU/RAM, check cable/input","Replace CPU","Format disk"],1,"Check seating and the video cable/input.")]),
  L("ca-ts-03","software-issues","Common OS & Software Issues",18,55,
   "The everyday software problems A+ techs resolve.",
   [S("OS symptoms",ul=[{"b":"Slow performance:","t":"startup apps, malware, low disk/RAM."},{"b":"App crashes:","t":"update/reinstall, check compatibility."},{"b":"Boot issues:","t":"Startup Repair, safe mode."}]),
    S("Malware signs",ul=["Pop-ups, redirects, unknown processes, slowdowns → scan and clean/reimage"]),
    S("Method",note={"kind":"tip","text":"Reproduce, check recent changes, update, and apply the same 6-step method."})],
   "A user reports a slow PC — list three things you'd check first.",
   [Q("First check for a slow PC…",["Buy new PC","Startup apps, disk space, malware","Repaint case","Replace monitor"],1,"Startup load, disk/RAM, and malware."),
    Q("Repeated pop-ups and redirects suggest…",["A GPU issue","Malware","A dead PSU","Low volume"],1,"Likely malware — scan the system."),
    Q("A non-booting Windows PC → try…",["New RAM only","Safe mode / Startup Repair","Reinstall Office","Change wallpaper"],1,"Use safe mode and Startup Repair.")]),
 ])

for c in (hardware, networking, mobilecloud, os, security, troubleshooting):
    man["courses"].append(c)
OUT.write_text(json.dumps(man, ensure_ascii=False))
print("p28 manifest:", len(man["courses"]), "courses,", sum(len(c["lessons"]) for c in man["courses"]), "lessons,",
      sum(len(l["quiz"]) for c in man["courses"] for l in c["lessons"]), "quiz questions")
