#!/usr/bin/env python3
"""Phase 3b: Python 9 -> 25 lessons (IT-automation focus)."""
import json, pathlib
MAN=pathlib.Path('/home/claude/it-academy/scripts/manifests/p29.json'); man=json.loads(MAN.read_text())
def L(i,s,t,mi,x,intro,se,pr,q):return{"id":i,"slug":s,"title":t,"minutes":mi,"xp":x,"content":{"intro":intro,"sections":se,"practice":pr},"quiz":q}
def S(h,p=None,ul=None,note=None,code=None):
    d={"h":h}
    if p:d["p"]=p if isinstance(p,list) else [p]
    if ul:d["ul"]=ul
    if code:d["code"]=code
    if note:d["note"]=note
    return d
def Q(p,o,ci,ex):return{"p":p,"o":o,"ci":ci,"ex":ex}
def RW(t):return{"kind":"info","text":"In the real world: "+t}
PY=[
 L("sc-py-10","lists-comprehensions","Lists & Comprehensions",20,60,
  "Lists are the workhorse collection; comprehensions make transforming them concise.",
  [S("List basics",code="hosts = ['srv01','srv02','srv03']\nhosts.append('srv04')\nhosts[0]            # 'srv01'\nhosts[-1]           # last\nlen(hosts)"),
   S("Comprehensions",code="up = [h.upper() for h in hosts]\nweb = [h for h in hosts if h.startswith('srv')]\nports = [(h, 443) for h in hosts]"),
   S("Why it matters",note=RW("Comprehensions replace loop boilerplate — building a list of unreachable hosts or failed logins becomes a single readable line.")),],
  "Write a comprehension that keeps only hostnames starting with 'db'.",
  [Q("Add to the end of a list with…",[".add()",".append()",".push()",".insert() only"],1,"list.append() adds an item."),
   Q("[x*2 for x in nums] is a…",["loop","comprehension","function","dict"],1,"That's a list comprehension."),
   Q("hosts[-1] returns the…",["first","last","length","error"],1,"Negative index counts from the end.")]),
 L("sc-py-11","dicts-sets","Dictionaries & Sets",20,60,
  "Key/value lookups and unique collections — essential for structured data.",
  [S("Dictionaries",code="user = {'name':'Ada','dept':'IT'}\nuser['dept']             # 'IT'\nuser.get('phone','n/a')  # safe default\nfor k,v in user.items(): print(k,v)"),
   S("Sets",code="a = {1,2,3}; b = {3,4}\na & b   # intersection {3}\na | b   # union\na - b   # difference"),
   S("Use cases",note=RW("Dicts model records (a user, a server) and sets dedupe fast — e.g. comparing 'accounts in AD' vs 'accounts in HR' is one set difference.")),],
  "Given two sets of usernames, write the expression for accounts in AD but not HR.",
  [Q("Safe key access with a default uses…",["[]",".get()",".find()",".key()"],1,".get(key, default) avoids KeyError."),
   Q("Unique items are stored in a…",["list","set","tuple","str"],1,"A set holds unique values."),
   Q("Set intersection uses…",["|","&","-","^"],1,"& gives common elements.")]),
 L("sc-py-12","csv","Working with CSV",20,60,
  "CSV is the universal exchange format for IT data — read and write it cleanly.",
  [S("Read",code="import csv\nwith open('users.csv', newline='') as f:\n    for row in csv.DictReader(f):\n        print(row['email'])"),
   S("Write",code="with open('out.csv','w',newline='') as f:\n    w = csv.DictWriter(f, fieldnames=['host','status'])\n    w.writeheader()\n    w.writerow({'host':'srv01','status':'up'})"),
   S("Bulk ops",note=RW("DictReader turns each row into a dict keyed by header — feed a CSV of new hires straight into an account-creation loop.")),],
  "Write a loop that prints the 'email' column of every row in users.csv.",
  [Q("Read rows as dicts with…",["csv.DictReader","csv.reader only","open()","json.load"],0,"DictReader keys by header."),
   Q("Always open CSV files with…",["newline=''","binary","append","no args"],0,"newline='' avoids blank rows on Windows."),
   Q("Write a header row with…",["writeheader()","header()","writerow('h')","top()"],0,"DictWriter.writeheader() emits headers.")]),
 L("sc-py-13","json","Working with JSON",18,55,
  "JSON is how APIs and config files speak — parse and produce it.",
  [S("Parse & dump",code="import json\ndata = json.loads('{\"name\":\"srv01\"}')\ndata['name']\njson.dumps({'ok':True}, indent=2)"),
   S("Files",code="with open('config.json') as f:\n    cfg = json.load(f)\nwith open('out.json','w') as f:\n    json.dump(cfg, f, indent=2)"),
   S("APIs",note=RW("Nearly every REST response is JSON — json handling is the bridge between an API call and a usable Python object.")),],
  "Write code that loads config.json into a dict.",
  [Q("Parse a JSON string with…",["json.loads","json.read","json.parse","load_json"],0,"json.loads parses a string."),
   Q("Read JSON from a file with…",["json.load(f)","json.loads(f)","f.json()","read_json"],0,"json.load reads from a file object."),
   Q("Pretty-print JSON with…",["indent=","pretty=True","format()","tab()"],0,"json.dumps(..., indent=2).")]),
 L("sc-py-14","xml","Working with XML",18,55,
  "Legacy systems and some configs still use XML — parse it with the standard library.",
  [S("Parse",code="import xml.etree.ElementTree as ET\ntree = ET.parse('data.xml')\nroot = tree.getroot()\nfor item in root.findall('item'):\n    print(item.get('id'), item.text)"),
   S("From a string",code="root = ET.fromstring('<r><a>1</a></r>')\nroot.find('a').text   # '1'"),
   S("When you meet it",note=RW("Windows event exports, some monitoring feeds, and older APIs return XML — ElementTree extracts the fields you need without extra dependencies.")),],
  "Write code that prints the text of every <item> element in data.xml.",
  [Q("Parse an XML file with…",["ET.parse","ET.json","xml.read","parse_xml"],0,"ElementTree.parse loads a file."),
   Q("Find matching child elements with…",["findall()","search()","grep()","query()"],0,"Element.findall() returns matches."),
   Q("An attribute value is read with…",[".get()",".attr",".value",".text"],0,"element.get('attr').")]),
 L("sc-py-15","apis-advanced","REST APIs: Auth, Pagination & Errors",22,65,
  "Real APIs need auth, handle paging, and fail — write clients that cope.",
  [S("Auth & errors",code="import requests\nr = requests.get(url, headers={'Authorization':f'Bearer {token}'}, timeout=10)\nr.raise_for_status()\ndata = r.json()"),
   S("Pagination",code="results, page = [], 1\nwhile True:\n    r = requests.get(url, params={'page':page}).json()\n    results += r['items']\n    if not r.get('next'): break\n    page += 1"),
   S("Resilience",note=RW("Timeouts, raise_for_status, and retry/backoff separate a script that dies at 2am from one that logs the error and moves on — essential for unattended automation.")),],
  "Write a paginated GET loop that stops when there's no 'next' page.",
  [Q("Stop a script on HTTP errors with…",["raise_for_status()","try only","ignore","r.ok print"],0,"raise_for_status() raises on 4xx/5xx."),
   Q("Prevent hanging calls with…",["timeout=","wait=","sleep()","block=False"],0,"Pass timeout= to requests."),
   Q("Pagination usually loops until…",["no next page","one call","an error","forever"],0,"Stop when there's no next page/cursor.")]),
 L("sc-py-16","ssh-paramiko","SSH Automation with Paramiko",22,65,
  "Run commands on remote Linux hosts from Python — core cross-platform admin.",
  [S("Connect & run",code="import paramiko\nc = paramiko.SSHClient()\nc.set_missing_host_key_policy(paramiko.AutoAddPolicy())\nc.connect('host', username='admin', key_filename='~/.ssh/id_rsa')\nstdin, stdout, stderr = c.exec_command('df -h')\nprint(stdout.read().decode())\nc.close()"),
   S("Best practices",ul=["Prefer key auth over passwords","Set timeouts","Close connections / use context managers"]),
   S("Fleet automation",note=RW("Paramiko lets one script push a command or config to dozens of Linux servers — the Python equivalent of PowerShell remoting for the *nix side of the house.")),],
  "Write the calls to connect via key auth and run 'uptime' on a remote host.",
  [Q("The Python SSH library is…",["paramiko","ssh2","netssh","pyssh only"],0,"Paramiko is the standard SSH lib."),
   Q("Run a remote command with…",["exec_command","run()","shell()","cmd()"],0,"SSHClient.exec_command()."),
   Q("Preferred remote auth is…",["password in code","SSH keys","no auth","telnet"],1,"Key-based auth is more secure.")]),
 L("sc-py-17","networking","Network Automation",20,60,
  "Check reachability and ports from Python for diagnostics and monitoring.",
  [S("Port check",code="import socket\ndef port_open(host, port, t=2):\n    with socket.socket() as s:\n        s.settimeout(t)\n        return s.connect_ex((host, port)) == 0\nport_open('srv01', 443)"),
   S("Ping via subprocess",code="import subprocess\nsubprocess.run(['ping','-c','1','host'], capture_output=True)"),
   S("Sweeps",note=RW("A short socket loop can scan a list of hosts/ports to confirm a service rollout — faster and more repeatable than manual telnet checks.")),],
  "Write a function that returns True if a TCP port is open on a host.",
  [Q("Low-level TCP checks use the…",["socket","http","json","os"],0,"The socket module."),
   Q("connect_ex returns 0 when…",["closed","the port is open","error","timeout"],1,"0 means the connection succeeded."),
   Q("Run an external ping with…",["subprocess.run","os.ping","net.ping","socket.ping"],0,"subprocess.run invokes the OS command.")]),
 L("sc-py-18","monitoring","Monitoring with psutil",20,60,
  "Read live system metrics in Python and alert on thresholds.",
  [S("Metrics",code="import psutil\npsutil.cpu_percent(interval=1)\npsutil.virtual_memory().percent\npsutil.disk_usage('/').percent"),
   S("Threshold alert",code="if psutil.disk_usage('/').percent > 90:\n    print('ALERT: disk over 90%')"),
   S("Cross-platform",note=RW("psutil works on Windows and Linux, so one monitoring script covers a mixed fleet — schedule it and pipe alerts to email or a webhook.")),],
  "Write a check that alerts when memory usage exceeds 85%.",
  [Q("Live system metrics come from…",["psutil","os only","sys","socket"],0,"psutil exposes CPU/mem/disk."),
   Q("Disk usage percent is…",["disk_usage(path).percent","df()","disk.pct","usage()"],0,"psutil.disk_usage(path).percent."),
   Q("psutil runs on…",["Windows only","Linux only","both","neither"],2,"It's cross-platform.")]),
 L("sc-py-19","email-automation","Email Automation",20,60,
  "Send reports and alerts programmatically with smtplib.",
  [S("Send mail",code="import smtplib\nfrom email.message import EmailMessage\nm = EmailMessage()\nm['From']='bot@corp'; m['To']='it@corp'; m['Subject']='Disk alert'\nm.set_content('srv01 disk at 92%')\nwith smtplib.SMTP('smtp.corp', 587) as s:\n    s.starttls(); s.login('bot','pw'); s.send_message(m)"),
   S("Attach a report",p="Use m.add_attachment(...) to attach a CSV/HTML report generated by your script."),
   S("Alerting loop",note=RW("Wiring monitoring + email means the system tells you about problems — the shift from reactive ('users reported it') to proactive ('the script caught it first').")),],
  "Outline the steps to send an alert email with a CSV attachment.",
  [Q("Send email in Python with…",["smtplib","emaillib","mailer","sendmail()"],0,"smtplib sends over SMTP."),
   Q("Encrypt the SMTP session with…",["starttls()","secure()","ssl_on","encrypt()"],0,"starttls() upgrades to TLS."),
   Q("Build the message with…",["EmailMessage","dict","str only","MailObj"],0,"email.message.EmailMessage.")]),
 L("sc-py-20","file-automation","File & Folder Automation",20,60,
  "Batch file operations with os, shutil, and pathlib.",
  [S("pathlib",code="from pathlib import Path\nfor p in Path('logs').glob('*.log'):\n    print(p.name, p.stat().st_size)"),
   S("Move / copy / delete",code="import shutil, os\nshutil.copy('a.txt','backup/')\nshutil.move('b.tmp','archive/')\nos.remove('old.log')"),
   S("Batch rename",code="for i, p in enumerate(Path('.').glob('*.jpg')):\n    p.rename(f'img_{i:03}.jpg')",note=RW("A 10-line pathlib script renames or sorts thousands of files consistently — the kind of tedious task that eats an afternoon by hand.")),],
  "Write a loop that prints the size of every .log file in a folder.",
  [Q("The modern path API is…",["pathlib","os.path only","filelib","dirlib"],0,"pathlib.Path is the modern API."),
   Q("Copy a file with…",["shutil.copy","os.copy","file.copy","cp()"],0,"shutil.copy() copies files."),
   Q("Match files by pattern with…",["glob()","find()","match()","ls()"],0,"Path.glob('*.ext').")]),
 L("sc-py-21","report-generation","Report Generation",20,60,
  "Turn collected data into readable CSV and HTML reports.",
  [S("CSV report",code="import csv\nrows = [{'host':'srv01','free':'12%'}]\nwith open('report.csv','w',newline='') as f:\n    w = csv.DictWriter(f, fieldnames=rows[0].keys()); w.writeheader(); w.writerows(rows)"),
   S("Simple HTML",code="html = '<table>' + ''.join(\n  f\"<tr><td>{r['host']}</td><td>{r['free']}</td></tr>\" for r in rows) + '</table>'\nopen('report.html','w').write(html)"),
   S("Deliver",note=RW("Pair report generation with email or a shared folder and you've built an automated daily/weekly status report — a visible win that makes your work matter to managers.")),],
  "Write code that writes a list of dicts to a CSV report with a header.",
  [Q("Write many dict rows with…",["writerows()","writeall()","dump()","save()"],0,"DictWriter.writerows()."),
   Q("A quick web-viewable report format is…",["HTML","EXE","ISO","BIN"],0,"HTML renders in any browser."),
   Q("Reports become valuable when they're…",["hidden","delivered/scheduled","deleted","manual"],1,"Automated delivery drives impact.")]),
 L("sc-py-22","ticket-automation","Ticket Automation",22,65,
  "Create and update tickets via a REST API — connect monitoring to your ITSM.",
  [S("Create a ticket",code="import requests\npayload = {'title':'Disk full on srv01','priority':'high'}\nr = requests.post(f'{base}/tickets', json=payload,\n                  headers={'Authorization':f'Bearer {token}'})\nticket_id = r.json()['id']"),
   S("Update / comment",code="requests.patch(f'{base}/tickets/{ticket_id}', json={'status':'in_progress'})"),
   S("Close the loop",note=RW("When a monitor detects an issue and opens a ticket automatically — with the host, metric, and timestamp pre-filled — you turn noise into tracked, assignable work.")),],
  "Outline how a monitoring alert would open a ticket via an API.",
  [Q("Create a resource via API with…",["POST","GET","DELETE","HEAD"],0,"POST creates a new ticket."),
   Q("The new ticket's id comes from…",["the response JSON","the URL only","a guess","the headers only"],0,"Read it from r.json()."),
   Q("Partial updates typically use…",["PATCH","GET","OPTIONS","TRACE"],0,"PATCH updates fields.")]),
 L("sc-py-23","helpdesk-automation","Help Desk Automation Projects",22,65,
  "Practical scripts that remove repetitive help-desk toil.",
  [S("Bulk actions from CSV",code="import csv\nfor row in csv.DictReader(open('resets.csv')):\n    # call your identity API / log the action\n    print('reset requested for', row['user'])"),
   S("Common wins",ul=["Bulk password-reset requests / logging","Stale-account report (last login > 90d)","Auto-triage: tag tickets by keyword"]),
   S("Value",note=RW("Automating even a 5-minute task done 30x/day frees hours weekly — help-desk automation is the clearest, fastest ROI you can demonstrate.")),],
  "Describe a help-desk task you'd automate and the inputs/outputs.",
  [Q("Bulk help-desk actions are driven from…",["a CSV/list","one manual entry","the registry","a screenshot"],0,"Feed actions from a CSV/list."),
   Q("A high-ROI target for automation is…",["a rare 1x task","a frequent repetitive task","a creative task","a meeting"],1,"Frequent, repetitive tasks pay back fastest."),
   Q("Auto-triage tags tickets by…",["keyword/rules","random","color","size"],0,"Keyword/rule matching classifies tickets.")]),
 L("sc-py-24","sysadmin-project","System Administration Project",22,70,
  "A multi-step project: inventory a fleet and flag issues.",
  [S("The brief",p="Read a list of hosts, check each host's reachability and (via SSH) disk usage, and produce a report of hosts over 85% disk."),
   S("Skeleton",code="import paramiko, csv\nresults = []\nfor host in open('hosts.txt').read().split():\n    try:\n        c = paramiko.SSHClient(); c.set_missing_host_key_policy(paramiko.AutoAddPolicy())\n        c.connect(host, username='admin', timeout=5)\n        out = c.exec_command('df -h / | tail -1')[1].read().decode()\n        results.append({'host':host, 'disk':out.split()[4]})\n        c.close()\n    except Exception as e:\n        results.append({'host':host, 'disk':f'ERR {e}'})"),
   S("Finish",ul=["Write results to CSV","Flag/alert hosts over threshold","Handle unreachable hosts gracefully"],note=RW("A fleet inventory-and-flag script is a staple sysadmin deliverable — it shows you can combine remoting, error handling, and reporting.")),],
  "List the three steps this fleet-check project performs per host.",
  [Q("Per-host failures should be…",["ignored","caught and recorded","fatal","retried forever"],1,"Catch errors so one bad host doesn't stop the run."),
   Q("Remote disk info is gathered via…",["paramiko + df","local os only","a GUI","ping"],0,"SSH runs df on each host."),
   Q("Results are delivered as…",["a CSV/report","nothing","print once","a reboot"],0,"Export a CSV/report.")]),
 L("sc-py-25","capstone","Capstone: Server Health Monitor",26,85,
  "Bring it together: a scheduled monitor that reports and alerts.",
  [S("The brief",p="Every run: gather CPU, memory, and disk via psutil; if any exceeds its threshold, send an email alert; always append a timestamped row to a CSV history."),
   S("Skeleton",code="import psutil, csv, smtplib\nfrom datetime import datetime\nfrom email.message import EmailMessage\n\nm = {'time':datetime.now().isoformat(),\n     'cpu':psutil.cpu_percent(1),\n     'mem':psutil.virtual_memory().percent,\n     'disk':psutil.disk_usage('/').percent}\nwith open('health.csv','a',newline='') as f:\n    csv.DictWriter(f, fieldnames=m).writerow(m)\nif m['disk'] > 90 or m['mem'] > 90:\n    pass  # send_alert(m) via smtplib"),
   S("Ship it",ul=["Wrap in try/except + logging","Schedule (cron / Task Scheduler)","Send email or webhook on threshold breach"],note=RW("This capstone is genuinely deployable — CPU/mem/disk monitoring with history and alerts is something small teams actually run in production.")),],
  "Name the three metrics the monitor records and the alert condition.",
  [Q("Cross-platform metrics come from…",["psutil","os.stat","socket","json"],0,"psutil reads CPU/mem/disk."),
   Q("History is appended to CSV using mode…",["'a'","'w'","'r'","'x'"],0,"'a' appends without truncating."),
   Q("A production monitor should be…",["run once","scheduled + alerting","manual only","disabled"],1,"Schedule it and alert on breaches.")]),
]
by={c["id"]:c for c in man["courses"]}; by["sc-python-scripting"]["lessons"].extend(PY)
MAN.write_text(json.dumps(man,ensure_ascii=False))
print("PY ->",len(by["sc-python-scripting"]["lessons"]),"lessons; track:",sum(len(c["lessons"]) for c in man["courses"]),"lessons,",sum(len(l["quiz"]) for c in man["courses"] for l in c["lessons"]),"quizzes")
