#!/usr/bin/env python3
"""Phase 3c: Help Desk Tier 0/1 practical courses (3 courses / 15 lessons)."""
import json, pathlib
OUT=pathlib.Path('/home/claude/it-academy/scripts/manifests/p33.json'); man={"courses":[]}
def L(i,s,t,mi,x,intro,se,pr,q):return{"id":i,"slug":s,"title":t,"minutes":mi,"xp":x,"content":{"intro":intro,"sections":se,"practice":pr},"quiz":q}
def S(h,p=None,ul=None,note=None,code=None):
    d={"h":h}
    if p:d["p"]=p if isinstance(p,list) else [p]
    if ul:d["ul"]=ul
    if code:d["code"]=code
    if note:d["note"]=note
    return d
def Q(p,o,ci,ex):return{"p":p,"o":o,"ci":ci,"ex":ex}
def RW(t):return{"kind":"info","text":"In the real world: "+t}
def C(area,cid,slug,title,icon,order,mid,mslug,mtitle,desc,lessons):
    return {"area":area,"id":cid,"slug":slug,"title":title,"icon":icon,"order":order,"module_id":mid,
            "module_slug":mslug,"module_title":mtitle,"difficulty":"beginner","description":desc,"lessons":lessons}

essentials=C("hd-essentials","hd-essentials","hd-essentials","Help Desk Essentials","🎧",30,"hd-ess-m1","help-desk-essentials","Help Desk Essentials",
 "The non-technical core of great support: communication, professionalism, documentation, and the ticket process.",[
  L("hd-ess-01","intro-helpdesk","Introduction to Help Desk",16,45,
   "What Tier-1 support really is, and what good looks like on day one.",
   [S("The role",p="Help desk is the first line of IT support: you receive issues, triage them, resolve what you can, and escalate the rest — while keeping users informed."),
    S("Tiers",ul=[{"b":"Tier 0","t":"self-service / KB"},{"b":"Tier 1","t":"first human contact, common fixes"},{"b":"Tier 2/3","t":"deeper/specialist"}]),
    S("What good looks like",note=RW("Employers hire for attitude and communication as much as technical skill — a calm, clear tech who documents well beats a silent genius on the phones.")),],
   "In your own words, describe the difference between Tier 1 and Tier 2.",
   [Q("Tier 1 support is…",["the deepest specialists","the first human contact for common issues","self-service only","management"],1,"Tier 1 handles first-contact common fixes."),
    Q("Issues beyond your scope should be…",["ignored","escalated with notes","closed","deleted"],1,"Escalate with context."),
    Q("Employers value help-desk techs for…",["silence","communication + attitude","typing speed only","hardware only"],1,"Soft skills matter as much as technical.")]),
  L("hd-ess-02","customer-communication","Customer Communication",18,50,
   "How you talk to users determines their experience as much as the fix does.",
   [S("Core habits",ul=["Listen fully, then confirm the problem back","Avoid jargon; explain in the user's terms","Set expectations (what you'll do, how long)"]),
    S("Difficult calls",ul=["Stay calm; acknowledge frustration","Focus on the next action, not blame","Follow up when you promise to"],note=RW("A user whose issue takes a day but who is kept informed is happier than one fixed in an hour with silence — communication is the product.")),
    S("Tone",p="Be warm, concise, and confident. Written tickets: clear subject, plain steps, no jargon.")],
   "Rewrite 'PEBKAC, rebooted, closed' as a professional ticket note.",
   [Q("The first step on any contact is…",["start fixing","listen and confirm the issue","escalate","close it"],1,"Understand before acting."),
    Q("With a frustrated user you should…",["match their anger","acknowledge + focus on next steps","hang up","blame them"],1,"Acknowledge and move to action."),
    Q("Good communication means avoiding…",["empathy","jargon","updates","clarity"],1,"Avoid jargon users don't know.")]),
  L("hd-ess-03","professionalism","Professionalism & Ethics",16,45,
   "Trust is the currency of IT — handle access and data responsibly.",
   [S("Conduct",ul=["Reliability, punctuality, follow-through","Own mistakes; don't hide them","Respect user privacy and data"]),
    S("Access ethics",ul=["Use admin access only for the task at hand","Never snoop; least privilege applies to you too","Follow data-handling policy"],note=RW("Techs have powerful access — the fastest way to lose a job (and references) is misusing it. Professionalism protects users and you.")),
    S("Boundaries",p="Know when to say 'I'll find out' rather than guessing, and when to escalate a security concern.")],
   "Name two ways a tech demonstrates trustworthiness with elevated access.",
   [Q("Elevated access should be used…",["freely","only for the task at hand","for curiosity","to browse files"],1,"Least privilege applies to techs too."),
    Q("When you make a mistake you should…",["hide it","own and fix it","blame a user","ignore it"],1,"Accountability builds trust."),
    Q("User data must be…",["shared","respected/protected","posted","copied"],1,"Protect privacy and follow policy.")]),
  L("hd-ess-04","documentation-kb","Documentation & Knowledge Bases",18,50,
   "Good notes turn one fix into a repeatable solution for the whole team.",
   [S("Ticket documentation",ul=["What was reported, what you found, what you did","Clear enough for the next tech to continue","Timestamps and affected users"]),
    S("Knowledge base",ul=["Write KB articles for recurring issues","Title by symptom users search for","Keep steps current"],note=RW("A well-written KB article you author once can resolve the same issue hundreds of times via self-service — the highest-leverage thing a Tier-1 tech does.")),
    S("Why it matters",p="Documentation shortens future tickets, enables escalation, and proves your work.")],
   "Outline the sections of a good KB article for 'Outlook won't open'.",
   [Q("Good ticket notes let…",["only you continue","the next tech continue","no one continue","managers only"],1,"Anyone should be able to pick it up."),
    Q("KB articles should be titled by…",["internal code","the symptom users search","the tech's name","date"],1,"Match how users describe it."),
    Q("A KB article's leverage is that it…",["is hidden","resolves issues repeatedly","expires fast","is private"],1,"Reused many times via self-service.")]),
  L("hd-ess-05","ticket-lifecycle","Ticket Lifecycle & Prioritization",18,50,
   "How a ticket flows and how to decide what to work first.",
   [S("Lifecycle",ul=["New → Assigned → In Progress → Resolved → Closed","Keep status current; add notes at each step"]),
    S("Priority = impact × urgency",ul=[{"b":"Impact","t":"how many / how critical"},{"b":"Urgency","t":"how time-sensitive"},{"b":"P1","t":"outage; P4: minor request"}],note=RW("A single exec's laptop vs a whole floor's network down — prioritization keeps you working the highest-impact issue instead of first-in-first-out.")),
    S("SLAs",p="Service Level Agreements set response/resolution targets by priority — meet them and communicate.")],
   "Given a company-wide email outage and one user's font issue, assign priorities and justify.",
   [Q("Priority is derived from…",["impact × urgency","ticket age","alphabetical","random"],0,"Impact and urgency set priority."),
    Q("A site-wide outage is typically…",["P4","P1","closed","low"],1,"Broad, urgent = P1."),
    Q("SLAs define…",["response/resolution targets","salaries","hardware","passwords"],0,"Agreed time targets by priority.")]),
 ])

everyday=C("hd-everyday","hd-everyday","hd-everyday","Everyday Support Tasks","🛠️",31,"hd-eve-m1","everyday-support","Everyday Support Tasks",
 "The bread-and-butter tickets a Tier-1 tech resolves daily — accounts, printing, remote access, email, and browsers.",[
  L("hd-eve-01","password-mfa","Password Resets & MFA",16,50,
   "The single most common ticket — done securely.",
   [S("Reset securely",ul=["Verify identity first (never skip)","Reset, require change at next logon","Never send a password over chat/email in the clear"]),
    S("MFA",ul=["Something you know + have/are","Reset/re-enroll MFA when a device is lost","Watch for MFA-fatigue social engineering"],note=RW("Attackers call the help desk pretending to be a user to get a reset — identity verification is your front-line security control, not a formality.")),
    S("Self-service",p="Encourage SSPR (self-service password reset) to cut volume.")],
   "List the identity-verification steps before resetting a password.",
   [Q("Before any reset you must…",["skip verification","verify identity","email the password","reboot"],1,"Always verify identity first."),
    Q("MFA combines…",["two passwords","different factor types","two emails","nothing"],1,"Know + have/are."),
    Q("A reset password should be sent…",["in plain email","never in clear text","via chat","on a sticky note"],1,"Never transmit in clear text.")]),
  L("hd-eve-02","printer-support","Printer Support",16,45,
   "Printing breaks constantly — know the usual suspects.",
   [S("Common fixes",ul=["Offline/queue stuck → restart Print Spooler","Driver issues → reinstall correct driver","Network printer down for all → check printer/IP"]),
    S("Isolate",p="One user vs everyone? A shared outage is printer/network-side, not the PC."),
    S("Consumables",note=RW("Half of 'printer broken' tickets are toner, paper, or a stuck queue — check the simple things before deep troubleshooting.")),],
   "A shared printer is offline for everyone — where do you look first?",
   [Q("A stuck print queue is cleared by…",["reinstalling Windows","restarting Print Spooler","new toner","a reboot only"],1,"Restart the Print Spooler."),
    Q("Offline for everyone points to…",["one PC","the printer/network","a password","the monitor"],1,"Shared outage = printer/network side."),
    Q("Faded output often means…",["low toner","DNS","bad RAM","a virus"],0,"Low toner/consumables.")]),
  L("hd-eve-03","vpn-remote","VPN & Remote Support",18,50,
   "Support remote workers and connect to their machines safely.",
   [S("VPN issues",ul=["Confirm internet first","Creds/MFA, client version, expired cert","Connected but no access → DNS/routing"]),
    S("Remote support tools",ul=["Remote Desktop / remote-control tools","Always get user consent; announce actions","Don't leave sessions open"],note=RW("Test by IP vs name to split 'VPN down' from 'DNS down' — most 'VPN broken' tickets are actually name resolution.")),
    S("Security",p="Remote sessions are powerful — verify identity and follow policy.")],
   "A user's VPN connects but internal sites fail — what do you test?",
   [Q("Before VPN troubleshooting, confirm…",["new laptop","the user has internet","AD reset","Office reinstall"],1,"No internet, no VPN."),
    Q("Connected but names don't resolve →",["bad monitor","DNS/routing","low RAM","dead NIC"],1,"Likely DNS over the tunnel."),
    Q("Remote-control a user's PC only…",["silently","with consent","after hours","never"],1,"Always get consent.")]),
  L("hd-eve-04","email-troubleshooting","Email Troubleshooting",16,50,
   "Diagnose the most common Outlook/mail complaints.",
   [S("Can't send/receive",ul=["Check connectivity + account status","Large mailbox / full quota","Rebuild profile if corrupt"]),
    S("Missing mail",ul=["Check rules, junk/quarantine, and filters","Use message trace (admin) for delivery"],note=RW("A message trace answers 'where did it go?' in seconds — quarantined, rejected, or never arrived — instead of guessing.")),
    S("Mobile mail",p="Verify server settings/ports and that the device accepted policy.")],
   "A user says an external email never arrived — first diagnostic step?",
   [Q("Best first tool for delivery issues…",["reboot Outlook","message trace","new mailbox","reset password"],1,"Message trace shows the path."),
    Q("Missing mail may be caught by…",["rules/junk/quarantine","the CPU","DNS only","the printer"],0,"Check rules, junk, quarantine."),
    Q("A corrupt Outlook profile is fixed by…",["new PC","rebuilding the profile","new license","BIOS reset"],1,"Rebuild the mail profile.")]),
  L("hd-eve-05","browser-troubleshooting","Browser Troubleshooting",14,45,
   "Web-app problems often come down to a few browser basics.",
   [S("Usual fixes",ul=["Clear cache/cookies for the site","Try incognito / another browser to isolate","Check extensions (disable to test)"]),
    S("Deeper",ul=["Certificate/date errors → check system clock","Proxy/DNS issues → test another site","Update the browser"],note=RW("'The website is broken' is often a stale cache or a rogue extension — incognito mode instantly tells you which side the problem is on.")),
    S("Escalate",p="If it fails across browsers and machines, it's likely server-side — escalate.")],
   "A web app fails in Chrome but works in incognito — likely cause?",
   [Q("Incognito working but normal failing suggests…",["server down","cache/extension","dead NIC","bad RAM"],1,"Stale cache or an extension."),
    Q("Certificate/date errors can stem from…",["the system clock","toner","the mouse","DNS only"],0,"A wrong clock breaks TLS validation."),
    Q("Failing across all browsers/machines is likely…",["client-side","server-side","the keyboard","the monitor"],1,"Escalate as server-side.")]),
 ])

tier1=C("hd-tier1-win","hd-tier1-win","hd-tier1-win","Tier 1: Windows & Accounts","🪟",32,"hd-t1-m1","tier1-windows","Tier 1: Windows & Accounts",
 "The Tier-1 Windows toolkit: troubleshooting, drivers, updates, remote desktop, and permissions.",[
  L("hd-t1-01","windows-troubleshooting","Windows Troubleshooting",18,50,
   "A repeatable approach to common Windows problems.",
   [S("Method",ul=["Reproduce, check recent changes, isolate","Safe Mode to rule out drivers/startup","Event Viewer for clues"]),
    S("Common issues",ul=["Slow PC → startup apps, disk, malware","App crash → update/reinstall","Boot issues → Startup Repair"],note=RW("Booting into Safe Mode first tells you instantly whether it's a driver/startup problem or something deeper — it saves hours of guessing.")),
    S("Tools",p="Task Manager, Resource Monitor, Reliability History, Event Viewer.")],
   "List three first checks for a 'slow computer' ticket.",
   [Q("Minimal-driver diagnostic boot is…",["Safe Mode","Fast Boot","UEFI","BIOS"],0,"Safe Mode loads minimal drivers."),
    Q("First checks for a slow PC…",["buy new PC","startup apps/disk/malware","repaint","new monitor"],1,"Startup load, disk/RAM, malware."),
    Q("Clues to app errors live in…",["Event Viewer","Paint","the BIOS","the router"],0,"Event Viewer logs errors.")]),
  L("hd-t1-02","device-manager-drivers","Device Manager & Drivers",16,50,
   "Diagnose hardware and driver issues the Tier-1 way.",
   [S("Device Manager",ul=["Yellow ! = driver/hardware problem","Update/rollback/reinstall drivers","Show hidden devices for ghosts"]),
    S("Drivers",ul=["Get drivers from the vendor/OEM","Roll back a bad driver update","Match the exact model"],note=RW("A device that worked yesterday and fails after an update is almost always a driver — roll it back before deeper troubleshooting.")),
    S("Isolate",p="Test the device on another PC / another port to split device vs machine.")],
   "A webcam stopped working after updates — what's your first move?",
   [Q("A yellow ! in Device Manager means…",["healthy","a driver/hardware problem","low disk","a virus"],1,"It flags a device problem."),
    Q("A device broken right after an update →",["new PC","roll back the driver","reinstall Windows","replace RAM"],1,"Roll back the driver."),
    Q("Drivers should come from…",["random sites","the vendor/OEM","email","a USB found in the lot"],1,"Use vendor/OEM drivers.")]),
  L("hd-t1-03","windows-updates","Windows Updates",14,45,
   "Keep systems patched and fix update failures.",
   [S("Why patch",p="Updates close security holes and fix bugs — a core security control."),
    S("Update failures",ul=["Check disk space + connectivity","Run the Update troubleshooter","Reset Windows Update components if stuck"],note=RW("Unpatched machines are the top target for malware — 'we'll update later' is how ransomware gets in.")),
    S("Control",p="In business, updates are often managed (WSUS/Intune) — know it's centralized.")],
   "An update keeps failing at install — list two things to check.",
   [Q("Updates primarily provide…",["wallpaper","security + bug fixes","more RAM","new hardware"],1,"Security patches and fixes."),
    Q("A stuck update may need…",["a new CPU","resetting Update components","a new mouse","BIOS reset"],1,"Reset Windows Update components."),
    Q("Unpatched systems are…",["safest","the top malware target","fastest","fine"],1,"Prime targets for attackers.")]),
  L("hd-t1-04","remote-desktop","Remote Desktop & Access",14,45,
   "Connect to machines remotely to support and administer.",
   [S("RDP basics",ul=["Enable Remote Desktop; it uses port 3389","Requires permission + network reachability","Only expose over VPN, never open to the internet"]),
    S("Alternatives",ul=["Remote-assist tools for user consent sessions","SSH for Linux hosts"],note=RW("Exposing RDP (3389) directly to the internet is a classic breach vector — always tunnel it through a VPN.")),
    S("Troubleshoot",p="Can't connect? Check the service, firewall, IP/name, and permissions.")],
   "Why should RDP never be exposed directly to the internet?",
   [Q("RDP uses port…",["22","3389","443","80"],1,"RDP is TCP 3389."),
    Q("RDP should be reached…",["over the open internet","through a VPN","via email","via USB"],1,"Tunnel it through a VPN."),
    Q("Remote-assist sessions require…",["nothing","user consent","a reboot","admin only"],1,"Get user consent.")]),
  L("hd-t1-05","permissions-shares","Permissions & File Shares",18,55,
   "Resolve the access tickets that fill a Tier-1 queue.",
   [S("NTFS vs Share",ul=["NTFS: granular, local + network","Share: network only","Most restrictive of the two wins"]),
    S("Groups",ul=["Assign access via groups, not individuals","'Access denied' → check group membership","Least privilege"],note=RW("The fastest fix for most access tickets is adding the user to the right security group — resist granting one-off permissions that no one can audit later.")),
    S("Inheritance",p="Broken inheritance causes surprise denials — check the folder's effective permissions.")],
   "When Share and NTFS permissions differ, which applies?",
   [Q("Combined Share + NTFS yields the…",["most permissive","most restrictive","share only","NTFS only"],1,"The most restrictive wins."),
    Q("Access is best granted via…",["individual users","security groups","email","the registry"],1,"Groups scale and audit better."),
    Q("Surprise denials often come from…",["broken inheritance","the monitor","toner","DNS"],0,"Broken permission inheritance.")]),
 ])

for c in (essentials, everyday, tier1): man["courses"].append(c)
OUT.write_text(json.dumps(man, ensure_ascii=False))
print("p33:", len(man["courses"]), "courses,", sum(len(c["lessons"]) for c in man["courses"]), "lessons,", sum(len(l["quiz"]) for c in man["courses"] for l in c["lessons"]), "quizzes")
