-- 0012_seed_quizzes_sysadmin_wsl.sql — Phase 13 (SysAdmin fill-out, done early):
-- quizzes for Windows Server 2025 (12) + Linux (10) courses. Idempotent.

insert into public.lesson_quizzes (lesson_id, pass_pct, bonus_xp) values
  ('windows-server-2025-01', 70, 30),
  ('windows-server-2025-02', 70, 30),
  ('windows-server-2025-03', 70, 30),
  ('windows-server-2025-04', 70, 30),
  ('windows-server-2025-05', 70, 30),
  ('windows-server-2025-06', 70, 30),
  ('windows-server-2025-07', 70, 30),
  ('windows-server-2025-08', 70, 30),
  ('windows-server-2025-09', 70, 30),
  ('windows-server-2025-10', 70, 30),
  ('windows-server-2025-11', 70, 30),
  ('windows-server-2025-12', 70, 30),
  ('linux-01', 70, 30),
  ('linux-02', 70, 30),
  ('linux-03', 70, 30),
  ('linux-04', 70, 30),
  ('linux-05', 70, 30),
  ('linux-06', 70, 30),
  ('linux-07', 70, 30),
  ('linux-08', 70, 30),
  ('linux-09', 70, 30),
  ('linux-10', 70, 30)
on conflict (lesson_id) do update set pass_pct=excluded.pass_pct, bonus_xp=excluded.bonus_xp;

delete from public.quiz_questions where lesson_id in ('windows-server-2025-01', 'windows-server-2025-02', 'windows-server-2025-03', 'windows-server-2025-04', 'windows-server-2025-05', 'windows-server-2025-06', 'windows-server-2025-07', 'windows-server-2025-08', 'windows-server-2025-09', 'windows-server-2025-10', 'windows-server-2025-11', 'windows-server-2025-12', 'linux-01', 'linux-02', 'linux-03', 'linux-04', 'linux-05', 'linux-06', 'linux-07', 'linux-08', 'linux-09', 'linux-10');

insert into public.quiz_questions (lesson_id, sort, prompt, options, correct_index, explanation) values
  ('windows-server-2025-01', 1, 'Server Core differs from Desktop Experience mainly because it…', '["Has no networking", "Runs without the full GUI, reducing attack surface and overhead", "Can''t join a domain", "Is only for printing"]'::jsonb, 1, 'Server Core omits the GUI for a smaller, more secure footprint.'),
  ('windows-server-2025-01', 2, 'A ''role'' in Windows Server is…', '["A user account", "A major function the server provides (e.g. AD DS, DNS, DHCP)", "A registry key", "A backup type"]'::jsonb, 1, 'Roles are the primary services a server hosts.'),
  ('windows-server-2025-01', 3, 'Which tool installs roles and features?', '["Server Manager / PowerShell (Install-WindowsFeature)", "Notepad", "Disk Cleanup", "Paint"]'::jsonb, 0, 'Server Manager or Install-WindowsFeature add roles/features.'),
  ('windows-server-2025-02', 1, 'A domain controller…', '["Only stores files", "Hosts AD DS and authenticates domain users", "Is a printer", "Is a backup disk"]'::jsonb, 1, 'DCs run AD DS and handle authentication/authorisation.'),
  ('windows-server-2025-02', 2, 'Organisational Units (OUs) are used to…', '["Store passwords in plain text", "Organise objects and apply Group Policy", "Replace DNS", "Hold backups"]'::jsonb, 1, 'OUs structure the directory and are GPO link points.'),
  ('windows-server-2025-02', 3, 'A security group''s main purpose is to…', '["Slow logins", "Grant access to resources collectively", "Encrypt the disk", "Run updates"]'::jsonb, 1, 'Groups grant access to many users at once.'),
  ('windows-server-2025-03', 1, 'A DHCP scope defines…', '["DNS names", "The range of IP addresses the server can lease", "Firewall rules", "User passwords"]'::jsonb, 1, 'A scope is the pool of leasable addresses.'),
  ('windows-server-2025-03', 2, 'A DHCP reservation ensures a device…', '["Never connects", "Always gets the same IP based on its MAC", "Has no IP", "Bypasses DNS"]'::jsonb, 1, 'Reservations bind an IP to a MAC address.'),
  ('windows-server-2025-03', 3, 'The DHCP lease process is often abbreviated…', '["DORA (Discover, Offer, Request, Acknowledge)", "HTTP", "TCP/IP", "RAID"]'::jsonb, 0, 'DORA = Discover, Offer, Request, Acknowledge.'),
  ('windows-server-2025-04', 1, 'A DNS A record maps…', '["A name to an IPv4 address", "An IP to a MAC", "A user to a group", "A port to a service"]'::jsonb, 0, 'An A record resolves a hostname to an IPv4 address.'),
  ('windows-server-2025-04', 2, 'A reverse lookup zone resolves…', '["Names to names", "IP addresses back to names", "Passwords", "Ports"]'::jsonb, 1, 'Reverse zones map IPs to hostnames (PTR records).'),
  ('windows-server-2025-04', 3, 'A DNS forwarder is used to…', '["Block DNS", "Send unresolved queries to another DNS server", "Store files", "Assign IPs"]'::jsonb, 1, 'Forwarders pass queries the server can''t answer upstream.'),
  ('windows-server-2025-05', 1, 'A GPO (Group Policy Object) is applied by linking it to…', '["A printer", "A site, domain, or OU", "A single file", "The BIOS"]'::jsonb, 1, 'GPOs link to sites, domains, or OUs.'),
  ('windows-server-2025-05', 2, 'Which command forces a Group Policy refresh?', '["gpupdate /force", "ipconfig /all", "chkdsk", "format c:"]'::jsonb, 0, 'gpupdate /force reapplies policy immediately.'),
  ('windows-server-2025-05', 3, 'Default GPO processing order is…', '["Random", "Local, Site, Domain, OU (LSDOU)", "OU only", "Domain only"]'::jsonb, 1, 'Local → Site → Domain → OU; later wins on conflict.'),
  ('windows-server-2025-06', 1, 'Hyper-V is a…', '["Type 1 (bare-metal) hypervisor", "Word processor", "Backup tool", "Firewall"]'::jsonb, 0, 'Hyper-V is a type 1 hypervisor.'),
  ('windows-server-2025-06', 2, 'A Hyper-V virtual switch provides VMs with…', '["Storage", "Network connectivity", "Extra CPUs", "A GUI"]'::jsonb, 1, 'Virtual switches connect VMs to networks.'),
  ('windows-server-2025-06', 3, 'A checkpoint (snapshot) lets you…', '["Delete a VM", "Capture and revert a VM''s state", "Add RAM", "Install Windows"]'::jsonb, 1, 'Checkpoints capture state you can roll back to.'),
  ('windows-server-2025-07', 1, 'DFS Namespaces let you…', '["Encrypt disks", "Present multiple shares under one logical path", "Assign IPs", "Run backups"]'::jsonb, 1, 'DFS-N unifies shares behind a single namespace.'),
  ('windows-server-2025-07', 2, 'When share and NTFS permissions combine over the network, the result is…', '["The most permissive", "The most restrictive of the two", "Always full control", "NTFS ignored"]'::jsonb, 1, 'The effective permission is the most restrictive.'),
  ('windows-server-2025-07', 3, 'Storage quotas are used to…', '["Speed up disks", "Limit how much space users/folders can consume", "Encrypt files", "Assign IPs"]'::jsonb, 1, 'Quotas cap consumption per user or folder.'),
  ('windows-server-2025-08', 1, 'Windows Defender Firewall filters traffic by…', '["File size", "Inbound and outbound rules", "User mood", "Disk type"]'::jsonb, 1, 'Rules govern inbound/outbound traffic.'),
  ('windows-server-2025-08', 2, 'Firewall profiles (Domain/Private/Public) exist to…', '["Confuse admins", "Apply different rules based on the network type", "Disable the firewall", "Store passwords"]'::jsonb, 1, 'Profiles tailor rules to the connected network type.'),
  ('windows-server-2025-08', 3, 'A common least-privilege firewall stance is…', '["Allow everything", "Default-deny inbound, allow only what''s needed", "Block all outbound only", "No rules"]'::jsonb, 1, 'Default-deny inbound with explicit allows is the norm.'),
  ('windows-server-2025-09', 1, 'Remote Desktop Services (RDS) lets users…', '["Print only", "Run sessions/apps hosted on a server", "Encrypt disks", "Assign IPs"]'::jsonb, 1, 'RDS delivers server-hosted desktops and apps.'),
  ('windows-server-2025-09', 2, 'RemoteApp publishes…', '["Whole desktops only", "Individual applications that appear local", "Firewall rules", "DNS zones"]'::jsonb, 1, 'RemoteApp streams individual apps to users.'),
  ('windows-server-2025-09', 3, 'RDS legally requires…', '["Nothing", "RDS CALs (client access licenses)", "A new domain", "A printer"]'::jsonb, 1, 'RDS needs CALs licensed appropriately.'),
  ('windows-server-2025-10', 1, 'A core backup principle is the…', '["3-2-1 rule (3 copies, 2 media, 1 offsite)", "RGB rule", "9-to-5 rule", "RAID-0 rule"]'::jsonb, 0, '3-2-1: three copies, two media types, one offsite.'),
  ('windows-server-2025-10', 2, 'Bare-metal recovery restores…', '["A single file", "An entire system to new/blank hardware", "Only the registry", "Just email"]'::jsonb, 1, 'BMR rebuilds the full system onto bare hardware.'),
  ('windows-server-2025-10', 3, 'Backups should be…', '["Never tested", "Regularly tested by restoring", "Stored only on the same server", "Deleted weekly"]'::jsonb, 1, 'Untested backups aren''t trustworthy — test restores.'),
  ('windows-server-2025-11', 1, 'Windows Admin Center is…', '["A browser-based server management tool", "A game", "A backup tape", "A firewall appliance"]'::jsonb, 0, 'WAC is a modern, browser-based management console.'),
  ('windows-server-2025-11', 2, 'WAC is useful because it…', '["Requires a GUI on every server", "Manages multiple servers (incl. Server Core) from one place", "Only manages printers", "Replaces Windows"]'::jsonb, 1, 'WAC centralises management, including Core servers.'),
  ('windows-server-2025-11', 3, 'WAC connects to servers primarily over…', '["Email", "Secure remote protocols (WinRM/PowerShell)", "USB", "Bluetooth"]'::jsonb, 1, 'WAC uses WinRM/PowerShell under the hood.'),
  ('windows-server-2025-12', 1, 'A key hardening step is to…', '["Install every role", "Remove/disable unused roles and features", "Disable logging", "Share admin passwords"]'::jsonb, 1, 'Reduce attack surface by removing what you don''t need.'),
  ('windows-server-2025-12', 2, 'Patching matters because…', '["It changes the theme", "It closes known security vulnerabilities", "It frees RAM", "It speeds typing"]'::jsonb, 1, 'Updates remediate known vulnerabilities.'),
  ('windows-server-2025-12', 3, 'Administrative access should follow…', '["Most privilege for all", "Least privilege / just-enough-admin", "Shared accounts", "No accounts"]'::jsonb, 1, 'Least privilege limits damage from error or compromise.'),
  ('linux-01', 1, 'In the Linux filesystem hierarchy, system-wide config files live in…', '["/home", "/etc", "/proc", "/dev"]'::jsonb, 1, '/etc holds system configuration.'),
  ('linux-01', 2, 'The top of the Linux directory tree is…', '["C:\\", "/ (root)", "~", "/boot"]'::jsonb, 1, 'Everything hangs off / (root).'),
  ('linux-01', 3, 'Variable data like logs typically lives in…', '["/var", "/bin", "/usr/include", "/root"]'::jsonb, 0, '/var holds variable data such as logs and spools.'),
  ('linux-02', 1, 'Which command prints the current directory?', '["pwd", "cd", "ls", "rm"]'::jsonb, 0, 'pwd = print working directory.'),
  ('linux-02', 2, 'The pipe symbol | is used to…', '["Delete files", "Send one command''s output into another", "Reboot", "Change passwords"]'::jsonb, 1, 'Pipes chain commands together.'),
  ('linux-02', 3, 'Which lists directory contents?', '["ls", "cat", "touch", "kill"]'::jsonb, 0, 'ls lists files and directories.'),
  ('linux-03', 1, 'In rwx permissions, the ''x'' means…', '["Delete", "Execute (or enter a directory)", "Encrypt", "Extend"]'::jsonb, 1, 'x is execute / directory traversal.'),
  ('linux-03', 2, 'Which command changes a file''s owner?', '["chown", "chmod", "chgrp only", "passwd"]'::jsonb, 0, 'chown changes ownership.'),
  ('linux-03', 3, 'chmod 750 grants the owner…', '["No access", "Read, write, execute", "Execute only", "Write only"]'::jsonb, 1, '7 = rwx for the owner.'),
  ('linux-04', 1, 'On Debian/Ubuntu, packages are managed with…', '["apt", "yum only", "brew", "choco"]'::jsonb, 0, 'apt is the Debian/Ubuntu package manager.'),
  ('linux-04', 2, 'On RHEL/Fedora, the modern package manager is…', '["dnf", "apt", "pacman", "zypper"]'::jsonb, 0, 'dnf manages packages on RHEL/Fedora.'),
  ('linux-04', 3, 'A software repository is…', '["A backup", "A source of installable packages", "A firewall", "A user group"]'::jsonb, 1, 'Repos are curated package sources.'),
  ('linux-05', 1, 'systemd manages…', '["Only files", "Services (units), boot, and dependencies", "Only networking", "Only users"]'::jsonb, 1, 'systemd is the init/service manager.'),
  ('linux-05', 2, 'Which starts a service now?', '["systemctl start <svc>", "systemctl enable <svc>", "service off", "kill -9"]'::jsonb, 0, 'start runs it immediately.'),
  ('linux-05', 3, '''systemctl enable'' does what?', '["Starts it once", "Sets it to start automatically at boot", "Deletes it", "Stops it"]'::jsonb, 1, 'enable sets a service to auto-start on boot.'),
  ('linux-06', 1, 'Which shows a Linux host''s IP addresses?', '["ip addr (or ip a)", "dir", "gpupdate", "format"]'::jsonb, 0, 'ip addr shows interface addresses.'),
  ('linux-06', 2, 'DNS resolver settings traditionally live in…', '["/etc/resolv.conf", "/etc/passwd", "/boot", "/var/log"]'::jsonb, 0, '/etc/resolv.conf holds resolver config.'),
  ('linux-06', 3, 'A ''port'' identifies…', '["A user", "A specific network service/endpoint on a host", "A disk", "A printer"]'::jsonb, 1, 'Ports map to services (e.g. 22 = SSH).'),
  ('linux-07', 1, 'SSH''s default port is…', '["22", "80", "443", "21"]'::jsonb, 0, 'SSH listens on TCP 22 by default.'),
  ('linux-07', 2, 'The most secure SSH authentication uses…', '["A blank password", "Public/private key pairs", "Only a username", "Telnet"]'::jsonb, 1, 'Key-based auth is stronger than passwords.'),
  ('linux-07', 3, 'The SSH server daemon is…', '["sshd", "httpd", "ftpd", "cron"]'::jsonb, 0, 'sshd is the SSH server daemon.'),
  ('linux-08', 1, 'ufw is…', '["A text editor", "An uncomplicated firewall front-end for iptables/nftables", "A package manager", "A shell"]'::jsonb, 1, 'ufw simplifies host firewall management.'),
  ('linux-08', 2, 'A secure default firewall policy is…', '["Allow all inbound", "Default-deny inbound, allow only needed ports", "Disable the firewall", "Block outbound only"]'::jsonb, 1, 'Default-deny inbound with explicit allows.'),
  ('linux-08', 3, 'iptables/nftables operate on…', '["Files", "Network packets via rules/chains", "Users", "Disks"]'::jsonb, 1, 'They filter packets using rules and chains.'),
  ('linux-09', 1, 'LVM provides…', '["Antivirus", "Flexible logical volumes you can resize", "A firewall", "A shell"]'::jsonb, 1, 'LVM abstracts storage into resizable logical volumes.'),
  ('linux-09', 2, 'Persistent mounts at boot are defined in…', '["/etc/fstab", "/etc/hosts", "/var/log", "/boot/grub only"]'::jsonb, 0, '/etc/fstab lists filesystems to mount at boot.'),
  ('linux-09', 3, 'The command to attach a filesystem is…', '["mount", "ping", "ssh", "chmod"]'::jsonb, 0, 'mount attaches a filesystem to a directory.'),
  ('linux-10', 1, 'A common Linux hardening step is to…', '["Permit root SSH login", "Disable direct root SSH login and use sudo", "Open all ports", "Share passwords"]'::jsonb, 1, 'Disable root SSH; use a normal account with sudo.'),
  ('linux-10', 2, 'Keeping a server secure requires…', '["Never updating", "Applying security updates regularly", "Disabling logs", "One shared account"]'::jsonb, 1, 'Regular patching closes known vulnerabilities.'),
  ('linux-10', 3, 'The principle to follow for access is…', '["Most privilege", "Least privilege", "No authentication", "Shared root"]'::jsonb, 1, 'Grant the minimum access required.');
