-- 0013_seed_quizzes_sysadmin_rest.sql — SysAdmin quiz fill-out (final 6 courses):
-- unix, networking, powershell, python, cybersecurity, troubleshooting. Idempotent.

insert into public.lesson_quizzes (lesson_id, pass_pct, bonus_xp) values
  ('unix-01', 70, 30),
  ('unix-02', 70, 30),
  ('unix-03', 70, 30),
  ('unix-04', 70, 30),
  ('unix-05', 70, 30),
  ('networking-01', 70, 30),
  ('networking-02', 70, 30),
  ('networking-03', 70, 30),
  ('networking-04', 70, 30),
  ('networking-05', 70, 30),
  ('networking-06', 70, 30),
  ('networking-07', 70, 30),
  ('powershell-01', 70, 30),
  ('powershell-02', 70, 30),
  ('powershell-03', 70, 30),
  ('powershell-04', 70, 30),
  ('powershell-05', 70, 30),
  ('powershell-06', 70, 30),
  ('powershell-07', 70, 30),
  ('powershell-08', 70, 30),
  ('python-01', 70, 30),
  ('python-02', 70, 30),
  ('python-03', 70, 30),
  ('python-04', 70, 30),
  ('python-05', 70, 30),
  ('python-06', 70, 30),
  ('python-07', 70, 30),
  ('python-08', 70, 30),
  ('python-09', 70, 30),
  ('cybersecurity-01', 70, 30),
  ('cybersecurity-02', 70, 30),
  ('cybersecurity-03', 70, 30),
  ('cybersecurity-04', 70, 30),
  ('cybersecurity-05', 70, 30),
  ('cybersecurity-06', 70, 30),
  ('cybersecurity-07', 70, 30),
  ('cybersecurity-08', 70, 30),
  ('cybersecurity-09', 70, 30),
  ('cybersecurity-10', 70, 30),
  ('troubleshooting-01', 70, 30),
  ('troubleshooting-02', 70, 30),
  ('troubleshooting-03', 70, 30),
  ('troubleshooting-04', 70, 30),
  ('troubleshooting-05', 70, 30),
  ('troubleshooting-06', 70, 30)
on conflict (lesson_id) do update set pass_pct=excluded.pass_pct, bonus_xp=excluded.bonus_xp;

delete from public.quiz_questions where lesson_id in ('unix-01', 'unix-02', 'unix-03', 'unix-04', 'unix-05', 'networking-01', 'networking-02', 'networking-03', 'networking-04', 'networking-05', 'networking-06', 'networking-07', 'powershell-01', 'powershell-02', 'powershell-03', 'powershell-04', 'powershell-05', 'powershell-06', 'powershell-07', 'powershell-08', 'python-01', 'python-02', 'python-03', 'python-04', 'python-05', 'python-06', 'python-07', 'python-08', 'python-09', 'cybersecurity-01', 'cybersecurity-02', 'cybersecurity-03', 'cybersecurity-04', 'cybersecurity-05', 'cybersecurity-06', 'cybersecurity-07', 'cybersecurity-08', 'cybersecurity-09', 'cybersecurity-10', 'troubleshooting-01', 'troubleshooting-02', 'troubleshooting-03', 'troubleshooting-04', 'troubleshooting-05', 'troubleshooting-06');

insert into public.quiz_questions (lesson_id, sort, prompt, options, correct_index, explanation) values
  ('unix-01', 1, 'A central tenet of the Unix philosophy is to…', '["Build one giant program", "Write small tools that do one thing well and compose them", "Avoid the command line", "Never use text"]'::jsonb, 1, 'Small, composable, single-purpose tools.'),
  ('unix-01', 2, 'In Unix, ''everything is a…''', '["file", "printer", "window", "registry key"]'::jsonb, 0, 'Devices, pipes, and more are exposed as files.'),
  ('unix-01', 3, 'Composability is achieved largely through…', '["the registry", "pipes and plain-text streams", "GUIs", "email"]'::jsonb, 1, 'Text streams piped between tools.'),
  ('unix-02', 1, 'A POSIX shell script usually starts with…', '["a shebang line like #!/bin/sh", "<html>", "// comment", "import os"]'::jsonb, 0, 'The shebang selects the interpreter.'),
  ('unix-02', 2, 'Which captures command output into a variable?', '["x=$(command)", "x == command", "print(command)", "command > x only"]'::jsonb, 0, 'Command substitution $( ) captures output.'),
  ('unix-02', 3, 'An exit status of 0 conventionally means…', '["failure", "success", "unknown", "timeout"]'::jsonb, 1, '0 = success; non-zero = error.'),
  ('unix-03', 1, 'FreeBSD, OpenBSD and NetBSD are examples of…', '["Windows editions", "BSD Unix systems", "Linux distros", "hypervisors"]'::jsonb, 1, 'They are BSD-derived Unix systems.'),
  ('unix-03', 2, 'OpenBSD is particularly known for…', '["gaming", "a strong security focus", "spreadsheets", "printing"]'::jsonb, 1, 'OpenBSD emphasises security and code correctness.'),
  ('unix-03', 3, 'BSD systems are licensed under…', '["GPL only", "the permissive BSD license", "a closed EULA", "no license"]'::jsonb, 1, 'The BSD license is permissive.'),
  ('unix-04', 1, 'An ACL extends standard Unix permissions by…', '["removing all access", "allowing per-user/per-group entries beyond owner/group/other", "encrypting files", "hiding files"]'::jsonb, 1, 'ACLs grant finer-grained access than ugo.'),
  ('unix-04', 2, 'The setuid bit causes a program to run with…', '["no permissions", "the file owner''s privileges", "guest only", "root removed"]'::jsonb, 1, 'setuid runs with the owner''s rights.'),
  ('unix-04', 3, 'Which sets read/write/execute for owner only (octal)?', '["700", "777", "644", "000"]'::jsonb, 0, '700 = rwx for owner, nothing for others.'),
  ('unix-05', 1, 'Sending SIGTERM to a process asks it to…', '["start", "terminate gracefully", "sleep forever", "fork"]'::jsonb, 1, 'SIGTERM requests a clean shutdown.'),
  ('unix-05', 2, 'SIGKILL (-9) differs because it…', '["can be ignored", "cannot be caught and forcibly kills", "restarts the process", "pauses it"]'::jsonb, 1, 'SIGKILL is unconditional and uncatchable.'),
  ('unix-05', 3, 'Which lists running processes?', '["ps (or top)", "ls", "cd", "cat"]'::jsonb, 0, 'ps/top show process information.'),
  ('networking-01', 1, 'How many layers does the OSI model have?', '["7", "4", "5", "3"]'::jsonb, 0, 'OSI has 7 layers.'),
  ('networking-01', 2, 'Routing and IP addressing happen at the OSI…', '["Physical layer", "Network layer (3)", "Application layer", "Session layer"]'::jsonb, 1, 'Layer 3 is the Network layer.'),
  ('networking-01', 3, 'MAC addresses operate at the…', '["Data Link layer (2)", "Transport layer", "Application layer", "Network layer"]'::jsonb, 0, 'MAC is a layer-2 (Data Link) concept.'),
  ('networking-02', 1, 'TCP is best described as…', '["connectionless", "connection-oriented and reliable", "unroutable", "a cable type"]'::jsonb, 1, 'TCP provides reliable, ordered delivery.'),
  ('networking-02', 2, 'UDP is preferred when you need…', '["guaranteed delivery", "low overhead/speed over reliability", "encryption", "routing"]'::jsonb, 1, 'UDP trades reliability for speed/low overhead.'),
  ('networking-02', 3, 'An IPv4 address is how many bits?', '["32", "64", "128", "16"]'::jsonb, 0, 'IPv4 = 32 bits.'),
  ('networking-03', 1, 'A /24 network provides how many usable host addresses?', '["254", "256", "510", "64"]'::jsonb, 0, '256 minus network+broadcast = 254 usable.'),
  ('networking-03', 2, 'CIDR notation /26 means the subnet mask is…', '["255.255.255.192", "255.255.255.0", "255.255.0.0", "255.255.255.255"]'::jsonb, 0, '/26 = 255.255.255.192.'),
  ('networking-03', 3, 'Subnetting is used to…', '["slow networks", "divide a network into smaller segments", "remove IPs", "disable routing"]'::jsonb, 1, 'Subnets segment a larger network.'),
  ('networking-04', 1, 'A VLAN primarily provides…', '["faster cables", "logical network segmentation on shared switches", "more storage", "encryption"]'::jsonb, 1, 'VLANs segment traffic logically.'),
  ('networking-04', 2, 'A trunk port carries…', '["one VLAN", "traffic for multiple VLANs (tagged)", "no traffic", "only management"]'::jsonb, 1, 'Trunks carry multiple tagged VLANs.'),
  ('networking-04', 3, 'Switches forward frames using…', '["IP addresses", "MAC address tables", "DNS", "ports only"]'::jsonb, 1, 'Switches learn and use MAC tables.'),
  ('networking-05', 1, 'A router''s job is to…', '["broadcast everything", "forward packets between different networks", "store files", "assign passwords"]'::jsonb, 1, 'Routers move packets between networks.'),
  ('networking-05', 2, 'A default route (0.0.0.0/0) is used when…', '["a packet matches no specific route", "always", "never", "for DNS only"]'::jsonb, 0, 'The default route is the catch-all next hop.'),
  ('networking-05', 3, 'Dynamic routing protocols (e.g. OSPF) exist to…', '["manually set routes", "automatically learn and share routes", "block traffic", "assign IPs"]'::jsonb, 1, 'They learn/advertise routes automatically.'),
  ('networking-06', 1, 'A DNS record that aliases one name to another is a…', '["CNAME", "A", "MX", "PTR"]'::jsonb, 0, 'CNAME is an alias to another name.'),
  ('networking-06', 2, 'Mail delivery for a domain is directed by which record?', '["MX", "A", "TXT", "NS"]'::jsonb, 0, 'MX records route mail.'),
  ('networking-06', 3, 'TTL on a DNS record controls…', '["security", "how long resolvers cache it", "the IP version", "the port"]'::jsonb, 1, 'TTL sets cache lifetime.'),
  ('networking-07', 1, 'The 5 GHz band vs 2.4 GHz generally offers…', '["longer range, slower", "shorter range, higher speed/less congestion", "no difference", "more interference"]'::jsonb, 1, '5 GHz: faster, shorter range, less crowded.'),
  ('networking-07', 2, 'WPA2/WPA3 provide Wi-Fi…', '["faster cables", "encryption and authentication", "more channels", "DNS"]'::jsonb, 1, 'They secure wireless access.'),
  ('networking-07', 3, 'An SSID is…', '["a password", "the wireless network name", "an IP address", "a MAC"]'::jsonb, 1, 'SSID is the network''s name.'),
  ('powershell-01', 1, 'PowerShell cmdlets follow which naming convention?', '["Verb-Noun (e.g. Get-Service)", "Noun.Verb", "all lowercase", "random"]'::jsonb, 0, 'Cmdlets use Verb-Noun.'),
  ('powershell-01', 2, 'Which retrieves help for a cmdlet?', '["Get-Help", "Show-Cmd", "man only", "Help.exe"]'::jsonb, 0, 'Get-Help documents cmdlets.'),
  ('powershell-01', 3, 'PowerShell passes what down the pipeline?', '["plain text", "objects", "bytes only", "files"]'::jsonb, 1, 'PowerShell pipelines pass objects.'),
  ('powershell-02', 1, 'Get-Process | Where-Object {$_.CPU -gt 100} filters by…', '["name", "a property condition (CPU > 100)", "date", "nothing"]'::jsonb, 1, 'Where-Object filters on object properties.'),
  ('powershell-02', 2, 'Select-Object is used to…', '["delete objects", "choose specific properties", "stop scripts", "format disks"]'::jsonb, 1, 'Select-Object picks properties/columns.'),
  ('powershell-02', 3, '$_ in the pipeline refers to…', '["the script", "the current pipeline object", "the user", "the host"]'::jsonb, 1, '$_ is the current object.'),
  ('powershell-03', 1, 'A reusable named block of PowerShell code is a…', '["function", "label", "comment", "variable"]'::jsonb, 0, 'Functions encapsulate reusable code.'),
  ('powershell-03', 2, 'PowerShell modules are used to…', '["slow scripts", "package and share related functions/cmdlets", "delete files", "format text"]'::jsonb, 1, 'Modules bundle and distribute functionality.'),
  ('powershell-03', 3, 'Execution Policy controls…', '["CPU usage", "whether/which scripts may run", "disk space", "colours"]'::jsonb, 1, 'It governs script execution permissions.'),
  ('powershell-04', 1, 'Which module provides AD cmdlets like Get-ADUser?', '["ActiveDirectory", "Hyper-V", "NetTCPIP", "Storage"]'::jsonb, 0, 'The ActiveDirectory module.'),
  ('powershell-04', 2, 'Get-ADUser -Filter * primarily…', '["deletes users", "retrieves user objects", "resets passwords", "creates OUs"]'::jsonb, 1, 'It queries user objects.'),
  ('powershell-04', 3, 'Bulk-creating users from a CSV typically uses…', '["Import-Csv piped to New-ADUser", "Format-Table", "Stop-Process", "Get-Help"]'::jsonb, 0, 'Import-Csv | New-ADUser.'),
  ('powershell-05', 1, 'PSRemoting lets you…', '["edit the registry locally only", "run commands on remote machines", "print", "compile code"]'::jsonb, 1, 'It executes commands remotely.'),
  ('powershell-05', 2, 'Which runs a scriptblock on a remote host?', '["Invoke-Command", "Get-Date", "Write-Host", "Sort-Object"]'::jsonb, 0, 'Invoke-Command targets remote sessions.'),
  ('powershell-05', 3, 'PSRemoting relies on which protocol by default?', '["WinRM", "FTP", "SMTP", "Telnet"]'::jsonb, 0, 'WinRM underpins PSRemoting.'),
  ('powershell-06', 1, 'Which lists files in a path?', '["Get-ChildItem", "Get-Service", "Stop-Process", "Get-Help"]'::jsonb, 0, 'Get-ChildItem enumerates items.'),
  ('powershell-06', 2, 'The registry is accessible in PowerShell as…', '["a drive (e.g. HKLM:)", "email", "a VLAN", "a printer"]'::jsonb, 0, 'Registry hives are PSDrives like HKLM:.'),
  ('powershell-06', 3, 'Test-Path is used to…', '["run a script", "check whether a path exists", "delete a file", "format a disk"]'::jsonb, 1, 'Test-Path verifies existence.'),
  ('powershell-07', 1, 'Desired State Configuration (DSC) ensures a system…', '["stays random", "matches a declared desired state", "never updates", "has no config"]'::jsonb, 1, 'DSC enforces a declarative target state.'),
  ('powershell-07', 2, 'DSC configurations are written…', '["as binaries", "declaratively", "in assembly", "in CSV"]'::jsonb, 1, 'DSC is declarative.'),
  ('powershell-07', 3, 'DSC helps prevent…', '["backups", "configuration drift", "logging", "networking"]'::jsonb, 1, 'It corrects drift from the desired state.'),
  ('powershell-08', 1, 'Exporting results to CSV uses…', '["Export-Csv", "Format-List", "Write-Host", "Get-Help"]'::jsonb, 0, 'Export-Csv writes CSV output.'),
  ('powershell-08', 2, 'Scheduling a recurring PowerShell job often uses…', '["Task Scheduler / scheduled jobs", "Paint", "Notepad", "Calculator"]'::jsonb, 0, 'Task Scheduler runs scripts on a schedule.'),
  ('powershell-08', 3, 'ConvertTo-Html is useful for…', '["deleting files", "producing HTML reports", "encrypting", "routing"]'::jsonb, 1, 'It generates HTML reports.'),
  ('python-01', 1, 'Python blocks are defined by…', '["braces {}", "indentation", "semicolons", "BEGIN/END"]'::jsonb, 1, 'Indentation defines blocks in Python.'),
  ('python-01', 2, 'Which built-in reads keyboard input?', '["input()", "scan()", "read()", "get()"]'::jsonb, 0, 'input() reads from stdin.'),
  ('python-01', 3, 'A Python list is…', '["immutable", "an ordered, mutable collection", "a single value", "a file"]'::jsonb, 1, 'Lists are ordered and mutable.'),
  ('python-02', 1, 'Which module handles filesystem paths cleanly?', '["pathlib", "math", "random", "socket"]'::jsonb, 0, 'pathlib models filesystem paths.'),
  ('python-02', 2, 'Opening a file safely uses…', '["with open(...) as f:", "goto", "malloc", "open() and forget"]'::jsonb, 0, 'The with-statement auto-closes files.'),
  ('python-02', 3, 'os.listdir() returns…', '["file contents", "the names in a directory", "a single file", "permissions"]'::jsonb, 1, 'It lists directory entries.'),
  ('python-03', 1, 'subprocess.run() is used to…', '["parse JSON", "execute external commands", "open sockets", "sort lists"]'::jsonb, 1, 'It runs external processes.'),
  ('python-03', 2, 'Capturing a command''s output uses…', '["capture_output=True", "silent=True", "quiet()", "noout"]'::jsonb, 0, 'capture_output=True collects stdout/stderr.'),
  ('python-03', 3, 'Checking a command succeeded means inspecting its…', '["colour", "returncode", "filename", "length"]'::jsonb, 1, 'returncode 0 means success.'),
  ('python-04', 1, 'Low-level network connections use which module?', '["socket", "csv", "turtle", "timeit"]'::jsonb, 0, 'socket provides network primitives.'),
  ('python-04', 2, 'A popular library for HTTP requests is…', '["requests", "pandas", "pygame", "tkinter"]'::jsonb, 0, 'requests handles HTTP simply.'),
  ('python-04', 3, 'Automating network devices commonly uses libraries like…', '["Netmiko/Paramiko", "NumPy", "Flask", "Pillow"]'::jsonb, 0, 'Netmiko/Paramiko drive SSH to devices.'),
  ('python-05', 1, 'Pattern matching in log text commonly uses the…', '["re (regex) module", "os module", "sys module", "gc module"]'::jsonb, 0, 're provides regular expressions.'),
  ('python-05', 2, 'Reading a large log line-by-line is memory-efficient because it…', '["loads all at once", "iterates without loading the whole file", "skips lines", "encrypts"]'::jsonb, 1, 'Iterating a file object streams lines.'),
  ('python-05', 3, 'Splitting a CSV-like line uses…', '["str.split('','') or the csv module", "math.floor", "time.sleep", "os.exit"]'::jsonb, 0, 'split or the csv module parses fields.'),
  ('python-06', 1, 'On Linux, recurring jobs are often scheduled with…', '["cron", "paint", "grep", "awk"]'::jsonb, 0, 'cron schedules recurring jobs.'),
  ('python-06', 2, 'A crontab field order is…', '["minute hour day month weekday", "year only", "random", "hour only"]'::jsonb, 0, 'Five time fields: min hr dom mon dow.'),
  ('python-06', 3, 'Making a Python script directly runnable needs…', '["a shebang and execute permission", "a .docx extension", "no changes", "a GUI"]'::jsonb, 0, 'Shebang + chmod +x.'),
  ('python-07', 1, 'A monitoring script typically alerts when a metric…', '["is logged", "crosses a threshold", "is colourful", "is short"]'::jsonb, 1, 'Thresholds trigger alerts.'),
  ('python-07', 2, 'Reading system metrics like CPU/memory often uses…', '["psutil", "pygame", "flask", "pillow"]'::jsonb, 0, 'psutil exposes system metrics.'),
  ('python-07', 3, 'Sending an alert email uses the…', '["smtplib module", "csv module", "math module", "gc module"]'::jsonb, 0, 'smtplib sends mail.'),
  ('python-08', 1, 'Ansible primarily uses which data format for playbooks?', '["YAML", "binary", "CSV", "HTML"]'::jsonb, 0, 'Playbooks are YAML.'),
  ('python-08', 2, 'Ansible is described as… by default', '["agentless (over SSH)", "agent-heavy", "GUI-only", "Windows-only"]'::jsonb, 0, 'Ansible is agentless over SSH.'),
  ('python-08', 3, 'Python relates to Ansible because Ansible is…', '["unrelated", "written in Python and extensible with Python modules", "a Python IDE", "a Python web server"]'::jsonb, 1, 'Ansible is Python-based and extensible.'),
  ('python-09', 1, 'Parsing command-line arguments cleanly uses…', '["argparse", "random", "turtle", "timeit"]'::jsonb, 0, 'argparse builds CLIs.'),
  ('python-09', 2, 'Packaging a CLI for reuse often involves a…', '["setup.py / pyproject.toml", "docx", "png", "wav"]'::jsonb, 0, 'Packaging metadata enables install/distribution.'),
  ('python-09', 3, 'A good CLI tool returns a non-zero exit code when it…', '["succeeds", "fails", "prints help", "starts"]'::jsonb, 1, 'Non-zero signals failure to callers.'),
  ('cybersecurity-01', 1, 'The CIA triad stands for…', '["Confidentiality, Integrity, Availability", "Control, Inspect, Audit", "Cipher, Index, Access", "Cloud, IAM, Access"]'::jsonb, 0, 'Confidentiality, Integrity, Availability.'),
  ('cybersecurity-01', 2, 'Encryption primarily protects which property?', '["Availability", "Confidentiality", "Integrity", "Speed"]'::jsonb, 1, 'Encryption protects confidentiality.'),
  ('cybersecurity-01', 3, 'A hash/checksum primarily protects…', '["availability", "integrity", "confidentiality", "bandwidth"]'::jsonb, 1, 'Hashes verify integrity.'),
  ('cybersecurity-02', 1, 'Threat modelling aims to…', '["ignore risk", "identify assets, threats, and mitigations early", "buy hardware", "speed networks"]'::jsonb, 1, 'It surfaces threats and mitigations by design.'),
  ('cybersecurity-02', 2, '''Attack surface'' refers to…', '["the GUI", "all the points an attacker could target", "disk space", "the help desk"]'::jsonb, 1, 'The sum of exposable entry points.'),
  ('cybersecurity-02', 3, 'Reducing attack surface usually means…', '["enabling everything", "disabling unused services/features", "sharing passwords", "opening all ports"]'::jsonb, 1, 'Turn off what isn''t needed.'),
  ('cybersecurity-03', 1, 'A key Windows hardening practice is…', '["leave default accounts enabled", "apply security baselines and disable unused services", "open all firewall ports", "share admin creds"]'::jsonb, 1, 'Baselines + minimal services.'),
  ('cybersecurity-03', 2, 'LAPS (Local Administrator Password Solution) helps by…', '["reusing one admin password", "randomising/managing local admin passwords", "disabling admins", "logging users out"]'::jsonb, 1, 'LAPS rotates unique local admin passwords.'),
  ('cybersecurity-03', 3, 'Least privilege on Windows means…', '["everyone is admin", "users get only the rights they need", "no accounts", "shared logins"]'::jsonb, 1, 'Grant minimal necessary rights.'),
  ('cybersecurity-04', 1, 'A core Linux hardening step is…', '["enable root SSH", "disable root SSH and use sudo", "open all ports", "run as root always"]'::jsonb, 1, 'Disable root SSH; use sudo.'),
  ('cybersecurity-04', 2, 'SELinux/AppArmor provide…', '["antivirus", "mandatory access control confinement", "backups", "DNS"]'::jsonb, 1, 'MAC confines processes.'),
  ('cybersecurity-04', 3, 'Keeping packages patched addresses…', '["theme changes", "known vulnerabilities", "disk speed", "fonts"]'::jsonb, 1, 'Patching fixes known CVEs.'),
  ('cybersecurity-05', 1, 'A secure default firewall policy is…', '["allow all", "default-deny, allow only required traffic", "block outbound only", "no rules"]'::jsonb, 1, 'Default-deny with explicit allows.'),
  ('cybersecurity-05', 2, 'A stateful firewall tracks…', '["file sizes", "connection state to allow return traffic", "user names", "disk usage"]'::jsonb, 1, 'It tracks connections/sessions.'),
  ('cybersecurity-05', 3, 'Segmentation with firewalls limits…', '["logging", "lateral movement after a breach", "backups", "DNS"]'::jsonb, 1, 'It contains attacker movement.'),
  ('cybersecurity-06', 1, 'In PKI, a certificate binds a public key to…', '["a port", "an identity", "a disk", "a VLAN"]'::jsonb, 1, 'Certificates bind keys to identities.'),
  ('cybersecurity-06', 2, 'TLS provides…', '["encryption + authentication in transit", "backups", "routing", "DHCP"]'::jsonb, 0, 'TLS secures data in transit.'),
  ('cybersecurity-06', 3, 'A Certificate Authority (CA) is trusted to…', '["assign IPs", "issue and sign certificates", "run backups", "manage Wi-Fi"]'::jsonb, 1, 'CAs issue/sign trusted certs.'),
  ('cybersecurity-07', 1, 'A SIEM primarily…', '["blocks USB", "aggregates and correlates security logs/events", "assigns IPs", "images disks"]'::jsonb, 1, 'SIEM centralises and correlates events.'),
  ('cybersecurity-07', 2, 'An IDS is designed to…', '["prevent all attacks", "detect and alert on suspicious activity", "encrypt disks", "route packets"]'::jsonb, 1, 'IDS detects and alerts.'),
  ('cybersecurity-07', 3, 'The difference with an IPS is that it can also…', '["only log", "actively block detected threats", "assign DNS", "format disks"]'::jsonb, 1, 'IPS can block, not just detect.'),
  ('cybersecurity-08', 1, 'Vulnerability scanning aims to…', '["exploit systems", "identify known weaknesses before attackers do", "delete logs", "encrypt data"]'::jsonb, 1, 'It finds known weaknesses proactively.'),
  ('cybersecurity-08', 2, 'A CVE is…', '["a firewall", "a public identifier for a known vulnerability", "a backup type", "a port"]'::jsonb, 1, 'CVE = catalogued known vulnerability.'),
  ('cybersecurity-08', 3, 'Scanning differs from penetration testing because scanning…', '["exploits everything", "identifies issues without necessarily exploiting them", "is illegal", "needs no tools"]'::jsonb, 1, 'Scans detect; pentests exploit.'),
  ('cybersecurity-09', 1, 'A common incident response order is…', '["Ignore, hope", "Prepare, Identify, Contain, Eradicate, Recover, Learn", "Delete, deny", "Reboot only"]'::jsonb, 1, 'The classic IR lifecycle.'),
  ('cybersecurity-09', 2, 'Containment aims to…', '["spread the incident", "limit the damage/scope", "delete evidence", "blame users"]'::jsonb, 1, 'Contain to stop the spread.'),
  ('cybersecurity-09', 3, 'Preserving logs/evidence during IR supports…', '["faster Wi-Fi", "forensics and lessons learned", "backups", "DNS"]'::jsonb, 1, 'Evidence enables analysis and learning.'),
  ('cybersecurity-10', 1, 'A ''pass-the-hash'' attack abuses…', '["printer drivers", "captured password hashes to authenticate", "DNS", "DHCP"]'::jsonb, 1, 'It reuses hashes to authenticate.'),
  ('cybersecurity-10', 2, 'Tiered administration in AD limits…', '["logging", "credential exposure across privilege levels", "backups", "Wi-Fi"]'::jsonb, 1, 'Tiering contains credential theft.'),
  ('cybersecurity-10', 3, 'Protecting Domain Admins matters because they…', '["print", "effectively control the entire domain", "manage Wi-Fi", "store files"]'::jsonb, 1, 'DA compromise = full domain control.'),
  ('troubleshooting-01', 1, 'A sound troubleshooting method works by…', '["guessing fast", "isolating one variable at a time", "changing everything", "rebooting only"]'::jsonb, 1, 'Change one variable at a time.'),
  ('troubleshooting-01', 2, 'After identifying a probable cause you should…', '["assume it''s fixed", "test your theory", "close the ticket", "escalate"]'::jsonb, 1, 'Test the hypothesis before broad changes.'),
  ('troubleshooting-01', 3, 'Documenting the fix matters because it…', '["wastes time", "helps future diagnosis and others", "is required by law", "hides issues"]'::jsonb, 1, 'Notes speed future resolution.'),
  ('troubleshooting-02', 1, 'Windows application/system errors are best reviewed in…', '["Event Viewer", "Paint", "Calculator", "Notepad"]'::jsonb, 0, 'Event Viewer holds Windows logs.'),
  ('troubleshooting-02', 2, 'A repeated app crash''s details often appear under…', '["Security log", "Application log", "DNS", "BIOS"]'::jsonb, 1, 'App crashes log to the Application log.'),
  ('troubleshooting-02', 3, 'Booting with minimal drivers/services uses…', '["Safe Mode", "Sleep", "Hibernate", "Fast Startup"]'::jsonb, 0, 'Safe Mode loads a minimal environment.'),
  ('troubleshooting-03', 1, 'On Linux, recent service logs are viewed with…', '["journalctl", "ipconfig", "regedit", "Event Viewer"]'::jsonb, 0, 'journalctl reads the systemd journal.'),
  ('troubleshooting-03', 2, 'Disk space issues are checked with…', '["df -h", "ping", "ls only", "whoami"]'::jsonb, 0, 'df -h shows filesystem usage.'),
  ('troubleshooting-03', 3, 'A service that won''t start is inspected with…', '["systemctl status <svc>", "format", "reboot only", "cd"]'::jsonb, 0, 'systemctl status shows why it failed.'),
  ('troubleshooting-04', 1, 'To test reachability to a host you use…', '["ping", "chmod", "df", "ls"]'::jsonb, 0, 'ping tests basic reachability.'),
  ('troubleshooting-04', 2, 'To trace the path packets take you use…', '["traceroute/tracert", "cat", "top", "kill"]'::jsonb, 0, 'traceroute maps the hop path.'),
  ('troubleshooting-04', 3, 'Names fail but IPs work — the likely culprit is…', '["the CPU", "DNS", "the monitor", "RAM"]'::jsonb, 1, 'Name-only failure points to DNS.'),
  ('troubleshooting-05', 1, 'Repeated AD account lockouts often trace to…', '["a failing GPU", "cached old credentials on a device", "low disk", "a dead mouse"]'::jsonb, 1, 'Stale cached creds relock accounts.'),
  ('troubleshooting-05', 2, 'Group Policy not applying is first checked with…', '["gpresult / gpupdate", "format c:", "ping -t", "chkdsk"]'::jsonb, 0, 'gpresult/gpupdate diagnose GPO application.'),
  ('troubleshooting-05', 3, 'AD replication problems can be diagnosed with…', '["repadmin", "notepad", "paint", "calc"]'::jsonb, 0, 'repadmin reports replication health.'),
  ('troubleshooting-06', 1, 'A performance bottleneck is found by checking…', '["only the theme", "CPU, memory, disk, and network utilisation", "the wallpaper", "the font"]'::jsonb, 1, 'Inspect the four core resources.'),
  ('troubleshooting-06', 2, 'Constant disk paging usually indicates…', '["too much RAM", "insufficient memory", "a fast CPU", "good health"]'::jsonb, 1, 'Heavy paging = memory pressure.'),
  ('troubleshooting-06', 3, 'Capacity planning aims to…', '["react after outages", "anticipate growth before resources run out", "ignore trends", "delete logs"]'::jsonb, 1, 'Plan ahead of demand.');
