-- 0017_seed_interview.sql — Phase 9 seed: interview prep questions. Idempotent.
delete from public.interview_questions;
insert into public.interview_questions (category, track, prompt, sample_answer, key_points, sort) values
('behavioral', null, 'Tell me about a time you helped a frustrated user.',
 'I stay calm and lead with empathy: acknowledge their frustration, confirm I understand the impact, and set a clear expectation for what I''ll do next. I then work the problem methodically and keep them informed, and I close by confirming it''s resolved and they''re comfortable.',
 '["Empathy and active listening first","Acknowledge impact, set expectations","Methodical resolution + status updates","Confirm resolution and follow up"]', 1),
('behavioral', null, 'How do you prioritize when several urgent tickets land at once?',
 'I triage by business impact and severity — how many people are affected and whether work is fully blocked — then communicate ETAs so no one is left in the dark. I escalate early if something exceeds my scope or time.',
 '["Triage by impact + severity","Number of users affected / fully blocked","Communicate ETAs","Escalate early when needed"]', 2),
('behavioral', null, 'Tell me about a time you did not know the answer.',
 'I''m honest that I don''t know yet, then I research methodically, check documentation and trusted sources, and escalate to the right team if needed. I make a point to learn it so I can handle it next time, and I document the fix.',
 '["Honesty over bluffing","Research methodically","Escalate appropriately","Learn it + document for next time"]', 3),
('behavioral', null, 'Describe a difficult technical problem you solved.',
 'I describe the symptom, how I isolated the cause one variable at a time, the hypothesis I tested, and the fix — plus what I documented afterward so it''s faster next time. I focus on the structured approach, not luck.',
 '["Clear symptom statement","Isolate one variable at a time","Test a hypothesis","Document the resolution"]', 4),
('technical', 'helpdesk', 'A user says "the internet is down." How do you troubleshoot?',
 'I work outward one layer at a time: confirm physical/Wi-Fi, check for a valid IP (a 169.254 address means DHCP failed), test the gateway, then a public IP, then DNS. The first rung that fails tells me where the problem is — for example, pinging IPs but not names points to DNS.',
 '["Work the layers outward","169.254 = DHCP failure","Gateway then public IP then DNS","IPs work but names fail = DNS"]', 5),
('technical', 'helpdesk', 'Walk me through resetting a user''s AD password — and what you check afterward.',
 'First I verify the person''s identity. I reset the password, set "must change at next logon," and confirm they can sign in. Crucially, I check why it happened — a cached old password on a phone or mapped drive is the classic cause of repeat lockouts — and fix that source.',
 '["Verify identity first","Reset + must-change-at-next-logon","Confirm sign-in","Fix cached-credential source to stop relocks"]', 6),
('technical', 'helpdesk', 'How would you handle a reported phishing email?',
 'Tell the user not to click links or reply, and to leave it in place. Report it to the security team through the proper channel, check whether others received it, and help contain any exposure. Then reinforce how to spot similar messages.',
 '["Don''t click / don''t reply","Report through the right channel","Check blast radius / contain","Educate the user"]', 7),
('technical', 'sysadmin', 'Explain the difference between a DNS A record and a CNAME.',
 'An A record maps a hostname directly to an IPv4 address. A CNAME is an alias that points one name to another name, which then resolves to an address. Use A for the canonical host and CNAME when you want several names to follow one target.',
 '["A = name → IPv4 address","CNAME = alias name → another name","CNAME ultimately resolves via the target","Use CNAME for multiple aliases"]', 8),
('technical', 'sysadmin', 'What is the principle of least privilege, and why does it matter?',
 'Give every user, service, and process only the access it needs — nothing more. It limits the damage from mistakes and from compromised accounts, and it shrinks the attack surface. It''s a foundational security habit, from file permissions to admin tiering.',
 '["Grant only the access needed","Limits blast radius of error/compromise","Shrinks attack surface","Applies from file perms to admin tiering"]', 9),
('technical', 'sysadmin', 'How does DHCP assign an address (the DORA process)?',
 'DORA: the client broadcasts a Discover, the server replies with an Offer, the client sends a Request for that address, and the server returns an Acknowledge — then the client holds the lease for its duration. Reservations bind a specific IP to a MAC.',
 '["Discover, Offer, Request, Acknowledge","Client broadcasts, server offers","Lease has a duration","Reservation = IP bound to MAC"]', 10),
('technical', 'sysadmin', 'What is the 3-2-1 backup rule?',
 'Keep three copies of your data, on two different media types, with one copy offsite. It protects against single points of failure — a bad disk, a site disaster, or ransomware — and backups should be tested by actually restoring them.',
 '["3 copies of the data","2 different media types","1 copy offsite","Test restores regularly"]', 11),
('technical', 'helpdesk', 'What is the difference between RAM and storage?',
 'RAM is fast, volatile working memory the system uses for running programs — it clears on power off. Storage (SSD/HDD) is slower but persistent, holding the OS and files. Too little RAM causes constant disk paging and slowness; a failing or full drive causes its own symptoms.',
 '["RAM = fast, volatile working memory","Storage = persistent OS + files","Too little RAM = paging/slowness","Failing/full drive = its own symptoms"]', 12);
