-- 0029_seed_winserver_lessons.sql — P18 Windows Server expansion (curriculum_lessons XP authority). Idempotent.
insert into public.curriculum_lessons (id, slug, title, track, xp, sort_order) values
  ('ws-ad-01', 'architecture', 'AD DS Architecture & Installation', 'sysadmin', 90, 2001),
  ('ws-ad-02', 'domains-forests', 'Domains, Trees & Forests', 'sysadmin', 90, 2002),
  ('ws-ad-03', 'ous-delegation', 'Organizational Units & Delegation', 'sysadmin', 90, 2003),
  ('ws-ad-04', 'groups-scopes', 'Users, Groups & Group Scopes', 'sysadmin', 90, 2004),
  ('ws-ad-05', 'fsmo', 'FSMO Roles', 'sysadmin', 95, 2005),
  ('ws-ad-06', 'sites-replication', 'Sites, Subnets & Replication', 'sysadmin', 95, 2006),
  ('ws-ad-07', 'trusts', 'Trusts', 'sysadmin', 90, 2007),
  ('ws-ad-08', 'maintenance', 'AD Maintenance & Health', 'sysadmin', 95, 2008),
  ('ws-gp-01', 'architecture', 'Group Policy Architecture', 'sysadmin', 85, 2009),
  ('ws-gp-02', 'processing-order', 'Processing Order & Precedence', 'sysadmin', 90, 2010),
  ('ws-gp-03', 'security-settings', 'Security Settings & Admin Templates', 'sysadmin', 90, 2011),
  ('ws-gp-04', 'preferences', 'Group Policy Preferences', 'sysadmin', 85, 2012),
  ('ws-gp-05', 'deployment', 'Folder Redirection & Software Deployment', 'sysadmin', 90, 2013),
  ('ws-gp-06', 'troubleshooting', 'Troubleshooting Group Policy', 'sysadmin', 90, 2014),
  ('ws-dns-01', 'dns-zones', 'DNS Fundamentals & Zones', 'sysadmin', 90, 2015),
  ('ws-dns-02', 'dns-records', 'DNS Record Types', 'sysadmin', 85, 2016),
  ('ws-dns-03', 'forwarders', 'Forwarders, Conditional Forwarders & Recursion', 'sysadmin', 90, 2017),
  ('ws-dns-04', 'dns-security', 'DNS Security & Maintenance', 'sysadmin', 90, 2018),
  ('ws-dhcp-01', 'dhcp-scopes', 'DHCP Fundamentals & Scopes', 'sysadmin', 85, 2019),
  ('ws-dhcp-02', 'dhcp-ha', 'DHCP High Availability', 'sysadmin', 90, 2020),
  ('ws-dhcp-03', 'dhcp-troubleshooting', 'DHCP Management & Troubleshooting', 'sysadmin', 85, 2021),
  ('ws-fs-01', 'permissions', 'NTFS & Share Permissions', 'sysadmin', 90, 2022),
  ('ws-fs-02', 'dfs', 'DFS Namespaces & Replication', 'sysadmin', 90, 2023),
  ('ws-fs-03', 'fsrm', 'File Server Resource Manager (Quotas & Screening)', 'sysadmin', 85, 2024),
  ('ws-fs-04', 'storage-spaces', 'Storage Spaces & Resiliency', 'sysadmin', 90, 2025),
  ('ws-fs-05', 'iscsi', 'iSCSI & Shared Storage', 'sysadmin', 85, 2026),
  ('ws-fs-06', 'dedup-vss', 'Deduplication & Shadow Copies', 'sysadmin', 85, 2027),
  ('ws-hv-01', 'basics', 'Hyper-V Basics & Installation', 'sysadmin', 90, 2028),
  ('ws-hv-02', 'virtual-switches', 'Virtual Switches & Networking', 'sysadmin', 90, 2029),
  ('ws-hv-03', 'vm-config', 'Creating & Configuring VMs', 'sysadmin', 90, 2030),
  ('ws-hv-04', 'virtual-disks', 'Virtual Disks & Storage', 'sysadmin', 85, 2031),
  ('ws-hv-05', 'checkpoints', 'Checkpoints & VM Management', 'sysadmin', 85, 2032),
  ('ws-hv-06', 'live-migration', 'Live Migration & Replica', 'sysadmin', 90, 2033),
  ('ws-sec-01', 'principles', 'Security Principles & Tiered Admin', 'sysadmin', 90, 2034),
  ('ws-sec-02', 'laps', 'Local Admin Passwords & LAPS', 'sysadmin', 85, 2035),
  ('ws-sec-03', 'defender-firewall', 'Windows Defender & Firewall', 'sysadmin', 85, 2036),
  ('ws-sec-04', 'bitlocker', 'BitLocker & Credential Guard', 'sysadmin', 85, 2037),
  ('ws-sec-05', 'patching', 'Patching & Update Management', 'sysadmin', 85, 2038),
  ('ws-sec-06', 'auditing', 'Auditing & Security Logging', 'sysadmin', 85, 2039),
  ('ws-sec-07', 'hardening', 'Attack Surface Reduction & Baselines', 'sysadmin', 90, 2040),
  ('ws-ps-01', 'fundamentals', 'PowerShell for Server Admins', 'sysadmin', 90, 2041),
  ('ws-ps-02', 'pipeline', 'Filtering, Formatting & the Pipeline', 'sysadmin', 85, 2042),
  ('ws-ps-03', 'managing', 'Managing Servers with Cmdlets', 'sysadmin', 90, 2043),
  ('ws-ps-04', 'remoting', 'PowerShell Remoting', 'sysadmin', 90, 2044),
  ('ws-ps-05', 'bulk', 'Bulk Administration & Scripting', 'sysadmin', 95, 2045),
  ('ws-ps-06', 'dsc-reporting', 'Scheduling, Reporting & DSC', 'sysadmin', 90, 2046),
  ('ws-bk-01', 'fundamentals', 'Backup Fundamentals', 'sysadmin', 85, 2047),
  ('ws-bk-02', 'windows-server-backup', 'Windows Server Backup', 'sysadmin', 85, 2048),
  ('ws-bk-03', 'restore', 'Restore & Recovery Scenarios', 'sysadmin', 90, 2049),
  ('ws-bk-04', 'clustering', 'Failover Clustering Basics', 'sysadmin', 90, 2050),
  ('ws-bk-05', 'dr-planning', 'Disaster Recovery Planning', 'sysadmin', 90, 2051),
  ('ws-fnd-01', 'editions', 'Editions, Licensing & Installation', 'sysadmin', 85, 2052),
  ('ws-fnd-02', 'server-core', 'Server Core vs Desktop Experience', 'sysadmin', 90, 2053),
  ('ws-fnd-03', 'initial-config', 'Initial Server Configuration', 'sysadmin', 85, 2054),
  ('ws-fnd-04', 'management-tools', 'Server Manager & Windows Admin Center', 'sysadmin', 85, 2055),
  ('ws-fnd-05', 'roles-features', 'Roles & Features', 'sysadmin', 85, 2056),
  ('ws-fnd-06', 'deployment', 'Deployment at Scale', 'sysadmin', 90, 2057),
  ('ws-ras-01', 'server-networking', 'Server Networking Configuration', 'sysadmin', 85, 2058),
  ('ws-ras-02', 'rras-vpn', 'Routing & Remote Access (VPN)', 'sysadmin', 90, 2059),
  ('ws-ras-03', 'nps-radius', 'Network Policy Server & RADIUS', 'sysadmin', 90, 2060),
  ('ws-ras-04', 'always-on-vpn', 'Always On VPN & Modern Remote Access', 'sysadmin', 90, 2061),
  ('ws-ras-05', 'rds', 'Remote Desktop Services Basics', 'sysadmin', 85, 2062),
  ('ws-mon-01', 'event-viewer', 'Event Viewer & Logs', 'sysadmin', 85, 2063),
  ('ws-mon-02', 'perfmon', 'Performance Monitor & Baselines', 'sysadmin', 90, 2064),
  ('ws-mon-03', 'services-startup', 'Services, Processes & Startup', 'sysadmin', 80, 2065),
  ('ws-mon-04', 'methodology', 'Troubleshooting Methodology', 'sysadmin', 90, 2066),
  ('ws-mon-05', 'common-problems', 'Common Server Problems', 'sysadmin', 90, 2067)
on conflict (id) do update set slug=excluded.slug, title=excluded.title, track=excluded.track, xp=excluded.xp, sort_order=excluded.sort_order;
