-- 0030_seed_winserver_quizzes.sql — P18 Windows Server quizzes. Idempotent.
insert into public.lesson_quizzes (lesson_id, pass_pct, bonus_xp) values
  ('ws-ad-01', 70, 30),
  ('ws-ad-02', 70, 30),
  ('ws-ad-03', 70, 30),
  ('ws-ad-04', 70, 30),
  ('ws-ad-05', 70, 30),
  ('ws-ad-06', 70, 30),
  ('ws-ad-07', 70, 30),
  ('ws-ad-08', 70, 30),
  ('ws-gp-01', 70, 30),
  ('ws-gp-02', 70, 30),
  ('ws-gp-03', 70, 30),
  ('ws-gp-04', 70, 30),
  ('ws-gp-05', 70, 30),
  ('ws-gp-06', 70, 30),
  ('ws-dns-01', 70, 30),
  ('ws-dns-02', 70, 30),
  ('ws-dns-03', 70, 30),
  ('ws-dns-04', 70, 30),
  ('ws-dhcp-01', 70, 30),
  ('ws-dhcp-02', 70, 30),
  ('ws-dhcp-03', 70, 30),
  ('ws-fs-01', 70, 30),
  ('ws-fs-02', 70, 30),
  ('ws-fs-03', 70, 30),
  ('ws-fs-04', 70, 30),
  ('ws-fs-05', 70, 30),
  ('ws-fs-06', 70, 30),
  ('ws-hv-01', 70, 30),
  ('ws-hv-02', 70, 30),
  ('ws-hv-03', 70, 30),
  ('ws-hv-04', 70, 30),
  ('ws-hv-05', 70, 30),
  ('ws-hv-06', 70, 30),
  ('ws-sec-01', 70, 30),
  ('ws-sec-02', 70, 30),
  ('ws-sec-03', 70, 30),
  ('ws-sec-04', 70, 30),
  ('ws-sec-05', 70, 30),
  ('ws-sec-06', 70, 30),
  ('ws-sec-07', 70, 30),
  ('ws-ps-01', 70, 30),
  ('ws-ps-02', 70, 30),
  ('ws-ps-03', 70, 30),
  ('ws-ps-04', 70, 30),
  ('ws-ps-05', 70, 30),
  ('ws-ps-06', 70, 30),
  ('ws-bk-01', 70, 30),
  ('ws-bk-02', 70, 30),
  ('ws-bk-03', 70, 30),
  ('ws-bk-04', 70, 30),
  ('ws-bk-05', 70, 30),
  ('ws-fnd-01', 70, 30),
  ('ws-fnd-02', 70, 30),
  ('ws-fnd-03', 70, 30),
  ('ws-fnd-04', 70, 30),
  ('ws-fnd-05', 70, 30),
  ('ws-fnd-06', 70, 30),
  ('ws-ras-01', 70, 30),
  ('ws-ras-02', 70, 30),
  ('ws-ras-03', 70, 30),
  ('ws-ras-04', 70, 30),
  ('ws-ras-05', 70, 30),
  ('ws-mon-01', 70, 30),
  ('ws-mon-02', 70, 30),
  ('ws-mon-03', 70, 30),
  ('ws-mon-04', 70, 30),
  ('ws-mon-05', 70, 30)
on conflict (lesson_id) do update set pass_pct=excluded.pass_pct, bonus_xp=excluded.bonus_xp;

delete from public.quiz_questions where lesson_id in ('ws-ad-01', 'ws-ad-02', 'ws-ad-03', 'ws-ad-04', 'ws-ad-05', 'ws-ad-06', 'ws-ad-07', 'ws-ad-08', 'ws-gp-01', 'ws-gp-02', 'ws-gp-03', 'ws-gp-04', 'ws-gp-05', 'ws-gp-06', 'ws-dns-01', 'ws-dns-02', 'ws-dns-03', 'ws-dns-04', 'ws-dhcp-01', 'ws-dhcp-02', 'ws-dhcp-03', 'ws-fs-01', 'ws-fs-02', 'ws-fs-03', 'ws-fs-04', 'ws-fs-05', 'ws-fs-06', 'ws-hv-01', 'ws-hv-02', 'ws-hv-03', 'ws-hv-04', 'ws-hv-05', 'ws-hv-06', 'ws-sec-01', 'ws-sec-02', 'ws-sec-03', 'ws-sec-04', 'ws-sec-05', 'ws-sec-06', 'ws-sec-07', 'ws-ps-01', 'ws-ps-02', 'ws-ps-03', 'ws-ps-04', 'ws-ps-05', 'ws-ps-06', 'ws-bk-01', 'ws-bk-02', 'ws-bk-03', 'ws-bk-04', 'ws-bk-05', 'ws-fnd-01', 'ws-fnd-02', 'ws-fnd-03', 'ws-fnd-04', 'ws-fnd-05', 'ws-fnd-06', 'ws-ras-01', 'ws-ras-02', 'ws-ras-03', 'ws-ras-04', 'ws-ras-05', 'ws-mon-01', 'ws-mon-02', 'ws-mon-03', 'ws-mon-04', 'ws-mon-05');

insert into public.quiz_questions (lesson_id, sort, prompt, options, correct_index, explanation) values
  ('ws-ad-01', 1, 'What is the top-level security boundary in Active Directory?', '["A domain", "A forest", "An OU", "A site"]'::jsonb, 1, 'The forest is the top-level security boundary; it contains domains sharing a schema.'),
  ('ws-ad-01', 2, 'Which file is the Active Directory database on a domain controller?', '["SYSVOL", "NTDS.dit", "boot.ini", "registry.pol"]'::jsonb, 1, 'NTDS.dit stores the directory database on each DC.'),
  ('ws-ad-01', 3, 'AD DS depends on which service to locate domain controllers?', '["DHCP", "DNS", "WINS", "FTP"]'::jsonb, 1, 'Clients find DCs via DNS SRV records, so AD requires DNS.'),
  ('ws-ad-02', 1, 'Domains in the same forest trust each other via…', '["Manual one-way trusts", "Automatic two-way transitive trusts", "No trust by default", "External trusts only"]'::jsonb, 1, 'Intra-forest trusts are automatic, two-way, and transitive.'),
  ('ws-ad-02', 2, 'A contiguous DNS namespace of parent/child domains forms a…', '["Site", "Tree", "Schema", "GPO"]'::jsonb, 1, 'A tree is domains sharing a contiguous namespace.'),
  ('ws-ad-02', 3, 'Raising the forest functional level primarily…', '["Deletes old objects", "Enables newer AD features and sets a minimum DC OS", "Speeds the network", "Resets passwords"]'::jsonb, 1, 'Functional levels gate features and require a minimum DC OS.'),
  ('ws-ad-03', 1, 'What can you do with an OU that you cannot do with a default container?', '["Store users", "Link Group Policy and delegate control", "Hold computers", "Nothing different"]'::jsonb, 1, 'OUs support GPO links and delegation; default containers do not.'),
  ('ws-ad-03', 2, 'The Delegation of Control Wizard is used to…', '["Delete a domain", "Grant specific admin rights over an OU", "Raise functional levels", "Seize FSMO roles"]'::jsonb, 1, 'It grants scoped rights to a group for least-privilege admin.'),
  ('ws-ad-03', 3, 'By default, GPOs and permissions on a parent OU…', '["Are ignored by children", "Are inherited by child OUs", "Only apply to computers", "Require manual copy"]'::jsonb, 1, 'Inheritance flows settings down the OU hierarchy.'),
  ('ws-ad-04', 1, 'Which group type is used to assign resource permissions?', '["Distribution", "Security", "Universal only", "Contact"]'::jsonb, 1, 'Security groups are used in permissions; distribution groups are for email.'),
  ('ws-ad-04', 2, 'In the AGDLP strategy, permissions are assigned to which group?', '["Global", "Universal", "Domain Local", "Built-in"]'::jsonb, 2, 'Accounts→Global→Domain Local→Permissions: permissions go on the Domain Local group.'),
  ('ws-ad-04', 3, 'A Global group is best used to…', '["Assign permissions directly", "Group users by role in their domain", "Span the whole forest", "Store passwords"]'::jsonb, 1, 'Global groups collect users by role; Domain Local groups get the permissions.'),
  ('ws-ad-05', 1, 'Which FSMO role is the authoritative time source and handles account lockouts?', '["RID Master", "PDC Emulator", "Schema Master", "Infrastructure Master"]'::jsonb, 1, 'The PDC Emulator is the time source and central point for lockouts and password changes.'),
  ('ws-ad-05', 2, 'How many DCs can hold the Schema Master role in a forest?', '["One", "One per domain", "Every DC", "Two"]'::jsonb, 0, 'Schema Master is a single forest-wide role held by exactly one DC.'),
  ('ws-ad-05', 3, 'You should ''seize'' a FSMO role only when…', '["Transferring normally", "The current holder is permanently offline", "The network is slow", "Raising functional levels"]'::jsonb, 1, 'Seize only when the holder is gone for good; otherwise transfer gracefully.'),
  ('ws-ad-06', 1, 'Associating IP subnets with sites lets clients…', '["Skip authentication", "Authenticate against a nearby domain controller", "Bypass DNS", "Disable replication"]'::jsonb, 1, 'Subnet-to-site mapping directs clients to a local DC.'),
  ('ws-ad-06', 2, 'Inter-site replication is…', '["Uncompressed and instant", "Scheduled and compressed over site links", "Disabled by default", "Never used"]'::jsonb, 1, 'Inter-site replication is compressed and scheduled to conserve WAN bandwidth.'),
  ('ws-ad-06', 3, 'Which component builds the replication topology automatically?', '["KCC", "DHCP", "WSUS", "RID Master"]'::jsonb, 0, 'The Knowledge Consistency Checker (KCC) maintains connection objects.'),
  ('ws-ad-07', 1, 'A forest trust between two forests is…', '["Always one-way and non-transitive", "Transitive across the two forests", "The same as a shortcut trust", "Impossible"]'::jsonb, 1, 'Forest trusts are transitive across the two forests.'),
  ('ws-ad-07', 2, 'An external trust is…', '["Transitive", "Non-transitive to a single domain", "Automatic within a forest", "A Kerberos realm trust"]'::jsonb, 1, 'External trusts are non-transitive, to one domain in another forest.'),
  ('ws-ad-07', 3, 'A shortcut trust is used to…', '["Merge forests", "Speed authentication between two domains in a forest", "Trust a Linux realm", "Block access"]'::jsonb, 1, 'Shortcut trusts shorten the referral path between domains in a forest.'),
  ('ws-ad-08', 1, 'Which tool reports domain controller health tests?', '["dcdiag", "ipconfig", "gpupdate", "chkdsk"]'::jsonb, 0, 'dcdiag runs DC health diagnostics.'),
  ('ws-ad-08', 2, 'The AD Recycle Bin lets you…', '["Defrag the database", "Recover deleted directory objects", "Seize FSMO roles", "Raise functional levels"]'::jsonb, 1, 'It restores deleted AD objects with their attributes.'),
  ('ws-ad-08', 3, 'Kerberos authentication fails if clocks between hosts drift more than about…', '["1 hour", "5 minutes", "1 day", "1 week"]'::jsonb, 1, 'By default a skew beyond ~5 minutes breaks Kerberos, so time sync matters.'),
  ('ws-gp-01', 1, 'A GPO takes effect when it is…', '["Created", "Linked to a site, domain, or OU", "Renamed", "Backed up"]'::jsonb, 1, 'An unlinked GPO does nothing; linking to a container applies it.'),
  ('ws-gp-01', 2, 'The actual policy files are stored in…', '["NTDS.dit", "SYSVOL (the GPT)", "the registry hive only", "the pagefile"]'::jsonb, 1, 'The Group Policy Template lives in SYSVOL; the GPC is the AD object.'),
  ('ws-gp-01', 3, 'By default, Group Policy refreshes in the background about every…', '["5 minutes", "90 minutes (plus offset)", "24 hours", "week"]'::jsonb, 1, 'Background refresh is ~90 minutes with a random offset.'),
  ('ws-gp-02', 1, 'The default GPO processing order is…', '["OU, Domain, Site, Local", "Local, Site, Domain, OU", "Domain only", "Random"]'::jsonb, 1, 'LSDOU: Local, Site, Domain, OU — later (OU) wins on conflicts.'),
  ('ws-gp-02', 2, 'An ''Enforced'' GPO link…', '["Can always be blocked", "Wins and cannot be blocked by inheritance", "Is disabled", "Applies only to computers"]'::jsonb, 1, 'Enforced forces precedence and overrides Block Inheritance.'),
  ('ws-gp-02', 3, 'Security filtering lets you…', '["Encrypt a GPO", "Target a GPO to specific users/computers", "Speed replication", "Delete SYSVOL"]'::jsonb, 1, 'Filtering scopes a GPO to objects with Apply permission.'),
  ('ws-gp-03', 1, 'Password complexity and lockout are typically set…', '["Per user in the OU", "At the domain level", "In the registry only", "On each workstation"]'::jsonb, 1, 'Account policies apply at the domain level (with fine-grained exceptions).'),
  ('ws-gp-03', 2, 'Administrative Templates are backed by…', '["SYSVOL files only", "registry settings (ADMX)", "NTDS.dit", "DNS records"]'::jsonb, 1, 'Admin templates map to registry values defined in ADMX files.'),
  ('ws-gp-03', 3, 'A good starting point for hardening policy is…', '["Random settings", "Microsoft Security Baselines", "Disabling all logging", "One giant GPO"]'::jsonb, 1, 'Security Baselines give a vetted starting configuration.'),
  ('ws-gp-04', 1, 'Group Policy Preferences are best for…', '["Enforcing password policy", "Setting defaults like mapped drives and printers", "Replicating AD", "Seizing FSMO roles"]'::jsonb, 1, 'Preferences configure things like drives and printers, often user-changeable.'),
  ('ws-gp-04', 2, 'Item-level targeting lets a single preference…', '["Encrypt data", "Apply to specific OSes, groups, or IP ranges", "Bypass DNS", "Delete OUs"]'::jsonb, 1, 'Targeting filters which objects receive the preference.'),
  ('ws-gp-04', 3, 'You should never use GPP to store…', '["Drive maps", "Passwords", "Printers", "Shortcuts"]'::jsonb, 1, 'GPP password storage was insecure and has been removed.'),
  ('ws-gp-05', 1, 'Folder redirection is used to…', '["Encrypt the disk", "Point user folders like Documents to a network share", "Deploy DNS", "Seize FSMO roles"]'::jsonb, 1, 'It redirects known folders to a central, backed-up location.'),
  ('ws-gp-05', 2, 'Assigning software to a computer via GPO installs it…', '["At the next logon only", "At startup for all users of that machine", "Never automatically", "Only on servers"]'::jsonb, 1, 'Computer-assigned software installs at startup for the machine.'),
  ('ws-gp-05', 3, 'GPO software installation (GPSI) deploys which package type?', '[".exe", "Windows Installer .msi", ".zip", ".iso"]'::jsonb, 1, 'GPSI deploys .msi packages; complex apps use other tools.'),
  ('ws-gp-06', 1, 'Which command produces a Resultant Set of Policy report?', '["gpupdate", "gpresult /h", "dcdiag", "ipconfig"]'::jsonb, 1, 'gpresult /h writes an HTML RSoP report of applied policy.'),
  ('ws-gp-06', 2, 'A GPO applies but a user still doesn''t get it — a likely cause is…', '["The CPU is slow", "Security filtering excludes them", "DNS is fast", "The disk is full"]'::jsonb, 1, 'Security filtering (Apply permission) commonly blocks application.'),
  ('ws-gp-06', 3, 'Disagreeing DCs handing out old policy points to a problem with…', '["SYSVOL/AD replication", "the mouse", "the monitor", "the pagefile"]'::jsonb, 0, 'Replication issues cause inconsistent policy delivery.'),
  ('ws-dns-01', 1, 'A reverse lookup zone resolves…', '["Name to IP", "IP to name", "Name to name", "Port to service"]'::jsonb, 1, 'Reverse zones map IPs back to names via PTR records.'),
  ('ws-dns-01', 2, 'The recommended zone type on a domain controller is…', '["Primary file-based", "Secondary", "AD-integrated", "Stub only"]'::jsonb, 2, 'AD-integrated zones are multi-master, replicated, and support secure updates.'),
  ('ws-dns-01', 3, 'Secure dynamic updates require which zone type?', '["File-based primary", "AD-integrated", "Secondary", "Reverse only"]'::jsonb, 1, 'Only AD-integrated zones support secure dynamic updates.'),
  ('ws-dns-02', 1, 'Which record locates services such as domain controllers?', '["A", "SRV", "MX", "TXT"]'::jsonb, 1, 'SRV records advertise services and ports; AD relies on them.'),
  ('ws-dns-02', 2, 'A CNAME record is…', '["A mail route", "An alias to another name", "A reverse record", "A zone parameter"]'::jsonb, 1, 'CNAME aliases one name to another.'),
  ('ws-dns-02', 3, 'SPF and DKIM values are typically published as which record?', '["PTR", "TXT", "A", "NS"]'::jsonb, 1, 'Email authentication data is stored in TXT records.'),
  ('ws-dns-03', 1, 'A conditional forwarder sends queries for…', '["All domains", "A specific domain to a specific server", "Only reverse lookups", "Nothing"]'::jsonb, 1, 'It forwards a named domain''s queries to a chosen server.'),
  ('ws-dns-03', 2, 'Root hints are used when…', '["A forwarder is configured", "No forwarder answers \u2014 to reach the root servers", "Recursion is disabled", "The zone is AD-integrated"]'::jsonb, 1, 'Root hints provide the fallback path to the DNS root.'),
  ('ws-dns-03', 3, 'On an internet-facing authoritative server you should usually…', '["Enable open recursion", "Disable recursion", "Delete root hints", "Forward to itself"]'::jsonb, 1, 'Disabling recursion reduces abuse and amplification risk.'),
  ('ws-dns-04', 1, 'DNSSEC primarily protects against…', '["Slow queries", "Tampered/forged DNS answers", "Disk failure", "Password reuse"]'::jsonb, 1, 'DNSSEC lets resolvers verify record authenticity, countering poisoning.'),
  ('ws-dns-04', 2, 'Scavenging is used to…', '["Sign zones", "Remove stale dynamic records", "Add forwarders", "Speed replication"]'::jsonb, 1, 'Scavenging cleans up records that are no longer refreshed.'),
  ('ws-dns-04', 3, 'Which reduces DNS being used in amplification attacks?', '["Open recursion", "Response Rate Limiting", "Disabling logging", "More forwarders"]'::jsonb, 1, 'RRL limits repetitive responses used in amplification.'),
  ('ws-dhcp-01', 1, 'The DHCP lease process is abbreviated…', '["HTTP", "DORA", "TCP", "RAID"]'::jsonb, 1, 'Discover, Offer, Request, Acknowledge.'),
  ('ws-dhcp-01', 2, 'A DHCP reservation ties an IP to a device''s…', '["hostname", "MAC address", "username", "serial in DNS"]'::jsonb, 1, 'Reservations bind an address to a MAC.'),
  ('ws-dhcp-01', 3, 'Which DHCP option delivers the default gateway?', '["006", "003", "015", "051"]'::jsonb, 1, 'Option 003 is the router/default gateway; 006 is DNS.'),
  ('ws-dhcp-02', 1, 'DHCP failover hot-standby means…', '["Both serve actively", "One serves; the partner takes over on failure", "No redundancy", "Clients pick a server"]'::jsonb, 1, 'Hot standby keeps a passive partner ready to take over.'),
  ('ws-dhcp-02', 2, 'A DHCP relay agent is needed when…', '["Every subnet has a DHCP server", "A subnet has no local DHCP server", "DNS is down", "Leases are long"]'::jsonb, 1, 'Relay agents forward DHCP across subnets that lack a local server.'),
  ('ws-dhcp-02', 3, 'The modern preferred HA method is…', '["Split scope", "DHCP failover", "Superscope", "Manual assignment"]'::jsonb, 1, 'Built-in DHCP failover syncs leases automatically.'),
  ('ws-dhcp-03', 1, 'A client showing a 169.254.x.x address means…', '["A valid lease", "DHCP failed to assign an address", "A reservation", "A DNS issue"]'::jsonb, 1, '169.254 (APIPA) indicates no DHCP lease was obtained.'),
  ('ws-dhcp-03', 2, 'In a domain, a DHCP server must be… before it leases addresses.', '["Rebooted", "Authorized in Active Directory", "Renamed", "Virtualised"]'::jsonb, 1, 'AD authorization prevents rogue DHCP servers.'),
  ('ws-dhcp-03', 3, 'A duplicate-IP conflict on the LAN often comes from…', '["Too much RAM", "A static device inside the DHCP pool without an exclusion", "A fast CPU", "DNS scavenging"]'::jsonb, 1, 'Static IPs within the pool need exclusions to avoid conflicts.'),
  ('ws-fs-01', 1, 'Over the network, the effective permission is…', '["The most permissive", "The most restrictive of share and NTFS", "Always Full Control", "NTFS only"]'::jsonb, 1, 'The combined result is the most restrictive of the two layers.'),
  ('ws-fs-01', 2, 'Which permission type also applies when logged on locally?', '["Share", "NTFS", "Both are network-only", "Neither"]'::jsonb, 1, 'NTFS permissions apply locally and over the network; share is network-only.'),
  ('ws-fs-01', 3, 'An explicit Deny…', '["Is ignored", "Overrides an Allow", "Only affects admins", "Applies to files only"]'::jsonb, 1, 'Deny takes precedence over Allow in the access check.'),
  ('ws-fs-02', 1, 'DFS Namespaces provide…', '["Encryption", "A single logical path over multiple shares", "Faster CPUs", "DNS records"]'::jsonb, 1, 'DFS-N unifies shares behind one namespace path.'),
  ('ws-fs-02', 2, 'DFS Replication is used to…', '["Assign IPs", "Keep folder copies synchronised across servers", "Seize FSMO roles", "Sign DNS zones"]'::jsonb, 1, 'DFS-R replicates folder contents between targets.'),
  ('ws-fs-02', 3, 'A benefit of combining DFS-N and DFS-R is…', '["Slower access", "A stable path with a resilient, nearby copy", "No redundancy", "Losing data on failover"]'::jsonb, 1, 'Users keep one path while data stays replicated and available.'),
  ('ws-fs-03', 1, 'An FSRM hard quota…', '["Only warns", "Prevents writes past the limit", "Deletes files", "Encrypts the folder"]'::jsonb, 1, 'Hard quotas enforce the limit; soft quotas only warn.'),
  ('ws-fs-03', 2, 'File screening is used to…', '["Speed the disk", "Block or warn on specific file types", "Assign IPs", "Replicate DNS"]'::jsonb, 1, 'File screens control which file types can be saved.'),
  ('ws-fs-03', 3, 'Which finds large or old files on a share?', '["FSRM storage reports", "gpupdate", "repadmin", "nslookup"]'::jsonb, 0, 'FSRM generates storage reports on usage patterns.'),
  ('ws-fs-04', 1, 'A two-way mirror space protects against…', '["No failures", "The loss of one disk", "Only power loss", "DNS errors"]'::jsonb, 1, 'A mirror keeps copies so it survives a disk failure.'),
  ('ws-fs-04', 2, 'Parity resiliency is best described as…', '["No redundancy", "Space-efficient redundancy with slower writes", "Faster than mirror for writes", "Encryption"]'::jsonb, 1, 'Parity is space-efficient like RAID-5 but has a write penalty.'),
  ('ws-fs-04', 3, 'Storage Spaces requires…', '["A hardware RAID card", "Pooled physical disks and software resiliency", "An SSD only", "A domain controller"]'::jsonb, 1, 'It provides software resiliency over a pool of disks.'),
  ('ws-fs-05', 1, 'In iSCSI, the server offering storage is the…', '["Initiator", "Target", "Relay", "Forwarder"]'::jsonb, 1, 'The target presents the storage; the initiator connects to it.'),
  ('ws-fs-05', 2, 'Shared block storage via iSCSI is a requirement for…', '["DNS", "Failover clustering", "Group Policy", "Scavenging"]'::jsonb, 1, 'Clustered nodes need shared storage, which iSCSI can provide.'),
  ('ws-fs-05', 3, 'For best performance, iSCSI traffic should be…', '["Mixed with user traffic", "Isolated on its own network/VLAN", "Sent over Wi-Fi", "Disabled"]'::jsonb, 1, 'Isolating iSCSI improves performance and security.'),
  ('ws-fs-06', 1, 'Data deduplication saves space by…', '["Compressing the OS", "Storing duplicate data chunks only once", "Deleting old files", "Encrypting data"]'::jsonb, 1, 'Dedup keeps a single copy of repeated chunks.'),
  ('ws-fs-06', 2, 'Volume Shadow Copies let users…', '["Assign IPs", "Restore previous versions of files themselves", "Replicate DNS", "Create OUs"]'::jsonb, 1, 'VSS exposes point-in-time versions via Previous Versions.'),
  ('ws-fs-06', 3, 'Shadow copies are…', '["A full backup replacement", "Not a substitute for real backups", "Stored offsite automatically", "Encrypted by default"]'::jsonb, 1, 'They live on the same volume and don''t replace backups.'),
  ('ws-hv-01', 1, 'Hyper-V is which type of hypervisor?', '["Type 1 (bare-metal)", "Type 2", "A container engine", "A backup tool"]'::jsonb, 0, 'Hyper-V runs directly on the hardware — type 1.'),
  ('ws-hv-01', 2, 'Which CPU feature is required for Hyper-V?', '["Hyper-Threading only", "Hardware virtualization (VT-x/AMD-V) with SLAT", "Overclocking", "A discrete GPU"]'::jsonb, 1, 'Hardware virtualization plus SLAT is required.'),
  ('ws-hv-01', 3, 'After installing the role you can manage VMs with…', '["Only the BIOS", "Hyper-V Manager / WAC / PowerShell", "Notepad", "DNS Manager"]'::jsonb, 1, 'Hyper-V Manager, Windows Admin Center, or PowerShell.'),
  ('ws-hv-02', 1, 'Which virtual switch type lets VMs reach the physical LAN?', '["Private", "Internal", "External", "Isolated"]'::jsonb, 2, 'An external switch binds to a physical NIC for LAN/internet access.'),
  ('ws-hv-02', 2, 'A private virtual switch allows communication…', '["With the internet", "Only between VMs on that switch", "With the host only", "With DNS only"]'::jsonb, 1, 'Private switches connect VMs to each other only.'),
  ('ws-hv-02', 3, 'Combining NICs on a Hyper-V host for bandwidth/redundancy uses…', '["BitLocker", "Switch Embedded Teaming (SET)", "DFS-R", "WSUS"]'::jsonb, 1, 'SET teams physical NICs behind the virtual switch.'),
  ('ws-hv-03', 1, 'For a modern 64-bit guest you should choose…', '["Generation 1", "Generation 2", "Neither", "A container"]'::jsonb, 1, 'Gen 2 uses UEFI/Secure Boot and is preferred for modern guests.'),
  ('ws-hv-03', 2, 'Dynamic memory…', '["Fixes memory at boot", "Adjusts a VM''s RAM between a min and max on demand", "Disables the VM", "Encrypts RAM"]'::jsonb, 1, 'Dynamic memory scales RAM to need, improving density.'),
  ('ws-hv-03', 3, 'Integration services provide the guest with…', '["A public IP", "Better performance, time sync, and clean shutdown", "More CPUs automatically", "A firewall"]'::jsonb, 1, 'They improve guest integration with the host.'),
  ('ws-hv-04', 1, 'The preferred modern virtual disk format is…', '["VHD", "VHDX", "ISO", "VMDK"]'::jsonb, 1, 'VHDX supports up to 64 TB and is more resilient than VHD.'),
  ('ws-hv-04', 2, 'A dynamically expanding disk…', '["Allocates full size up front", "Grows as data is written", "Cannot be resized", "Is encrypted"]'::jsonb, 1, 'Dynamic disks grow on demand, saving space.'),
  ('ws-hv-04', 3, 'A fixed virtual disk is chosen for…', '["Maximum space savings", "Best performance", "Differencing chains", "Pass-through only"]'::jsonb, 1, 'Fixed disks pre-allocate for best performance.'),
  ('ws-hv-05', 1, 'The default, application-consistent checkpoint type is…', '["Standard", "Production", "Differencing", "Pass-through"]'::jsonb, 1, 'Production checkpoints use VSS for supported, consistent snapshots.'),
  ('ws-hv-05', 2, 'Checkpoints should be treated as…', '["Permanent backups", "Temporary \u2014 not a backup replacement", "Encryption", "VLANs"]'::jsonb, 1, 'They''re short-term rollback points, not backups.'),
  ('ws-hv-05', 3, 'Exporting a VM is used to…', '["Delete it", "Copy it for backup or moving to another host", "Assign an IP", "Sign DNS"]'::jsonb, 1, 'Export packages a VM and disks for backup/migration.'),
  ('ws-hv-06', 1, 'Live migration moves a running VM…', '["With a long outage", "With no downtime", "Only when powered off", "Only within a VM"]'::jsonb, 1, 'Live migration relocates a running VM without downtime.'),
  ('ws-hv-06', 2, 'True high availability for VMs (auto-restart on host failure) comes from…', '["Checkpoints", "Failover clustering", "DNS", "BitLocker"]'::jsonb, 1, 'Clustering restarts VMs on a surviving node.'),
  ('ws-hv-06', 3, 'Hyper-V Replica is primarily for…', '["Load balancing", "Disaster recovery to another site", "Faster disks", "VLAN tagging"]'::jsonb, 1, 'Replica provides DR by copying VMs to another location.'),
  ('ws-sec-01', 1, 'Administrative tiering primarily prevents…', '["Slow logons", "Credential theft cascading to full domain control", "DNS errors", "Disk failure"]'::jsonb, 1, 'Tiering stops a compromised low-tier machine yielding high-tier credentials.'),
  ('ws-sec-01', 2, 'Reducing attack surface means…', '["Installing every role", "Removing unused roles, features, and services", "Disabling logging", "Sharing admin passwords"]'::jsonb, 1, 'Fewer running components means fewer things to attack.'),
  ('ws-sec-01', 3, 'Least privilege says accounts should have…', '["Maximum access for convenience", "Only the access they need", "No authentication", "Shared credentials"]'::jsonb, 1, 'Grant the minimum access required.'),
  ('ws-sec-02', 1, 'LAPS solves the risk of…', '["Weak Wi-Fi", "A shared local admin password across machines", "Slow DNS", "Full disks"]'::jsonb, 1, 'LAPS gives each machine a unique, rotated local admin password.'),
  ('ws-sec-02', 2, 'LAPS stores the managed passwords…', '["In a text file", "Securely in Active Directory/Entra ID", "On every desktop", "In DNS"]'::jsonb, 1, 'Passwords are protected in the directory for authorised readers.'),
  ('ws-sec-02', 3, 'A key benefit of LAPS is…', '["Faster boot", "Unique, automatically rotated local admin passwords", "More RAM", "VLAN tagging"]'::jsonb, 1, 'Unique rotating passwords stop lateral movement via shared creds.'),
  ('ws-sec-03', 1, 'Defender Firewall profiles (Domain/Private/Public) exist to…', '["Confuse admins", "Apply different rules per network type", "Disable the firewall", "Store passwords"]'::jsonb, 1, 'Profiles tailor rules to the connected network.'),
  ('ws-sec-03', 2, 'A secure default firewall stance is…', '["Allow all inbound", "Default-deny inbound, allow only what''s needed", "Block outbound only", "No rules"]'::jsonb, 1, 'Default-deny with explicit allows is the norm.'),
  ('ws-sec-03', 3, 'Broad antivirus exclusions are…', '["Recommended everywhere", "A risk that can hide malware", "Required for updates", "Encryption"]'::jsonb, 1, 'Excessive exclusions create blind spots for malware.'),
  ('ws-sec-04', 1, 'BitLocker protects…', '["Data in transit", "Data at rest on a volume", "DNS records", "Nothing"]'::jsonb, 1, 'BitLocker encrypts volumes so a stolen disk is unreadable.'),
  ('ws-sec-04', 2, 'Credential Guard defends against…', '["Slow disks", "Credential theft from memory (e.g. pass-the-hash)", "DNS poisoning", "Full drives"]'::jsonb, 1, 'It isolates secrets using virtualization-based security.'),
  ('ws-sec-04', 3, 'BitLocker recovery keys should be…', '["Written on the server", "Escrowed in Active Directory", "Emailed to users", "Deleted"]'::jsonb, 1, 'Escrow keys in AD so admins can recover volumes.'),
  ('ws-sec-05', 1, 'Most breaches exploit…', '["Zero-days only", "Known, already-patched vulnerabilities", "Strong passwords", "Encrypted data"]'::jsonb, 1, 'Timely patching closes the known holes attackers use most.'),
  ('ws-sec-05', 2, 'WSUS is used to…', '["Sign DNS zones", "Approve and distribute Microsoft updates internally", "Encrypt disks", "Assign IPs"]'::jsonb, 1, 'WSUS centralises update approval and delivery.'),
  ('ws-sec-05', 3, 'A safe patch process includes…', '["Patching all servers at once with no testing", "A test ring, maintenance windows, and compliance tracking", "Never rebooting", "Disabling updates"]'::jsonb, 1, 'Rings, windows, and reporting reduce risk.'),
  ('ws-sec-06', 1, 'Audit policy is best configured through…', '["The BIOS", "Group Policy", "DNS", "DHCP"]'::jsonb, 1, 'Advanced audit policy is deployed via Group Policy.'),
  ('ws-sec-06', 2, 'For correlation across many servers, forward events to…', '["A single text file", "A SIEM / Windows Event Forwarding", "the pagefile", "DNS"]'::jsonb, 1, 'Central collection enables correlation and alerting.'),
  ('ws-sec-06', 3, 'A high-signal event worth alerting on is…', '["A successful ping", "A user added to a privileged group", "A screen unlock", "A DNS query"]'::jsonb, 1, 'Privileged group changes are security-relevant.'),
  ('ws-sec-07', 1, 'A basic hardening step is to…', '["Enable SMBv1", "Remove/disable legacy protocols like SMBv1", "Open all ports", "Share admin passwords"]'::jsonb, 1, 'SMBv1 is obsolete and insecure — remove it.'),
  ('ws-sec-07', 2, 'The best way to apply consistent hardening is…', '["Manually per server", "Microsoft Security Baselines as GPOs", "Random settings", "Disabling logging"]'::jsonb, 1, 'Baselines give vetted, repeatable configuration.'),
  ('ws-sec-07', 3, 'Preferring Kerberos and limiting NTLM helps because…', '["NTLM is faster", "NTLM is weaker and abused in credential attacks", "Kerberos needs no DNS", "NTLM encrypts disks"]'::jsonb, 1, 'Reducing NTLM cuts exposure to credential-relay/theft attacks.'),
  ('ws-ps-01', 1, 'PowerShell cmdlets follow which naming pattern?', '["Noun.Verb", "Verb-Noun", "all lowercase", "random"]'::jsonb, 1, 'Cmdlets use Verb-Noun, e.g. Get-Service.'),
  ('ws-ps-01', 2, 'Which cmdlet shows an object''s properties and methods?', '["Get-Help", "Get-Member", "Get-Date", "Write-Host"]'::jsonb, 1, 'Get-Member inspects the pipeline object''s members.'),
  ('ws-ps-01', 3, 'PowerShell pipelines pass…', '["Plain text", "Objects", "Bytes only", "Files"]'::jsonb, 1, 'Objects flow through the pipeline, enabling property-based work.'),
  ('ws-ps-02', 1, 'Which cmdlet filters objects by a condition?', '["Select-Object", "Where-Object", "Format-Table", "Get-Help"]'::jsonb, 1, 'Where-Object filters on a property test.'),
  ('ws-ps-02', 2, '$_ in a pipeline refers to…', '["the script file", "the current pipeline object", "the host name", "the user"]'::jsonb, 1, '$_ is the current object flowing through the pipeline.'),
  ('ws-ps-02', 3, 'Format-* cmdlets should be placed…', '["First", "In the middle", "At the very end (display only)", "Never used"]'::jsonb, 2, 'Formatting is for output; keep it last.'),
  ('ws-ps-03', 1, 'Which cmdlet installs a server role?', '["Get-Service", "Install-WindowsFeature", "Format-Table", "Set-Location"]'::jsonb, 1, 'Install-WindowsFeature adds roles/features.'),
  ('ws-ps-03', 2, 'An efficient way to query event logs is…', '["Notepad", "Get-WinEvent", "ping", "chkdsk"]'::jsonb, 1, 'Get-WinEvent queries the Windows event logs.'),
  ('ws-ps-03', 3, 'Scripting a change across servers helps because it is…', '["Slower", "Consistent and self-documenting", "Riskier than clicking", "Untraceable"]'::jsonb, 1, 'Scripts apply identical, repeatable, documented changes.'),
  ('ws-ps-04', 1, 'Which cmdlet runs a scriptblock on remote computers?', '["Invoke-Command", "Get-Date", "Write-Host", "Sort-Object"]'::jsonb, 0, 'Invoke-Command executes remotely, optionally in parallel.'),
  ('ws-ps-04', 2, 'PowerShell remoting relies on which protocol?', '["FTP", "WinRM", "SMTP", "Telnet"]'::jsonb, 1, 'WinRM underpins PowerShell remoting.'),
  ('ws-ps-04', 3, 'A persistent reusable connection is created with…', '["New-PSSession", "Format-List", "Get-Help", "Stop-Service"]'::jsonb, 0, 'New-PSSession creates a reusable remoting session.'),
  ('ws-ps-05', 1, 'Which cmdlet reads a CSV to drive bulk changes?', '["Import-Csv", "Get-Member", "Format-Table", "Get-Help"]'::jsonb, 0, 'Import-Csv turns spreadsheet rows into objects to process.'),
  ('ws-ps-05', 2, 'Before a bulk change, you should test with…', '["-Force", "-WhatIf", "-Verbose only", "nothing"]'::jsonb, 1, '-WhatIf previews changes without applying them.'),
  ('ws-ps-05', 3, 'Robust scripts handle failures with…', '["No handling", "try/catch and -ErrorAction Stop", "reboots", "Format-List"]'::jsonb, 1, 'try/catch plus -ErrorAction Stop catches and manages errors.'),
  ('ws-ps-06', 1, 'Exporting results to a spreadsheet uses…', '["Export-Csv", "Write-Host", "Get-Help", "Stop-Process"]'::jsonb, 0, 'Export-Csv writes objects to CSV.'),
  ('ws-ps-06', 2, 'Running a script unattended on a schedule uses…', '["Task Scheduler / scheduled jobs", "Paint", "Notepad", "DNS Manager"]'::jsonb, 0, 'Task Scheduler runs scripts on a schedule.'),
  ('ws-ps-06', 3, 'Desired State Configuration (DSC) is best described as…', '["A backup tool", "Declarative configuration that corrects drift", "A firewall", "A hypervisor"]'::jsonb, 1, 'DSC enforces a declared desired state, fixing drift.'),
  ('ws-bk-01', 1, 'An incremental backup captures…', '["Everything", "Changes since the last backup of any type", "Changes since the last full", "Nothing"]'::jsonb, 1, 'Incrementals store changes since the previous backup; restores chain them.'),
  ('ws-bk-01', 2, 'The 3-2-1 rule means…', '["3 copies on 1 disk", "3 copies, 2 media types, 1 offsite", "2 copies only", "1 copy in 3 folders"]'::jsonb, 1, 'Three copies, two media, one offsite.'),
  ('ws-bk-01', 3, 'RPO defines…', '["Recovery speed", "How much data you can afford to lose", "Disk size", "Network speed"]'::jsonb, 1, 'RPO is the acceptable data-loss window; RTO is recovery time.'),
  ('ws-bk-02', 1, 'On a domain controller, System State backup includes…', '["Only the pagefile", "Active Directory", "User documents only", "Nothing"]'::jsonb, 1, 'System State on a DC captures AD (NTDS.dit, SYSVOL, etc.).'),
  ('ws-bk-02', 2, 'A bare-metal recovery backup lets you…', '["Restore one file", "Rebuild the entire server onto new hardware", "Reset a password", "Assign an IP"]'::jsonb, 1, 'BMR restores the whole system image.'),
  ('ws-bk-02', 3, 'Windows Server Backup can target…', '["Only tape", "A dedicated disk or network share", "Only the C: drive it backs up", "DNS"]'::jsonb, 1, 'WSB writes to a dedicated disk or a network share.'),
  ('ws-bk-03', 1, 'An untested backup…', '["Is fully reliable", "Isn''t proven until a restore succeeds", "Restores faster", "Needs no storage"]'::jsonb, 1, 'Only a successful restore proves a backup.'),
  ('ws-bk-03', 2, 'To recover deleted AD objects across the domain you can use…', '["DSRM authoritative restore or AD Recycle Bin", "gpupdate", "nslookup", "chkdsk"]'::jsonb, 0, 'DSRM authoritative restore (or the Recycle Bin) recovers AD objects.'),
  ('ws-bk-03', 3, 'Bare-metal recovery is used when…', '["A single file is lost", "An entire server must be rebuilt", "A password is forgotten", "DNS is slow"]'::jsonb, 1, 'BMR rebuilds a whole failed server from an image.'),
  ('ws-bk-04', 1, 'Failover clustering provides…', '["Faster CPUs", "Automatic workload takeover if a node fails", "Encryption", "DNS"]'::jsonb, 1, 'Clustering restarts roles on a surviving node for HA.'),
  ('ws-bk-04', 2, 'Quorum exists to…', '["Speed backups", "Decide how many nodes must be up (avoid split-brain)", "Assign IPs", "Sign DNS"]'::jsonb, 1, 'Quorum keeps the cluster consistent and prevents split-brain.'),
  ('ws-bk-04', 3, 'Cluster nodes typically require…', '["No storage", "Shared storage and reliable inter-node networking", "A single disk each", "Wi-Fi only"]'::jsonb, 1, 'Shared storage and good networking are core requirements.'),
  ('ws-bk-05', 1, 'Disaster recovery (vs high availability) addresses…', '["A single failed node", "Loss of a whole site", "A slow disk", "A forgotten password"]'::jsonb, 1, 'DR covers site-level loss; HA covers node-level failure.'),
  ('ws-bk-05', 2, 'RPO and RTO should be…', '["Chosen by IT alone", "Agreed with the business per service", "Ignored", "Always zero"]'::jsonb, 1, 'The business sets acceptable loss/recovery targets.'),
  ('ws-bk-05', 3, 'A DR plan is only trustworthy if it is…', '["Long", "Regularly tested with drills", "Encrypted", "Printed"]'::jsonb, 1, 'Untested DR plans tend to fail in a real event.'),
  ('ws-fnd-01', 1, 'Which edition gives unlimited virtualization rights for dense hosts?', '["Standard", "Datacenter", "Essentials", "Core"]'::jsonb, 1, 'Datacenter suits highly virtualized hosts with unlimited VM rights.'),
  ('ws-fnd-01', 2, 'Windows Server is primarily licensed…', '["Per user only", "Per physical core (plus CALs)", "Per gigabyte", "Free forever"]'::jsonb, 1, 'Core-based licensing plus CALs for connecting users/devices.'),
  ('ws-fnd-01', 3, 'Client Access Licenses (CALs) are required for…', '["The server hardware", "Users or devices connecting to the server", "DNS", "The BIOS"]'::jsonb, 1, 'CALs cover the users/devices that access the server.'),
  ('ws-fnd-02', 1, 'Server Core''s main advantages are…', '["A nicer GUI", "Smaller footprint, fewer updates, smaller attack surface", "More games", "Slower boot"]'::jsonb, 1, 'No desktop shell means less to patch and attack.'),
  ('ws-fnd-02', 2, 'On Server Core, quick local configuration is done with…', '["Paint", "sconfig and PowerShell", "Only the BIOS", "DNS Manager"]'::jsonb, 1, 'sconfig and PowerShell configure a headless server locally.'),
  ('ws-fnd-02', 3, 'Server Core is a good fit for…', '["Nothing", "Infrastructure roles like DC/DNS/Hyper-V", "Only desktops", "Only databases"]'::jsonb, 1, 'Its reduced surface suits core infrastructure roles.'),
  ('ws-fnd-03', 1, 'Infrastructure servers should use…', '["DHCP addresses", "Static IP addresses", "No IP", "IPv6 only"]'::jsonb, 1, 'DCs/DNS/DHCP need stable static addresses.'),
  ('ws-fnd-03', 2, 'A member server''s DNS should point to…', '["A public resolver", "A domain controller/internal DNS", "Itself only", "Nothing"]'::jsonb, 1, 'Domain members must resolve via internal DNS to find the domain.'),
  ('ws-fnd-03', 3, 'Roles should be installed…', '["Before naming/networking", "After the basic identity and network setup", "Never", "Only on Core"]'::jsonb, 1, 'Get identity and networking right first, then add roles.'),
  ('ws-fnd-04', 1, 'Windows Admin Center is…', '["A BIOS tool", "A browser-based central management tool", "A backup format", "A DNS record"]'::jsonb, 1, 'WAC manages servers/clusters from a web UI.'),
  ('ws-fnd-04', 2, 'Server Manager can manage…', '["Only the local server", "Local and remote servers in pools", "Only Server Core", "Only DNS"]'::jsonb, 1, 'It manages groups of local and remote servers.'),
  ('ws-fnd-04', 3, 'Best practice for day-to-day admin is to…', '["Log on to each server console", "Manage remotely with WAC/RSAT", "Disable management", "Use only the BIOS"]'::jsonb, 1, 'Remote management reduces risk and saves time.'),
  ('ws-fnd-05', 1, 'A ''role'' in Windows Server is…', '["A user account", "A primary server function like DNS or AD DS", "A firewall rule", "A backup"]'::jsonb, 1, 'Roles define the server''s main function.'),
  ('ws-fnd-05', 2, 'Which cmdlet installs roles and features?', '["Get-Help", "Install-WindowsFeature", "Format-Table", "Restart-Service"]'::jsonb, 1, 'Install-WindowsFeature adds roles/features.'),
  ('ws-fnd-05', 3, 'Installing only needed roles…', '["Slows the server", "Reduces patching and attack surface", "Breaks DNS", "Is impossible"]'::jsonb, 1, 'Fewer roles means less to maintain and secure.'),
  ('ws-fnd-06', 1, 'Sysprep is used to…', '["Encrypt a disk", "Generalise an image (remove unique SIDs) before capture", "Assign IPs", "Sign DNS"]'::jsonb, 1, 'Sysprep prepares an image for reuse by removing machine-specific identity.'),
  ('ws-fnd-06', 2, 'An unattended install is driven by…', '["A phone call", "An answer file (unattend.xml)", "the BIOS beep", "DNS"]'::jsonb, 1, 'Answer files automate Windows setup.'),
  ('ws-fnd-06', 3, 'Deploying identical images helps because it…', '["Creates snowflakes", "Makes behaviour predictable and troubleshooting easier", "Slows deployment", "Breaks licensing"]'::jsonb, 1, 'Standard builds are predictable and easier to support.'),
  ('ws-ras-01', 1, 'Infrastructure servers should point DNS at…', '["A public resolver", "Internal domain controllers", "Themselves only", "The router"]'::jsonb, 1, 'Domain members resolve via internal DNS to reach the domain.'),
  ('ws-ras-01', 2, 'NIC teaming provides…', '["Encryption", "Bandwidth aggregation and failover", "DNS records", "A firewall"]'::jsonb, 1, 'Teaming aggregates NICs and survives a link failure.'),
  ('ws-ras-01', 3, 'Which cmdlet tests reachability to a specific port?', '["Get-Help", "Test-NetConnection", "Format-List", "Stop-Service"]'::jsonb, 1, 'Test-NetConnection checks host and port connectivity.'),
  ('ws-ras-02', 1, 'A site-to-site VPN connects…', '["One user", "Two whole networks", "Only DNS", "Nothing"]'::jsonb, 1, 'Site-to-site links entire networks together.'),
  ('ws-ras-02', 2, 'SSTP is often chosen because it…', '["Needs no encryption", "Works over 443 and is firewall-friendly", "Is unencrypted", "Requires Linux"]'::jsonb, 1, 'SSTP tunnels over TCP 443, easing firewall traversal.'),
  ('ws-ras-02', 3, 'The Windows role that provides VPN/routing is…', '["DNS", "RRAS", "WSUS", "FSRM"]'::jsonb, 1, 'Routing and Remote Access (RRAS) provides VPN and routing.'),
  ('ws-ras-03', 1, 'NPS is Microsoft''s implementation of…', '["DNS", "RADIUS", "DHCP", "DFS"]'::jsonb, 1, 'NPS provides RADIUS authentication/authorisation.'),
  ('ws-ras-03', 2, 'WPA2/3-Enterprise Wi-Fi commonly uses NPS to…', '["Assign IPs", "Authenticate users against Active Directory", "Encrypt disks", "Replicate DNS"]'::jsonb, 1, 'NPS authenticates enterprise Wi-Fi against AD.'),
  ('ws-ras-03', 3, 'RADIUS ''accounting'' refers to…', '["Billing only", "Logging of access sessions", "Encryption", "Routing"]'::jsonb, 1, 'Accounting logs who connected and when.'),
  ('ws-ras-04', 1, 'Always On VPN''s key user benefit is…', '["Manual reconnection", "Automatic, transparent connectivity", "No encryption", "Slower access"]'::jsonb, 1, 'It connects automatically without user action.'),
  ('ws-ras-04', 2, 'Always On VPN is the modern replacement for…', '["RRAS", "DirectAccess", "DNS", "DHCP"]'::jsonb, 1, 'It supersedes the legacy DirectAccess feature.'),
  ('ws-ras-04', 3, 'Always On VPN is typically deployed via…', '["Floppy disk", "Intune/MDM or scripts", "the BIOS", "DNS zones"]'::jsonb, 1, 'Configuration is pushed through MDM/Intune or scripting.'),
  ('ws-ras-05', 1, 'Which RDS role secures access from the internet over HTTPS?', '["Session Host", "RD Gateway", "Connection Broker", "Web Access"]'::jsonb, 1, 'RD Gateway tunnels RDP over HTTPS for secure external access.'),
  ('ws-ras-05', 2, 'RDS requires which extra licensing?', '["None", "RD CALs (per user/device)", "DNS CALs", "BitLocker keys"]'::jsonb, 1, 'RD CALs are needed on top of Windows Server CALs.'),
  ('ws-ras-05', 3, 'Exposing raw RDP to the internet is…', '["Recommended", "A serious risk \u2014 use RD Gateway + MFA", "Required", "Encrypted by default"]'::jsonb, 1, 'Direct RDP exposure is dangerous; front it with RD Gateway and MFA.'),
  ('ws-mon-01', 1, 'Which Windows log records service and driver events?', '["Security", "System", "Setup", "Web"]'::jsonb, 1, 'The System log holds OS/service/driver events.'),
  ('ws-mon-01', 2, 'A Custom View lets you…', '["Encrypt logs", "Filter events across logs by criteria", "Delete the OS", "Assign IPs"]'::jsonb, 1, 'Custom Views filter to the events you care about.'),
  ('ws-mon-01', 3, 'To centralise logs from many servers you use…', '["A text file", "Event forwarding / a SIEM", "the BIOS", "DNS"]'::jsonb, 1, 'Event forwarding collects logs centrally for correlation.'),
  ('ws-mon-02', 1, 'A performance baseline is used to…', '["Encrypt data", "Know what ''normal'' looks like to spot abnormalities", "Assign IPs", "Replicate DNS"]'::jsonb, 1, 'Baselines define normal so anomalies stand out.'),
  ('ws-mon-02', 2, 'Sustained high disk queue length usually indicates…', '["A CPU issue", "A disk/storage bottleneck", "A DNS error", "A firewall block"]'::jsonb, 1, 'Long disk queues point to storage as the bottleneck.'),
  ('ws-mon-02', 3, 'Long-term counter capture uses…', '["Data Collector Sets", "Notepad", "ping", "gpupdate"]'::jsonb, 0, 'Data Collector Sets record counters over time.'),
  ('ws-mon-03', 1, 'To make a service restart automatically after a crash you configure…', '["Its icon", "Recovery actions", "DNS", "A GPO link"]'::jsonb, 1, 'Service Recovery actions can restart it on failure.'),
  ('ws-mon-03', 2, 'A service that won''t start often has a…', '["Failed dependency", "Slow GPU", "Missing wallpaper", "DNS scavenging issue"]'::jsonb, 0, 'Check dependencies and the System log when a service won''t start.'),
  ('ws-mon-03', 3, 'Which tool shows real-time per-process resource use?', '["Resource Monitor / Task Manager", "nslookup", "repadmin", "chkdsk"]'::jsonb, 0, 'Task Manager/Resource Monitor show live process resource usage.'),
  ('ws-mon-04', 1, 'After forming a theory of cause you should…', '["Change many things at once", "Test it by changing one thing at a time", "Reboot everything", "Ignore logs"]'::jsonb, 1, 'Test one variable at a time to isolate the cause.'),
  ('ws-mon-04', 2, 'The final troubleshooting step is to…', '["Forget it", "Document the cause and resolution", "Delete logs", "Reinstall Windows"]'::jsonb, 1, 'Documenting closes the loop and helps next time.'),
  ('ws-mon-04', 3, 'Good isolation asks…', '["Nothing", "Is it one server/user or many, and what changed?", "Only the CPU model", "The wallpaper"]'::jsonb, 1, 'Scope and recent-change questions localise the fault.'),
  ('ws-mon-05', 1, 'Sudden ''random'' authentication failures on domain members often trace to…', '["Wallpaper", "Large clock drift breaking Kerberos", "A fast CPU", "DNS scavenging off"]'::jsonb, 1, 'Kerberos fails when clocks drift too far — check time sync.'),
  ('ws-mon-05', 2, 'A volume filling up is commonly caused by…', '["Too little RAM", "Logs, updates, or shadow copies", "A fast NIC", "A new mouse"]'::jsonb, 1, 'Runaway logs/updates/shadow copies fill disks.'),
  ('ws-mon-05', 3, 'After resolving an incident you should…', '["Do nothing", "Add monitoring/alerting for that condition", "Delete the logs", "Disable the service"]'::jsonb, 1, 'Alerting catches the issue earlier next time.');
