-- 0032_seed_networking_lessons.sql — P19 Networking expansion (curriculum_lessons XP authority). Idempotent.
insert into public.curriculum_lessons (id, slug, title, track, xp, sort_order) values
  ('nw-fund-01', 'what-is-a-network', 'What Is a Network?', 'sysadmin', 60, 3001),
  ('nw-fund-02', 'osi-model', 'The OSI Model', 'sysadmin', 75, 3002),
  ('nw-fund-03', 'tcp-ip-encapsulation', 'TCP/IP & Encapsulation', 'sysadmin', 80, 3003),
  ('nw-fund-04', 'protocols-ports', 'Protocols & Ports', 'sysadmin', 75, 3004),
  ('nw-fund-05', 'cabling-media', 'Cabling & Media', 'sysadmin', 70, 3005),
  ('nw-ip-01', 'ipv4-basics', 'IPv4 Addressing Basics', 'sysadmin', 75, 3006),
  ('nw-ip-02', 'subnet-masks-cidr', 'Subnet Masks & CIDR', 'sysadmin', 85, 3007),
  ('nw-ip-03', 'subnetting', 'Subnetting: Splitting a Network', 'sysadmin', 90, 3008),
  ('nw-ip-04', 'subnetting-practice', 'Subnetting Practice', 'sysadmin', 90, 3009),
  ('nw-ip-05', 'vlsm', 'VLSM: Variable-Length Subnet Masks', 'sysadmin', 85, 3010),
  ('nw-ip-06', 'addressing-scheme', 'Planning an Addressing Scheme', 'sysadmin', 80, 3011),
  ('nw-ip6-01', 'ipv6-addressing', 'Why IPv6 & Addressing', 'sysadmin', 80, 3012),
  ('nw-ip6-02', 'ipv6-types-slaac', 'Address Types & SLAAC', 'sysadmin', 80, 3013),
  ('nw-ip6-03', 'ipv6-transition', 'IPv6 Transition & Coexistence', 'sysadmin', 75, 3014),
  ('nw-sw-01', 'ethernet-mac', 'Ethernet & MAC Addressing', 'sysadmin', 80, 3015),
  ('nw-sw-02', 'vlans', 'VLANs', 'sysadmin', 90, 3016),
  ('nw-sw-03', 'trunking', 'Trunking (802.1Q)', 'sysadmin', 85, 3017),
  ('nw-sw-04', 'spanning-tree', 'Spanning Tree Protocol', 'sysadmin', 85, 3018),
  ('nw-sw-05', 'port-security', 'Port Security & Switch Hardening', 'sysadmin', 85, 3019),
  ('nw-rt-01', 'routing-concepts', 'Routing Concepts', 'sysadmin', 85, 3020),
  ('nw-rt-02', 'static-routing', 'Static Routing', 'sysadmin', 80, 3021),
  ('nw-rt-03', 'dynamic-routing', 'Dynamic Routing', 'sysadmin', 85, 3022),
  ('nw-rt-04', 'inter-vlan', 'Inter-VLAN Routing', 'sysadmin', 85, 3023),
  ('nw-rt-05', 'nat-pat', 'NAT & PAT', 'sysadmin', 85, 3024),
  ('nw-wifi-01', 'standards-bands', 'Wi-Fi Standards & Bands', 'sysadmin', 75, 3025),
  ('nw-wifi-02', 'wireless-security', 'Wireless Security', 'sysadmin', 80, 3026),
  ('nw-wifi-03', 'wireless-design', 'Wireless Design & Troubleshooting', 'sysadmin', 80, 3027),
  ('nw-sec-01', 'firewalls-acls', 'Firewalls & ACLs', 'sysadmin', 85, 3028),
  ('nw-sec-02', 'vpns-ipsec', 'VPNs & IPsec', 'sysadmin', 85, 3029),
  ('nw-sec-03', 'segmentation-zero-trust', 'Segmentation & Zero Trust', 'sysadmin', 85, 3030),
  ('nw-sec-04', 'dhcp-dns-network', 'DHCP & DNS on the Network', 'sysadmin', 80, 3031),
  ('nw-tsh-01', 'cli-tools', 'Essential CLI Tools', 'sysadmin', 85, 3032),
  ('nw-tsh-02', 'method', 'A Troubleshooting Method', 'sysadmin', 85, 3033),
  ('nw-tsh-03', 'packet-analysis', 'Packet Analysis', 'sysadmin', 85, 3034),
  ('nw-tsh-04', 'monitoring', 'Monitoring at Scale', 'sysadmin', 80, 3035)
on conflict (id) do update set slug=excluded.slug, title=excluded.title, track=excluded.track, xp=excluded.xp, sort_order=excluded.sort_order;
