-- 0033_seed_networking_quizzes.sql — P19 Networking quizzes. Idempotent.
insert into public.lesson_quizzes (lesson_id, pass_pct, bonus_xp) values
  ('nw-fund-01', 70, 30),
  ('nw-fund-02', 70, 30),
  ('nw-fund-03', 70, 30),
  ('nw-fund-04', 70, 30),
  ('nw-fund-05', 70, 30),
  ('nw-ip-01', 70, 30),
  ('nw-ip-02', 70, 30),
  ('nw-ip-03', 70, 30),
  ('nw-ip-04', 70, 30),
  ('nw-ip-05', 70, 30),
  ('nw-ip-06', 70, 30),
  ('nw-ip6-01', 70, 30),
  ('nw-ip6-02', 70, 30),
  ('nw-ip6-03', 70, 30),
  ('nw-sw-01', 70, 30),
  ('nw-sw-02', 70, 30),
  ('nw-sw-03', 70, 30),
  ('nw-sw-04', 70, 30),
  ('nw-sw-05', 70, 30),
  ('nw-rt-01', 70, 30),
  ('nw-rt-02', 70, 30),
  ('nw-rt-03', 70, 30),
  ('nw-rt-04', 70, 30),
  ('nw-rt-05', 70, 30),
  ('nw-wifi-01', 70, 30),
  ('nw-wifi-02', 70, 30),
  ('nw-wifi-03', 70, 30),
  ('nw-sec-01', 70, 30),
  ('nw-sec-02', 70, 30),
  ('nw-sec-03', 70, 30),
  ('nw-sec-04', 70, 30),
  ('nw-tsh-01', 70, 30),
  ('nw-tsh-02', 70, 30),
  ('nw-tsh-03', 70, 30),
  ('nw-tsh-04', 70, 30)
on conflict (lesson_id) do update set pass_pct=excluded.pass_pct, bonus_xp=excluded.bonus_xp;

delete from public.quiz_questions where lesson_id in ('nw-fund-01', 'nw-fund-02', 'nw-fund-03', 'nw-fund-04', 'nw-fund-05', 'nw-ip-01', 'nw-ip-02', 'nw-ip-03', 'nw-ip-04', 'nw-ip-05', 'nw-ip-06', 'nw-ip6-01', 'nw-ip6-02', 'nw-ip6-03', 'nw-sw-01', 'nw-sw-02', 'nw-sw-03', 'nw-sw-04', 'nw-sw-05', 'nw-rt-01', 'nw-rt-02', 'nw-rt-03', 'nw-rt-04', 'nw-rt-05', 'nw-wifi-01', 'nw-wifi-02', 'nw-wifi-03', 'nw-sec-01', 'nw-sec-02', 'nw-sec-03', 'nw-sec-04', 'nw-tsh-01', 'nw-tsh-02', 'nw-tsh-03', 'nw-tsh-04');

insert into public.quiz_questions (lesson_id, sort, prompt, options, correct_index, explanation) values
  ('nw-fund-01', 1, 'The internet is best described as…', '["A LAN", "The world''s largest WAN", "A PAN", "A bus topology"]'::jsonb, 1, 'The internet is a global wide area network (WAN).'),
  ('nw-fund-01', 2, 'In a star topology, devices connect to…', '["Each other directly", "A central switch", "A ring", "A single bus cable"]'::jsonb, 1, 'Star topologies centre on a switch; the modern default.'),
  ('nw-fund-01', 3, 'A device that both requests and provides resources is…', '["A server only", "A peer", "A client only", "A router"]'::jsonb, 1, 'Peer-to-peer devices act as both client and server.'),
  ('nw-fund-02', 1, 'Routing and IP addressing happen at which OSI layer?', '["2 Data Link", "3 Network", "4 Transport", "7 Application"]'::jsonb, 1, 'Layer 3 (Network) handles logical addressing and routing.'),
  ('nw-fund-02', 2, 'MAC addresses and switching operate at layer…', '["1", "2", "3", "4"]'::jsonb, 1, 'Layer 2 (Data Link) uses MAC addresses; switches work here.'),
  ('nw-fund-02', 3, 'The data unit at the Transport layer is a…', '["Frame", "Packet", "Segment", "Bit"]'::jsonb, 2, 'Layer 4 works with segments (TCP) / datagrams (UDP).'),
  ('nw-fund-03', 1, 'Encapsulation means each layer…', '["Removes a header", "Adds its own header as data moves down", "Encrypts everything", "Deletes data"]'::jsonb, 1, 'Each layer prepends its header on the way down the stack.'),
  ('nw-fund-03', 2, 'A router makes forwarding decisions using the…', '["Frame/MAC header", "IP header", "TCP payload", "Physical bits"]'::jsonb, 1, 'Routers read the layer-3 IP header to route packets.'),
  ('nw-fund-03', 3, 'The TCP/IP model has how many layers?', '["Seven", "Five", "Four", "Three"]'::jsonb, 2, 'The TCP/IP model is commonly described as four layers.'),
  ('nw-fund-04', 1, 'Which transport protocol is reliable and connection-oriented?', '["UDP", "TCP", "ICMP", "ARP"]'::jsonb, 1, 'TCP provides reliable, ordered, connection-oriented delivery.'),
  ('nw-fund-04', 2, 'HTTPS uses which port by default?', '["80", "22", "443", "3389"]'::jsonb, 2, 'HTTPS uses TCP port 443.'),
  ('nw-fund-04', 3, 'DNS queries typically use which transport for speed?', '["TCP only", "UDP (with TCP fallback)", "FTP", "RDP"]'::jsonb, 1, 'DNS uses UDP/53 for most queries, with TCP for large responses/zone transfers.'),
  ('nw-fund-05', 1, 'The practical maximum run for twisted-pair copper is about…', '["10 m", "100 m", "1 km", "unlimited"]'::jsonb, 1, 'Twisted-pair Ethernet runs are limited to roughly 100 m.'),
  ('nw-fund-05', 2, 'For a long-distance campus backbone you''d choose…', '["Cat5e", "Single-mode fiber", "Coax", "A crossover cable"]'::jsonb, 1, 'Single-mode fiber covers long distances.'),
  ('nw-fund-05', 3, 'Auto-MDIX means…', '["Cables never fail", "Devices auto-detect straight-through vs crossover", "Fiber is unnecessary", "Ports run faster"]'::jsonb, 1, 'Auto-MDIX removes the need to pick crossover vs straight-through.'),
  ('nw-ip-01', 1, 'An IPv4 address is how many bits?', '["16", "32", "48", "64"]'::jsonb, 1, 'IPv4 addresses are 32 bits (four octets).'),
  ('nw-ip-01', 2, 'Which is a private (RFC 1918) range?', '["8.0.0.0/8", "172.16.0.0/12", "1.1.1.0/24", "100.0.0.0/8"]'::jsonb, 1, '172.16.0.0/12 is private; 10/8 and 192.168/16 are the others.'),
  ('nw-ip-01', 3, 'The network address of a subnet has all host bits set to…', '["1", "0", "255", "random"]'::jsonb, 1, 'All host bits 0 = the network address; all 1 = broadcast.'),
  ('nw-ip-02', 1, 'A /24 network provides how many usable hosts?', '["256", "254", "128", "64"]'::jsonb, 1, '256 addresses minus network and broadcast = 254 usable.'),
  ('nw-ip-02', 2, 'The mask 255.255.255.224 corresponds to which prefix?', '["/25", "/26", "/27", "/28"]'::jsonb, 2, '224 = 11100000, 27 network bits → /27.'),
  ('nw-ip-02', 3, 'Usable hosts per subnet is calculated as…', '["2^host bits", "2^host bits \u2212 2", "2^network bits", "host bits \u00d7 2"]'::jsonb, 1, 'Subtract network and broadcast addresses.'),
  ('nw-ip-03', 1, 'Borrowing one more host bit for subnets…', '["Doubles subnets, halves hosts", "Halves subnets", "Adds no subnets", "Doubles hosts"]'::jsonb, 0, 'Each borrowed bit doubles subnets and halves hosts per subnet.'),
  ('nw-ip-03', 2, 'For a /27, the block size in the last octet is…', '["8", "16", "32", "64"]'::jsonb, 2, '256 − 224 = 32.'),
  ('nw-ip-03', 3, '192.168.10.37/27 belongs to which network?', '["192.168.10.0", "192.168.10.32", "192.168.10.37", "192.168.10.64"]'::jsonb, 1, 'Block size 32; .37 falls in the .32 subnet.'),
  ('nw-ip-04', 1, '172.16.5.200/28 has which broadcast address?', '["172.16.5.191", "172.16.5.207", "172.16.5.223", "172.16.5.255"]'::jsonb, 1, 'Block size 16; .200 is in .192, broadcast = .207.'),
  ('nw-ip-04', 2, 'A /30 subnet provides how many usable hosts?', '["1", "2", "4", "6"]'::jsonb, 1, '/30 = 4 addresses − 2 = 2 usable (ideal for point-to-point links).'),
  ('nw-ip-04', 3, 'The last usable host in 10.0.5.130/25 is…', '["10.0.5.254", "10.0.5.255", "10.0.5.128", "10.0.5.126"]'::jsonb, 0, 'Network .128, broadcast .255, so last usable is .254.'),
  ('nw-ip-05', 1, 'VLSM is used to…', '["Use one mask everywhere", "Right-size each subnet to its host need", "Disable subnetting", "Assign public IPs"]'::jsonb, 1, 'VLSM fits the mask to each subnet, reducing waste.'),
  ('nw-ip-05', 2, 'When applying VLSM you allocate…', '["Smallest need first", "Largest need first", "Randomly", "Only /24s"]'::jsonb, 1, 'Allocate largest-to-smallest to avoid fragmentation.'),
  ('nw-ip-05', 3, 'A 2-host point-to-point link is best served by a…', '["/24", "/28", "/30", "/26"]'::jsonb, 2, '/30 gives exactly two usable hosts.'),
  ('nw-ip-06', 1, 'A good addressing scheme should…', '["Use every address immediately", "Leave headroom for growth and be documented", "Be random", "Avoid subnets"]'::jsonb, 1, 'Plan for growth and document it.'),
  ('nw-ip-06', 2, 'Summarisable (contiguous) allocation helps…', '["Waste addresses", "Keep routing tables small and simple", "Break DNS", "Slow switches"]'::jsonb, 1, 'Summarisation reduces routing complexity.'),
  ('nw-ip-06', 3, 'Encoding site/VLAN into the address makes it…', '["Slower", "Human-readable and easier to manage", "Insecure", "Non-routable"]'::jsonb, 1, 'Structured addressing conveys meaning to operators.'),
  ('nw-ip6-01', 1, 'An IPv6 address is how many bits?', '["32", "64", "128", "256"]'::jsonb, 2, 'IPv6 uses 128-bit addresses.'),
  ('nw-ip6-01', 2, 'The :: in an IPv6 address may appear…', '["Anywhere, multiple times", "Only once per address", "Never", "Twice"]'::jsonb, 1, 'A double colon compresses one run of zero groups, used once.'),
  ('nw-ip6-01', 3, 'IPv6 addresses are written in…', '["Decimal", "Hexadecimal", "Binary only", "Octal"]'::jsonb, 1, 'IPv6 uses hexadecimal groups separated by colons.'),
  ('nw-ip6-02', 1, 'A link-local IPv6 address starts with…', '["2001", "fe80", "ff00", "fc00"]'::jsonb, 1, 'Link-local addresses use fe80::/10.'),
  ('nw-ip6-02', 2, 'SLAAC allows a host to…', '["Only use DHCP", "Auto-configure its address from a router prefix", "Disable IPv6", "Assign MACs"]'::jsonb, 1, 'SLAAC builds an address from the advertised prefix, no DHCP needed.'),
  ('nw-ip6-02', 3, 'IPv6 replaces broadcast with…', '["Anycast only", "Multicast", "Unicast only", "ARP"]'::jsonb, 1, 'IPv6 uses multicast instead of broadcast.'),
  ('nw-ip6-03', 1, 'The preferred, simplest coexistence method is…', '["Tunneling", "Dual-stack", "NAT64", "Turning off IPv4"]'::jsonb, 1, 'Running both stacks (dual-stack) is the common approach.'),
  ('nw-ip6-03', 2, 'NAT64 is used to…', '["Speed IPv4", "Let IPv6-only hosts reach IPv4 services", "Assign MACs", "Encrypt traffic"]'::jsonb, 1, 'NAT64 translates between IPv6-only clients and IPv4 servers.'),
  ('nw-ip6-03', 3, 'Tunneling helps when…', '["Everything is IPv6", "IPv6 must cross an IPv4-only network", "DNS is down", "VLANs are used"]'::jsonb, 1, 'Tunnels carry IPv6 over IPv4-only paths.'),
  ('nw-sw-01', 1, 'A switch forwards frames based on…', '["IP addresses", "MAC addresses", "Port numbers", "Hostnames"]'::jsonb, 1, 'Switches use layer-2 MAC addresses.'),
  ('nw-sw-01', 2, 'When a switch doesn''t know the destination MAC it…', '["Drops the frame", "Floods it out all other ports", "Routes it", "Encrypts it"]'::jsonb, 1, 'Unknown-unicast frames are flooded until the MAC is learned.'),
  ('nw-sw-01', 3, 'ARP resolves…', '["MAC to IP", "IP to MAC on the local network", "Name to IP", "Port to service"]'::jsonb, 1, 'ARP finds the MAC for a known local IP.'),
  ('nw-sw-02', 1, 'Each VLAN is a separate…', '["Collision domain only", "Broadcast domain", "Physical switch", "IP host"]'::jsonb, 1, 'A VLAN is its own broadcast domain.'),
  ('nw-sw-02', 2, 'Devices in different VLANs communicate via…', '["Nothing needed", "A router (layer 3)", "A hub", "ARP only"]'::jsonb, 1, 'Inter-VLAN traffic must be routed.'),
  ('nw-sw-02', 3, 'An access port carries…', '["All VLANs", "A single VLAN to an end device", "Only trunk traffic", "No traffic"]'::jsonb, 1, 'Access ports belong to one VLAN for an end device.'),
  ('nw-sw-03', 1, '802.1Q trunks keep VLANs separate by…', '["Encrypting frames", "Inserting a VLAN tag in each frame", "Using more cables", "Slowing traffic"]'::jsonb, 1, 'The 802.1Q tag identifies each frame''s VLAN.'),
  ('nw-sw-03', 2, 'The native VLAN on a trunk is…', '["Tagged twice", "Sent untagged", "Always VLAN 20", "Encrypted"]'::jsonb, 1, 'Native-VLAN traffic is sent untagged; match both ends.'),
  ('nw-sw-03', 3, 'A trunk link is typically used for…', '["A single PC", "Switch-to-switch or switch-to-router links", "A printer", "A wireless client"]'::jsonb, 1, 'Trunks interconnect infrastructure carrying multiple VLANs.'),
  ('nw-sw-04', 1, 'Layer-2 loops are dangerous because frames…', '["Expire quickly", "Have no TTL and can circulate forever", "Are encrypted", "Are routed"]'::jsonb, 1, 'No TTL at layer 2 means loops cause broadcast storms.'),
  ('nw-sw-04', 2, 'Spanning Tree prevents loops by…', '["Encrypting frames", "Blocking redundant paths, leaving one active", "Adding VLANs", "Speeding CPUs"]'::jsonb, 1, 'STP blocks redundant links to keep a loop-free topology.'),
  ('nw-sw-04', 3, 'Which improves convergence and protects access ports?', '["Disabling STP", "RSTP with PortFast/BPDU Guard", "More loops", "Hubs"]'::jsonb, 1, 'RSTP plus PortFast/BPDU Guard is best practice.'),
  ('nw-sw-05', 1, 'Port security can…', '["Speed the CPU", "Limit MAC addresses per port and act on violations", "Add VLANs", "Encrypt frames"]'::jsonb, 1, 'It restricts MACs per port to stop rogue devices/flooding.'),
  ('nw-sw-05', 2, 'Which stops a rogue DHCP server on the access layer?', '["DHCP snooping", "STP", "NAT", "ARP"]'::jsonb, 0, 'DHCP snooping permits DHCP only from trusted ports.'),
  ('nw-sw-05', 3, 'Unused switch ports should be…', '["Left enabled in VLAN 1", "Disabled / placed in an unused VLAN", "Set as trunks", "Given public IPs"]'::jsonb, 1, 'Disabling unused ports reduces attack surface.'),
  ('nw-rt-01', 1, 'A router selects a route using…', '["Shortest cable", "Longest prefix (most specific) match", "Random choice", "MAC address"]'::jsonb, 1, 'Longest-prefix match picks the most specific route.'),
  ('nw-rt-01', 2, 'The default route is written as…', '["255.255.255.255", "0.0.0.0/0", "127.0.0.1", "::1"]'::jsonb, 1, '0.0.0.0/0 matches any destination not matched more specifically.'),
  ('nw-rt-01', 3, 'A host sends traffic for another subnet to its…', '["DNS server", "Default gateway", "Switch MAC", "Broadcast"]'::jsonb, 1, 'Off-subnet traffic goes to the default gateway (router).'),
  ('nw-rt-02', 1, 'Static routing is best for…', '["Huge dynamic networks", "Small or stub networks", "Replacing DNS", "VLAN tagging"]'::jsonb, 1, 'Static routes suit small/stub topologies.'),
  ('nw-rt-02', 2, 'A drawback of static routing is that it…', '["Uses lots of CPU", "Doesn''t adapt automatically to changes", "Needs DHCP", "Breaks NAT"]'::jsonb, 1, 'Static routes must be updated manually when the topology changes.'),
  ('nw-rt-02', 3, 'A route to 0.0.0.0/0 is a…', '["Host route", "Default route", "Broadcast", "Loopback"]'::jsonb, 1, '0.0.0.0/0 is the default route.'),
  ('nw-rt-03', 1, 'OSPF is which type of routing protocol?', '["Distance-vector", "Link-state", "Static", "Broadcast"]'::jsonb, 1, 'OSPF is a link-state interior gateway protocol.'),
  ('nw-rt-03', 2, 'Convergence refers to…', '["Encryption", "How fast routers agree after a topology change", "MAC learning", "NAT translation"]'::jsonb, 1, 'Convergence is the time to reach a consistent routing view.'),
  ('nw-rt-03', 3, 'The protocol that routes between organisations on the internet is…', '["RIP", "OSPF", "BGP", "ARP"]'::jsonb, 2, 'BGP is the internet''s inter-domain routing protocol.'),
  ('nw-rt-04', 1, 'Router-on-a-stick routes VLANs using…', '["Multiple cables per VLAN", "Sub-interfaces on one trunk", "A hub", "DNS"]'::jsonb, 1, 'A trunk with per-VLAN sub-interfaces routes between VLANs.'),
  ('nw-rt-04', 2, 'A layer-3 switch routes between VLANs with…', '["ACLs", "SVIs (Switched Virtual Interfaces)", "ARP only", "STP"]'::jsonb, 1, 'SVIs give the switch a routed interface per VLAN.'),
  ('nw-rt-04', 3, 'Each VLAN''s hosts use which as their default gateway?', '["A random host", "The router sub-interface or SVI for that VLAN", "The broadcast address", "Their own IP"]'::jsonb, 1, 'The per-VLAN routed interface is the gateway.'),
  ('nw-rt-05', 1, 'NAT primarily translates…', '["MAC to IP", "Private addresses to public (and back)", "Names to IPs", "VLAN tags"]'::jsonb, 1, 'NAT rewrites private↔public addresses at the edge.'),
  ('nw-rt-05', 2, 'PAT distinguishes many hosts behind one public IP using…', '["VLANs", "Port numbers", "MAC addresses", "DNS"]'::jsonb, 1, 'PAT uses unique port numbers per session.'),
  ('nw-rt-05', 3, 'A side benefit of NAT is that it…', '["Speeds DNS", "Hides internal addressing from the internet", "Encrypts data", "Adds VLANs"]'::jsonb, 1, 'Internal addresses aren''t exposed publicly.'),
  ('nw-wifi-01', 1, 'Which band offers longer range but more interference?', '["5 GHz", "2.4 GHz", "6 GHz", "60 GHz"]'::jsonb, 1, '2.4 GHz reaches further but is more congested.'),
  ('nw-wifi-01', 2, 'The non-overlapping 2.4 GHz channels are…', '["1, 2, 3", "1, 6, 11", "all of them", "5, 10, 15"]'::jsonb, 1, 'Channels 1, 6, 11 don''t overlap on 2.4 GHz.'),
  ('nw-wifi-01', 3, 'Wi-Fi 6E adds which band?', '["2.4 GHz", "5 GHz", "6 GHz", "900 MHz"]'::jsonb, 2, 'Wi-Fi 6E extends into the 6 GHz band.'),
  ('nw-wifi-02', 1, 'The current strongest common Wi-Fi encryption is…', '["WEP", "WPA", "WPA2", "WPA3"]'::jsonb, 3, 'WPA3 is the current standard; WEP/WPA are insecure.'),
  ('nw-wifi-02', 2, 'Enterprise Wi-Fi authentication (802.1X) uses…', '["A shared passphrase", "Per-user credentials via RADIUS", "No auth", "MAC only"]'::jsonb, 1, '802.1X authenticates each user, typically via RADIUS.'),
  ('nw-wifi-02', 3, 'Guest Wi-Fi should be…', '["On the internal VLAN", "Isolated on its own VLAN with client isolation", "Open with no limits", "WEP-secured"]'::jsonb, 1, 'Isolate guests from internal resources.'),
  ('nw-wifi-03', 1, 'A common 2.4 GHz interference source is…', '["Fiber cable", "Microwave ovens and Bluetooth", "5 GHz APs only", "Ethernet switches"]'::jsonb, 1, '2.4 GHz shares spectrum with microwaves and Bluetooth.'),
  ('nw-wifi-03', 2, 'Wireless capacity should be sized for…', '["Floor area only", "Device density", "Cable length", "VLAN count"]'::jsonb, 1, 'Dense client counts, not just coverage, drive AP planning.'),
  ('nw-wifi-03', 3, 'A wireless controller is used to…', '["Route the internet", "Centrally manage many APs", "Replace switches", "Assign public IPs"]'::jsonb, 1, 'Controllers manage AP config, channels, and roaming centrally.'),
  ('nw-sec-01', 1, 'A stateful firewall…', '["Treats each packet in isolation", "Tracks connections and allows return traffic", "Only blocks ICMP", "Routes packets"]'::jsonb, 1, 'Stateful firewalls track sessions and permit their return traffic.'),
  ('nw-sec-01', 2, 'In an ACL, rule order matters because…', '["Rules run randomly", "The first match wins", "The last match wins", "Order is ignored"]'::jsonb, 1, 'ACLs evaluate top-down; the first match applies.'),
  ('nw-sec-01', 3, 'A secure default firewall policy is…', '["Allow all", "Default-deny, allow what''s needed", "Block outbound only", "No rules"]'::jsonb, 1, 'Default-deny with explicit allows is best practice.'),
  ('nw-sec-02', 1, 'A site-to-site VPN connects…', '["One user", "Two whole networks", "A printer", "DNS servers"]'::jsonb, 1, 'Site-to-site links entire networks.'),
  ('nw-sec-02', 2, 'IPsec tunnel mode encrypts…', '["Only headers", "The entire original packet", "Nothing", "Only ports"]'::jsonb, 1, 'Tunnel mode encapsulates and encrypts the whole packet.'),
  ('nw-sec-02', 3, 'IPsec provides confidentiality, integrity, and…', '["Routing", "Authentication", "Switching", "NAT"]'::jsonb, 1, 'IPsec authenticates peers alongside encrypting/integrity-checking traffic.'),
  ('nw-sec-03', 1, 'Network segmentation primarily…', '["Speeds DNS", "Limits how far a breach can spread", "Adds public IPs", "Replaces backups"]'::jsonb, 1, 'Segmentation contains compromise to a zone.'),
  ('nw-sec-03', 2, 'A DMZ is used to…', '["Store backups", "Host internet-facing services separately from the internal network", "Route VLANs", "Assign IPs"]'::jsonb, 1, 'The DMZ isolates public-facing services.'),
  ('nw-sec-03', 3, 'Zero trust assumes…', '["Inside the network is safe", "No implicit trust \u2014 verify every access", "Firewalls are unnecessary", "Only perimeter defence"]'::jsonb, 1, 'Zero trust verifies identity/authorisation regardless of location.'),
  ('nw-sec-04', 1, 'A DHCP relay is needed when…', '["Every subnet has a DHCP server", "Clients are on a different subnet from the DHCP server", "DNS is down", "VLANs are absent"]'::jsonb, 1, 'Relays forward DHCP across subnets to a central server.'),
  ('nw-sec-04', 2, 'DNS resolution generally proceeds…', '["TLD \u2192 root \u2192 host", "Root \u2192 TLD \u2192 authoritative", "Randomly", "Host \u2192 root"]'::jsonb, 1, 'Resolvers go root → TLD → authoritative (with caching).'),
  ('nw-sec-04', 3, 'A rogue DHCP server is mitigated by…', '["DNSSEC", "DHCP snooping", "NAT", "STP"]'::jsonb, 1, 'DHCP snooping permits DHCP only from trusted ports.'),
  ('nw-tsh-01', 1, 'Which tool shows the path and where it breaks?', '["ping", "traceroute/tracert", "arp", "netstat"]'::jsonb, 1, 'Traceroute reveals each hop and where it fails.'),
  ('nw-tsh-01', 2, 'To test whether DNS is resolving you use…', '["ping only", "nslookup / dig", "arp", "ipconfig"]'::jsonb, 1, 'nslookup/dig query DNS directly.'),
  ('nw-tsh-01', 3, 'Pinging 8.8.8.8 works but a website name fails — the likely problem is…', '["Routing", "DNS resolution", "The cable", "NAT"]'::jsonb, 1, 'IP works but names fail → DNS resolution issue.'),
  ('nw-tsh-02', 1, 'Using the OSI model to troubleshoot means…', '["Guessing", "Checking each layer methodically", "Ignoring layers", "Rebooting first"]'::jsonb, 1, 'Work layer by layer to localise the fault.'),
  ('nw-tsh-02', 2, 'When testing a theory you should change…', '["Many things at once", "One variable at a time", "Nothing", "Random settings"]'::jsonb, 1, 'One change at a time isolates cause and effect.'),
  ('nw-tsh-02', 3, 'A key early question is…', '["What''s the CPU model", "Is it one user or many, and what changed?", "What''s the wallpaper", "The switch brand"]'::jsonb, 1, 'Scope and recent changes localise the problem.'),
  ('nw-tsh-03', 1, 'A TCP connection starts with which exchange?', '["ACK \u2192 SYN", "SYN \u2192 SYN-ACK \u2192 ACK", "PUSH \u2192 PULL", "GET \u2192 POST"]'::jsonb, 1, 'The three-way handshake is SYN, SYN-ACK, ACK.'),
  ('nw-tsh-03', 2, 'Display filters in a capture tool are used to…', '["Encrypt packets", "Focus on relevant traffic", "Block traffic", "Route packets"]'::jsonb, 1, 'Filters narrow the capture to what matters.'),
  ('nw-tsh-03', 3, 'Packet analysis is most useful when…', '["Everything works", "Higher-level tools can''t explain the problem", "You need to assign IPs", "Configuring VLANs"]'::jsonb, 1, 'Captures reveal exactly what''s happening on the wire.'),
  ('nw-tsh-04', 1, 'Which protocol polls device health like interface and CPU stats?', '["NetFlow", "SNMP", "Syslog", "ARP"]'::jsonb, 1, 'SNMP polls device health metrics.'),
  ('nw-tsh-04', 2, 'NetFlow tells you…', '["Device temperature", "Traffic patterns (who talks to whom, how much)", "DNS records", "MAC tables"]'::jsonb, 1, 'Flow data reveals conversation and volume patterns.'),
  ('nw-tsh-04', 3, 'The point of a baseline is to…', '["Slow the network", "Know normal so you can alert on deviations", "Encrypt logs", "Replace backups"]'::jsonb, 1, 'Baselines make anomalies detectable.');
