-- 0036_seed_helpdesk_tier2_quizzes.sql — P20 Help Desk Tier 2 quizzes. Idempotent.
insert into public.lesson_quizzes (lesson_id, pass_pct, bonus_xp) values
  ('t2-win-01', 70, 30),
  ('t2-win-02', 70, 30),
  ('t2-win-03', 70, 30),
  ('t2-win-04', 70, 30),
  ('t2-win-05', 70, 30),
  ('t2-win-06', 70, 30),
  ('t2-win-07', 70, 30),
  ('t2-ad-01', 70, 30),
  ('t2-ad-02', 70, 30),
  ('t2-ad-03', 70, 30),
  ('t2-ad-04', 70, 30),
  ('t2-ad-05', 70, 30),
  ('t2-ad-06', 70, 30),
  ('t2-m365-01', 70, 30),
  ('t2-m365-02', 70, 30),
  ('t2-m365-03', 70, 30),
  ('t2-m365-04', 70, 30),
  ('t2-m365-05', 70, 30),
  ('t2-m365-06', 70, 30),
  ('t2-m365-07', 70, 30),
  ('t2-net-01', 70, 30),
  ('t2-net-02', 70, 30),
  ('t2-net-03', 70, 30),
  ('t2-net-04', 70, 30),
  ('t2-net-05', 70, 30),
  ('t2-itil-01', 70, 30),
  ('t2-itil-02', 70, 30),
  ('t2-itil-03', 70, 30),
  ('t2-itil-04', 70, 30),
  ('t2-itil-05', 70, 30)
on conflict (lesson_id) do update set pass_pct=excluded.pass_pct, bonus_xp=excluded.bonus_xp;

delete from public.quiz_questions where lesson_id in ('t2-win-01', 't2-win-02', 't2-win-03', 't2-win-04', 't2-win-05', 't2-win-06', 't2-win-07', 't2-ad-01', 't2-ad-02', 't2-ad-03', 't2-ad-04', 't2-ad-05', 't2-ad-06', 't2-m365-01', 't2-m365-02', 't2-m365-03', 't2-m365-04', 't2-m365-05', 't2-m365-06', 't2-m365-07', 't2-net-01', 't2-net-02', 't2-net-03', 't2-net-04', 't2-net-05', 't2-itil-01', 't2-itil-02', 't2-itil-03', 't2-itil-04', 't2-itil-05');

insert into public.quiz_questions (lesson_id, sort, prompt, options, correct_index, explanation) values
  ('t2-win-01', 1, 'A ''no boot device / BCD'' error is best fixed with…', '["Reinstalling apps", "Startup Repair / bootrec in WinRE", "A new monitor", "Disabling Wi-Fi"]'::jsonb, 1, 'WinRE''s Startup Repair or bootrec fixes boot/BCD problems.'),
  ('t2-win-01', 2, 'Windows normally enters WinRE automatically after…', '["One failed boot", "Three failed boots", "A week", "Never"]'::jsonb, 1, 'Repeated (≈3) boot failures trigger WinRE.'),
  ('t2-win-01', 3, 'A reboot loop after the logo most often points to…', '["A DNS issue", "A bad driver or update", "A full mailbox", "A weak password"]'::jsonb, 1, 'Kernel-stage loops are commonly driver/update related.'),
  ('t2-win-02', 1, 'The first clue to a BSOD''s cause is…', '["The wallpaper", "The stop code (and any named driver)", "The user''s name", "The IP address"]'::jsonb, 1, 'The stop code and faulting driver point to the cause.'),
  ('t2-win-02', 2, 'Which tool shows a timeline of crashes and recent changes?', '["Reliability Monitor", "Notepad", "DNS Manager", "Paint"]'::jsonb, 0, 'Reliability Monitor correlates crashes with changes.'),
  ('t2-win-02', 3, 'Frequent BSODs with memory-related stop codes suggest testing…', '["The mouse", "RAM", "The monitor", "DNS"]'::jsonb, 1, 'Memory errors are a common BSOD cause — run a memory test.'),
  ('t2-win-03', 1, 'If a problem disappears in Safe Mode, the cause is likely…', '["Hardware failure", "A third-party driver or startup item", "A DNS error", "A dead battery"]'::jsonb, 1, 'Safe Mode loads minimal drivers, isolating third-party causes.'),
  ('t2-win-03', 2, 'Startup Repair and System Restore are launched from…', '["The BIOS", "WinRE (Advanced Startup)", "Task Manager", "the registry"]'::jsonb, 1, 'WinRE hosts the recovery tools.'),
  ('t2-win-03', 3, 'A quick way to reach Advanced Startup is…', '["Delete Windows", "Shift + Restart", "Unplug the mouse", "Change the wallpaper"]'::jsonb, 1, 'Shift+Restart opens Advanced Startup options.'),
  ('t2-win-04', 1, 'System Restore reverts…', '["Personal files", "System files, drivers, and registry to a restore point", "Only the wallpaper", "Nothing"]'::jsonb, 1, 'It rolls back system state without deleting personal files.'),
  ('t2-win-04', 2, '''Reset this PC → Keep my files'' will…', '["Delete documents", "Reinstall Windows and keep documents (removes apps)", "Do nothing", "Only change the password"]'::jsonb, 1, 'It refreshes Windows, keeping files but removing apps.'),
  ('t2-win-04', 3, 'Before editing a registry key you should…', '["Delete a random key", "Export/back up the key first", "Turn off the PC", "Change the IP"]'::jsonb, 1, 'Export the key so you can restore it if needed.'),
  ('t2-win-05', 1, 'A standard image mainly provides…', '["Random configs", "Consistent OS/apps/settings across machines", "Slower builds", "More BSODs"]'::jsonb, 1, 'Imaging gives consistent, fast, supportable builds.'),
  ('t2-win-05', 2, 'The critical step before reimaging is to…', '["Change the wallpaper", "Back up user data", "Delete the registry", "Disable DNS"]'::jsonb, 1, 'Always back up user data before a wipe.'),
  ('t2-win-05', 3, 'After reimaging a domain PC you must…', '["Nothing", "Rejoin the domain and restore data/apps", "Only set wallpaper", "Remove the NIC"]'::jsonb, 1, 'Rejoin the domain and restore the user''s environment.'),
  ('t2-win-06', 1, 'A ''.bak'' key under ProfileList usually means…', '["Healthy profile", "A corrupt/temp profile", "A virus", "Low disk"]'::jsonb, 1, 'The profile is corrupt; Windows loaded a temp one.'),
  ('t2-win-06', 2, 'Best way to isolate profile vs machine issues…', '["Reinstall Windows", "Test another user + another PC", "Replace RAM", "Reset router"]'::jsonb, 1, 'Cross-test user and machine.'),
  ('t2-win-06', 3, 'Before recreating a profile you must…', '["Nothing", "Back up the user''s data", "Reimage", "Change the CPU"]'::jsonb, 1, 'Back up data first — recreation wipes the profile.'),
  ('t2-win-07', 1, 'Sustained 100% disk + SMART warnings suggests…', '["Nothing", "A failing drive", "Low volume", "A DNS issue"]'::jsonb, 1, 'Likely a failing drive — back up and replace.'),
  ('t2-win-07', 2, 'Which tool shows per-resource usage?', '["Notepad", "Resource Monitor", "Paint", "Regedit"]'::jsonb, 1, 'Resource Monitor breaks down CPU/disk/RAM/net.'),
  ('t2-win-07', 3, 'Trim slow boots via…', '["Task Manager Startup tab", "New monitor", "BIOS reset", "More RAM only"]'::jsonb, 0, 'Disable heavy startup apps.'),
  ('t2-ad-01', 1, 'When a user leaves, the safer first action is to…', '["Delete immediately", "Disable the account", "Reset the wallpaper", "Ignore it"]'::jsonb, 1, 'Disabling preserves history/access references; deletion can be done later.'),
  ('t2-ad-01', 2, 'A user''s OU placement determines…', '["Their monitor size", "Which Group Policy and access they inherit", "Their password length only", "Nothing"]'::jsonb, 1, 'OU membership drives inherited policy and access.'),
  ('t2-ad-01', 3, 'The everyday GUI for AD account tasks is…', '["Notepad", "Active Directory Users and Computers", "the BIOS", "Paint"]'::jsonb, 1, 'ADUC manages users, groups, and OUs.'),
  ('t2-ad-02', 1, 'To grant a user access to a resource you usually…', '["Edit their profile", "Add them to the right group", "Change their password", "Reboot the server"]'::jsonb, 1, 'Access is granted via group membership.'),
  ('t2-ad-02', 2, 'New group membership typically takes effect…', '["Instantly always", "At next logon / token refresh", "After a week", "Never"]'::jsonb, 1, 'Users often must log off/on to pick up new membership.'),
  ('t2-ad-02', 3, 'If one group Allows and another Denies, the result is…', '["Allow", "Deny", "Random", "No access rule"]'::jsonb, 1, 'An explicit Deny overrides Allow.'),
  ('t2-ad-03', 1, 'Before resetting a password you must first…', '["Reboot the DC", "Verify the user''s identity", "Change their OU", "Disable DNS"]'::jsonb, 1, 'Identity verification prevents social-engineering resets.'),
  ('t2-ad-03', 2, 'An account locked by failed attempts needs to be…', '["Deleted", "Unlocked", "Reimaged", "Moved OUs"]'::jsonb, 1, 'Unlock the account (reset only if the password is unknown).'),
  ('t2-ad-03', 3, 'Repeated lockouts are commonly caused by…', '["A fast CPU", "A stale cached password (phone/drive/service)", "A new mouse", "DNS scavenging"]'::jsonb, 1, 'Cached old credentials repeatedly lock the account.'),
  ('t2-ad-04', 1, 'A setting a user ''can''t change'' is often enforced by…', '["Their mouse", "Group Policy", "DNS", "The monitor"]'::jsonb, 1, 'GPOs enforce settings centrally based on OU.'),
  ('t2-ad-04', 2, 'Which command reports the GPOs applied to a user/PC?', '["ipconfig", "gpresult", "ping", "arp"]'::jsonb, 1, 'gpresult shows the resultant set of policy.'),
  ('t2-ad-04', 3, 'From the help desk, a misapplied domain GPO should be…', '["Edited directly", "Documented and escalated to the GPO team", "Deleted", "Ignored"]'::jsonb, 1, 'Capture evidence and escalate; don''t edit domain policy at Tier 2.'),
  ('t2-ad-05', 1, 'Which shows the policies actually applied?', '["gpupdate", "gpresult /r", "ipconfig", "chkdsk"]'::jsonb, 1, 'gpresult /r lists applied GPOs.'),
  ('t2-ad-05', 2, 'The most common ''GPO not applying'' cause is…', '["Wrong OU", "Bad RAM", "Low disk", "DNS only"]'::jsonb, 0, 'The object is often in the wrong OU.'),
  ('t2-ad-05', 3, 'GPO precedence order is…', '["OU\u2192Domain\u2192Site\u2192Local", "Local\u2192Site\u2192Domain\u2192OU", "random", "Domain only"]'::jsonb, 1, 'Local, Site, Domain, OU — last wins.'),
  ('t2-ad-06', 1, 'Which event ID indicates a lockout?', '["4625", "4740", "1000", "41"]'::jsonb, 1, 'Event 4740 logs account lockouts.'),
  ('t2-ad-06', 2, 'Repeated re-lockouts usually mean…', '["Bad monitor", "A stale saved credential somewhere", "Low RAM", "DNS"]'::jsonb, 1, 'An old password cached on a device/service.'),
  ('t2-ad-06', 3, 'The caller computer in the lockout event tells you…', '["Nothing", "Where the bad creds originate", "The CPU", "The IP of the DC"]'::jsonb, 1, 'It points to the source of the bad attempts.'),
  ('t2-m365-01', 1, 'Which admin role follows least privilege for help desk work?', '["Global Admin", "Helpdesk/User Admin", "Owner", "None"]'::jsonb, 1, 'Scoped roles like Helpdesk Admin avoid over-granting Global Admin.'),
  ('t2-m365-01', 2, 'Before troubleshooting a widespread outage, check…', '["The wallpaper", "The Service health dashboard", "The BIOS", "DNS scavenging"]'::jsonb, 1, 'Service health shows Microsoft-side incidents.'),
  ('t2-m365-01', 3, 'The admin center is primarily used to manage…', '["Switch VLANs", "Users, licenses, and M365 services", "Router ACLs", "Physical cabling"]'::jsonb, 1, 'It manages M365 identities, licensing, and services.'),
  ('t2-m365-02', 1, 'Which plan does NOT include the desktop Office apps?', '["Business Standard", "Business Basic", "E3", "E5"]'::jsonb, 1, 'Business Basic is web/mobile + services; no desktop Office.'),
  ('t2-m365-02', 2, 'Business Premium adds, over Standard, mainly…', '["Nothing", "Advanced security and device management (Intune)", "A new mouse", "Fewer features"]'::jsonb, 1, 'Premium adds security and Intune device management.'),
  ('t2-m365-02', 3, 'A user with no desktop apps who needs them likely has the wrong…', '["Monitor", "License plan", "Keyboard", "Cable"]'::jsonb, 1, 'Reassign to a plan that includes desktop Office (Standard/E3).'),
  ('t2-m365-03', 1, 'A support@ address several staff monitor is best set up as a…', '["User mailbox each", "Shared mailbox", "Distribution list only", "Personal folder"]'::jsonb, 1, 'A shared mailbox lets multiple users access one inbox.'),
  ('t2-m365-03', 2, 'An extra email address on an existing mailbox is called an…', '["Alias", "OU", "ACL", "SID"]'::jsonb, 0, 'An alias is an additional address for a mailbox.'),
  ('t2-m365-03', 3, 'For a missing inbound email, first check…', '["The BIOS", "Quarantine, address, and message trace", "The router", "The wallpaper"]'::jsonb, 1, 'Quarantine and message trace explain most delivery issues.'),
  ('t2-m365-04', 1, 'Microsoft 365 cloud identity is provided by…', '["On-prem DNS", "Entra ID (Azure AD)", "the BIOS", "a switch"]'::jsonb, 1, 'Entra ID underpins M365 identity and sign-in.'),
  ('t2-m365-04', 2, 'The single biggest account-security improvement is…', '["A longer wallpaper", "Multi-factor authentication", "A faster CPU", "More RAM"]'::jsonb, 1, 'MFA dramatically reduces account compromise.'),
  ('t2-m365-04', 3, 'A sign-in blocked by location policy is likely…', '["A broken account", "Conditional Access working as intended", "A dead NIC", "A DNS error"]'::jsonb, 1, 'Conditional Access may be correctly blocking risky sign-ins.'),
  ('t2-m365-05', 1, 'Most ''can''t open a shared file'' tickets are…', '["Hardware failures", "Sharing/permission problems", "DNS outages", "BIOS errors"]'::jsonb, 1, 'Permissions/sharing cause most file-access issues.'),
  ('t2-m365-05', 2, 'Intune is used to…', '["Route packets", "Manage and secure devices (MDM)", "Assign IPs", "Replicate DNS"]'::jsonb, 1, 'Intune handles device enrollment, compliance, and apps.'),
  ('t2-m365-05', 3, 'A Teams meeting with no sound is usually a…', '["License issue", "Audio device/permission issue", "DNS problem", "Registry error"]'::jsonb, 1, 'Teams AV issues are typically device/permission related.'),
  ('t2-m365-06', 1, 'Best first tool for a delivery issue…', '["Reboot Outlook", "Message trace", "New mailbox", "Reset password"]'::jsonb, 1, 'Message trace shows the delivery path.'),
  ('t2-m365-06', 2, 'Which protects against spoofing?', '["SPF/DKIM/DMARC", "RAID", "VLAN", "UAC"]'::jsonb, 0, 'SPF/DKIM/DMARC authenticate senders.'),
  ('t2-m365-06', 3, 'An NDR code like 550 5.4.1…', '["Is random", "Explains the delivery failure", "Means success", "Is a virus"]'::jsonb, 1, 'NDR codes identify the cause.'),
  ('t2-m365-07', 1, 'A Team is backed by…', '["A single mailbox", "A SharePoint site + M365 group", "A local folder", "A VLAN"]'::jsonb, 1, 'Teams use a SharePoint site and M365 group.'),
  ('t2-m365-07', 2, 'A frequent Teams client fix is…', '["Replace GPU", "Clear the Teams cache", "Reset BIOS", "New license only"]'::jsonb, 1, 'Clearing the cache fixes many client issues.'),
  ('t2-m365-07', 3, 'File access differences usually come from…', '["Permissions inheritance", "CPU speed", "Monitor size", "DNS"]'::jsonb, 0, 'Broken permission inheritance.'),
  ('t2-net-01', 1, 'A client with a 169.254 address has…', '["A DNS issue", "No DHCP lease", "A VPN problem", "A printer issue"]'::jsonb, 1, '169.254 (APIPA) means no DHCP lease was obtained.'),
  ('t2-net-01', 2, 'Pinging an IP works but names fail — fix by checking/refreshing…', '["The router firmware", "DNS (flushdns / nslookup)", "the monitor", "BIOS"]'::jsonb, 1, 'IP works, names fail → DNS resolution problem.'),
  ('t2-net-01', 3, 'Which re-requests a DHCP lease?', '["ipconfig /flushdns", "ipconfig /release then /renew", "ping", "arp -a"]'::jsonb, 1, 'release/renew re-acquires an address from DHCP.'),
  ('t2-net-02', 1, 'Before a VPN can connect, the user needs…', '["A printer", "Working internet first", "A new mouse", "A VLAN"]'::jsonb, 1, 'VPN rides over the existing internet connection.'),
  ('t2-net-02', 2, 'Connected to VPN but can''t reach internal resources often means…', '["A dead battery", "DNS/routing not applied through the tunnel", "A BIOS error", "A full mailbox"]'::jsonb, 1, 'Missing VPN DNS/routes block internal access.'),
  ('t2-net-02', 3, 'Split tunneling means…', '["All traffic goes via VPN", "Only some traffic goes through the VPN", "VPN is disabled", "Two VPNs at once"]'::jsonb, 1, 'Split tunneling routes only selected traffic through the VPN.'),
  ('t2-net-03', 1, 'A stuck print queue is often cleared by…', '["Reinstalling Windows", "Clearing jobs / restarting the Print Spooler", "Changing the wallpaper", "Resetting DNS"]'::jsonb, 1, 'The Print Spooler service manages the queue.'),
  ('t2-net-03', 2, 'A networked printer ''offline'' for everyone suggests checking…', '["One PC''s driver", "The printer''s power/network/IP", "The user''s password", "The monitor"]'::jsonb, 1, 'A shared outage points to the printer/network, not one PC.'),
  ('t2-net-03', 3, 'Restarting the Print Spooler on a print server…', '["Is invisible", "Clears all queued jobs there \u2014 warn users", "Deletes drivers", "Changes IPs"]'::jsonb, 1, 'It flushes queued jobs, so notify affected users.'),
  ('t2-net-04', 1, 'VPN connects but names don''t resolve →', '["Bad monitor", "Internal DNS/routing", "Low RAM", "Dead NIC"]'::jsonb, 1, 'Likely DNS or routing over the tunnel.'),
  ('t2-net-04', 2, 'First confirm before VPN troubleshooting…', '["User has internet", "New laptop", "Reset AD", "Reinstall Office"]'::jsonb, 0, 'No internet = no VPN.'),
  ('t2-net-04', 3, 'Reaching a host by IP but not name means…', '["Routing is down", "DNS issue", "VPN is off", "Firewall only"]'::jsonb, 1, 'Name resolution (DNS) is failing.'),
  ('t2-net-05', 1, 'IP reachable, names fail →', '["Cable", "DNS", "Power", "GPU"]'::jsonb, 1, 'DNS resolution is broken.'),
  ('t2-net-05', 2, 'Clear stale DNS records with…', '["ipconfig /flushdns", "chkdsk", "sfc", "ping"]'::jsonb, 0, 'ipconfig /flushdns clears the cache.'),
  ('t2-net-05', 3, 'Verify a name resolves with…', '["nslookup", "dir", "cls", "copy"]'::jsonb, 0, 'nslookup tests resolution.'),
  ('t2-itil-01', 1, 'Restoring a down service as fast as possible is a(n)…', '["Problem", "Incident", "Change", "Release"]'::jsonb, 1, 'An incident is about restoring service quickly.'),
  ('t2-itil-01', 2, 'Finding the root cause of recurring incidents is…', '["Change", "Problem management", "An incident", "A reset"]'::jsonb, 1, 'Problem management removes the underlying cause.'),
  ('t2-itil-01', 3, 'A controlled, approved modification to infrastructure is a…', '["Incident", "Change", "Problem", "Ticket"]'::jsonb, 1, 'Changes go through review/approval to reduce risk.'),
  ('t2-itil-02', 1, 'Priority is generally determined by…', '["Alphabetical order", "Impact combined with urgency", "Ticket number", "User seniority only"]'::jsonb, 1, 'Priority = impact × urgency.'),
  ('t2-itil-02', 2, 'An SLA defines…', '["The wallpaper", "Target response/resolution times", "The IP scheme", "The registry"]'::jsonb, 1, 'SLAs set time targets per priority.'),
  ('t2-itil-02', 3, 'When you escalate a ticket you should…', '["Close it", "Hand off with full notes and keep ownership", "Delete it", "Ignore it"]'::jsonb, 1, 'Escalation includes documentation and continued ownership.'),
  ('t2-itil-03', 1, 'Good ticket notes let a colleague…', '["Guess", "Pick up the ticket cold", "Skip the SLA", "Delete history"]'::jsonb, 1, 'Clear notes enable seamless handoffs.'),
  ('t2-itil-03', 2, 'A recurring issue with known steps deserves a…', '["Deleted ticket", "Knowledge base article", "Louder alert", "New OU"]'::jsonb, 1, 'KB articles capture repeatable resolutions.'),
  ('t2-itil-03', 3, 'When remoting onto a user''s PC you should…', '["Say nothing", "Explain, get consent, respect privacy", "Change their wallpaper", "Disable their account"]'::jsonb, 1, 'Consent and transparency build user trust.'),
  ('t2-itil-04', 1, 'A strong escalation always includes…', '["Just ''it''s broken''", "Repro steps, errors, what''s tried", "Only the username", "A screenshot only"]'::jsonb, 1, 'Context and steps tried speed resolution.'),
  ('t2-itil-04', 2, 'Priority is derived from…', '["Impact + urgency", "Ticket age only", "Random", "Alphabetical"]'::jsonb, 0, 'Impact and urgency set priority.'),
  ('t2-itil-04', 3, 'Before escalating you should…', '["Nothing", "Triage and document", "Reimage", "Close it"]'::jsonb, 1, 'Triage first, then escalate with notes.'),
  ('t2-itil-05', 1, 'A ''problem'' record exists to…', '["Restore service now", "Find/fix root cause", "Buy hardware", "Close incidents faster"]'::jsonb, 1, 'Problems address recurring root causes.'),
  ('t2-itil-05', 2, 'Changes should always have…', '["A rollback plan", "A new server", "More RAM", "A screenshot"]'::jsonb, 0, 'A rollback plan reduces change risk.'),
  ('t2-itil-05', 3, 'Restoring service ASAP is…', '["Problem mgmt", "Incident mgmt", "Change mgmt", "Release mgmt"]'::jsonb, 1, 'That''s incident management.');
