-- 0045_seed_comptia_lessons.sql — P28 CompTIA A+ lessons. Idempotent.
insert into public.curriculum_lessons (id, slug, title, track, xp, sort_order) values
  ('ca-hw-01', 'cpu-motherboard', 'CPUs & Motherboards', 'comptia', 50, 5001),
  ('ca-hw-02', 'memory-storage', 'Memory & Storage', 'comptia', 50, 5002),
  ('ca-hw-03', 'power-connectors', 'Power, Connectors & Peripherals', 'comptia', 50, 5003),
  ('ca-hw-04', 'display-video', 'Display & Video', 'comptia', 50, 5004),
  ('ca-hw-05', 'printers', 'Printers & Multifunction Devices', 'comptia', 55, 5005),
  ('ca-hw-06', 'custom-raid', 'Custom Configurations & RAID', 'comptia', 50, 5006),
  ('ca-net-01', 'fundamentals', 'Networking Fundamentals', 'comptia', 50, 5007),
  ('ca-net-02', 'cabling', 'Cabling & Connectors', 'comptia', 50, 5008),
  ('ca-net-03', 'wireless-soho', 'Wireless & SOHO Networks', 'comptia', 50, 5009),
  ('ca-net-04', 'devices', 'Network Devices', 'comptia', 50, 5010),
  ('ca-net-05', 'tcpip-services', 'TCP/IP & Network Services', 'comptia', 55, 5011),
  ('ca-net-06', 'internet-types', 'Internet Connection Types', 'comptia', 50, 5012),
  ('ca-mc-01', 'mobile', 'Mobile Devices', 'comptia', 50, 5013),
  ('ca-mc-02', 'virtualization', 'Virtualization', 'comptia', 50, 5014),
  ('ca-mc-03', 'cloud', 'Cloud Concepts', 'comptia', 50, 5015),
  ('ca-mc-04', 'mobile-connectivity', 'Mobile Connectivity & Email', 'comptia', 50, 5016),
  ('ca-mc-05', 'mobile-sync-security', 'Mobile Sync & Security', 'comptia', 50, 5017),
  ('ca-mc-06', 'laptop-hardware', 'Laptop Hardware', 'comptia', 50, 5018),
  ('ca-os-01', 'types-install', 'OS Types & Installation', 'comptia', 50, 5019),
  ('ca-os-02', 'windows-config', 'Windows Configuration', 'comptia', 50, 5020),
  ('ca-os-03', 'command-line', 'Command-Line Basics', 'comptia', 50, 5021),
  ('ca-os-04', 'macos-linux', 'macOS & Linux Basics', 'comptia', 50, 5022),
  ('ca-os-05', 'windows-networking', 'Windows Networking Configuration', 'comptia', 50, 5023),
  ('ca-os-06', 'users-security', 'OS Security & User Management', 'comptia', 50, 5024),
  ('ca-sec-01', 'threats-malware', 'Security Threats & Malware', 'comptia', 55, 5025),
  ('ca-sec-02', 'best-practices', 'Security Best Practices', 'comptia', 55, 5026),
  ('ca-sec-03', 'physical-data', 'Physical & Data Security', 'comptia', 55, 5027),
  ('ca-sec-04', 'wireless-auth', 'Wireless Security & Authentication', 'comptia', 55, 5028),
  ('ca-sec-05', 'malware-removal', 'Malware Removal Process', 'comptia', 55, 5029),
  ('ca-sec-06', 'social-engineering', 'Social Engineering & Common Threats', 'comptia', 55, 5030),
  ('ca-ts-01', 'methodology', 'Troubleshooting Methodology', 'comptia', 55, 5031),
  ('ca-ts-02', 'hardware-issues', 'Common Hardware Issues', 'comptia', 55, 5032),
  ('ca-ts-03', 'software-issues', 'Common OS & Software Issues', 'comptia', 55, 5033),
  ('ca-ts-04', 'network-ts', 'Network Troubleshooting', 'comptia', 55, 5034),
  ('ca-ts-05', 'printer-ts', 'Printer Troubleshooting', 'comptia', 50, 5035),
  ('ca-ts-06', 'mobile-security-ts', 'Mobile & Security Troubleshooting', 'comptia', 50, 5036)
on conflict (id) do update set slug=excluded.slug, title=excluded.title, track=excluded.track, xp=excluded.xp, sort_order=excluded.sort_order;
