-- 0046_seed_comptia_quizzes.sql — P28 CompTIA A+ quizzes. Idempotent.
insert into public.lesson_quizzes (lesson_id, pass_pct, bonus_xp) values
  ('ca-hw-01', 70, 30),
  ('ca-hw-02', 70, 30),
  ('ca-hw-03', 70, 30),
  ('ca-hw-04', 70, 30),
  ('ca-hw-05', 70, 30),
  ('ca-hw-06', 70, 30),
  ('ca-hw-07', 70, 30),
  ('ca-net-01', 70, 30),
  ('ca-net-02', 70, 30),
  ('ca-net-03', 70, 30),
  ('ca-net-04', 70, 30),
  ('ca-net-05', 70, 30),
  ('ca-net-06', 70, 30),
  ('ca-net-07', 70, 30),
  ('ca-mc-01', 70, 30),
  ('ca-mc-02', 70, 30),
  ('ca-mc-03', 70, 30),
  ('ca-mc-04', 70, 30),
  ('ca-mc-05', 70, 30),
  ('ca-mc-06', 70, 30),
  ('ca-mc-07', 70, 30),
  ('ca-os-01', 70, 30),
  ('ca-os-02', 70, 30),
  ('ca-os-03', 70, 30),
  ('ca-os-04', 70, 30),
  ('ca-os-05', 70, 30),
  ('ca-os-06', 70, 30),
  ('ca-os-07', 70, 30),
  ('ca-sec-01', 70, 30),
  ('ca-sec-02', 70, 30),
  ('ca-sec-03', 70, 30),
  ('ca-sec-04', 70, 30),
  ('ca-sec-05', 70, 30),
  ('ca-sec-06', 70, 30),
  ('ca-sec-07', 70, 30),
  ('ca-ts-01', 70, 30),
  ('ca-ts-02', 70, 30),
  ('ca-ts-03', 70, 30),
  ('ca-ts-04', 70, 30),
  ('ca-ts-05', 70, 30),
  ('ca-ts-06', 70, 30),
  ('ca-ts-07', 70, 30)
on conflict (lesson_id) do update set pass_pct=excluded.pass_pct, bonus_xp=excluded.bonus_xp;

delete from public.quiz_questions where lesson_id in ('ca-hw-01', 'ca-hw-02', 'ca-hw-03', 'ca-hw-04', 'ca-hw-05', 'ca-hw-06', 'ca-hw-07', 'ca-net-01', 'ca-net-02', 'ca-net-03', 'ca-net-04', 'ca-net-05', 'ca-net-06', 'ca-net-07', 'ca-mc-01', 'ca-mc-02', 'ca-mc-03', 'ca-mc-04', 'ca-mc-05', 'ca-mc-06', 'ca-mc-07', 'ca-os-01', 'ca-os-02', 'ca-os-03', 'ca-os-04', 'ca-os-05', 'ca-os-06', 'ca-os-07', 'ca-sec-01', 'ca-sec-02', 'ca-sec-03', 'ca-sec-04', 'ca-sec-05', 'ca-sec-06', 'ca-sec-07', 'ca-ts-01', 'ca-ts-02', 'ca-ts-03', 'ca-ts-04', 'ca-ts-05', 'ca-ts-06', 'ca-ts-07');

insert into public.quiz_questions (lesson_id, sort, prompt, options, correct_index, explanation) values
  ('ca-hw-01', 1, 'A CPU must match the motherboard''s…', '["Color", "Socket", "Fan brand", "Case size"]'::jsonb, 1, 'The socket (LGA/AM4/AM5) must match the CPU.'),
  ('ca-hw-01', 2, 'Which form factor is the largest with the most expansion?', '["Mini-ITX", "microATX", "ATX", "Nano-ITX"]'::jsonb, 2, 'ATX is the largest common form factor.'),
  ('ca-hw-01', 3, 'A GPU typically uses which slot?', '["PCIe x1", "PCIe x16", "RAM slot", "SATA"]'::jsonb, 1, 'Graphics cards use the PCIe x16 slot.'),
  ('ca-hw-02', 1, 'Which is volatile (cleared on power off)?', '["SSD", "HDD", "RAM", "NVMe"]'::jsonb, 2, 'RAM is volatile working memory.'),
  ('ca-hw-02', 2, 'The fastest common storage interface is…', '["SATA HDD", "SATA SSD", "NVMe (M.2)", "USB 2.0"]'::jsonb, 2, 'NVMe over PCIe is fastest.'),
  ('ca-hw-02', 3, 'Dual-channel RAM requires…', '["One stick", "Matched pairs", "DDR3 only", "An SSD"]'::jsonb, 1, 'Matched pairs enable dual-channel bandwidth.'),
  ('ca-hw-03', 1, 'The main motherboard power connector is…', '["8-pin", "24-pin", "SATA", "Molex"]'::jsonb, 1, 'The 24-pin ATX connector powers the board.'),
  ('ca-hw-03', 2, 'Which port is network (Ethernet)?', '["RJ-11", "RJ-45", "HDMI", "USB-C"]'::jsonb, 1, 'RJ-45 is the Ethernet connector.'),
  ('ca-hw-03', 3, 'You should never open a PSU because…', '["It voids nothing", "Capacitors can hold a charge", "It''s glued", "It has no parts"]'::jsonb, 1, 'Stored charge in capacitors is a shock hazard.'),
  ('ca-hw-04', 1, 'Which panel type has the best color/viewing angles?', '["TN", "IPS", "VGA", "CRT"]'::jsonb, 1, 'IPS offers superior color and angles.'),
  ('ca-hw-04', 2, 'Which connector is digital and carries audio?', '["VGA", "HDMI", "PS/2", "Serial"]'::jsonb, 1, 'HDMI carries digital audio + video.'),
  ('ca-hw-04', 3, 'Projector brightness is measured in…', '["Hz", "Lumens", "DPI", "Watts"]'::jsonb, 1, 'Lumens measure projector brightness.'),
  ('ca-hw-05', 1, 'Which printer uses toner and a fusing step?', '["Inkjet", "Laser", "Thermal", "Impact"]'::jsonb, 1, 'Laser printers fuse toner to paper.'),
  ('ca-hw-05', 2, 'The step right after Exposing is…', '["Charging", "Developing", "Fusing", "Cleaning"]'::jsonb, 1, 'Developing follows exposing.'),
  ('ca-hw-05', 3, 'Receipts commonly use which printer?', '["Laser", "Thermal", "3D", "Impact"]'::jsonb, 1, 'Thermal printers use heat-sensitive paper.'),
  ('ca-hw-06', 1, 'RAID 0 provides…', '["Redundancy", "Speed, no redundancy", "Parity", "A backup"]'::jsonb, 1, 'Striping boosts speed but has no redundancy.'),
  ('ca-hw-06', 2, 'RAID 5 requires at least…', '["1 disk", "2 disks", "3 disks", "5 disks"]'::jsonb, 2, 'RAID 5 needs 3+ disks for parity.'),
  ('ca-hw-06', 3, 'RAID is not a substitute for…', '["Speed", "Backups", "A GPU", "Cooling"]'::jsonb, 1, 'RAID isn''t a backup.'),
  ('ca-hw-07', 1, 'Which supports GPT disks and Secure Boot?', '["Legacy BIOS", "UEFI", "MBR", "CMOS"]'::jsonb, 1, 'UEFI supports GPT and Secure Boot.'),
  ('ca-hw-07', 2, 'Win11 requires which chip enabled?', '["GPU", "TPM", "NIC", "PSU"]'::jsonb, 1, 'TPM 2.0 is required.'),
  ('ca-hw-07', 3, 'POST runs…', '["After login", "Before OS boot", "On shutdown", "Never"]'::jsonb, 1, 'POST runs at power-on before boot.'),
  ('ca-net-01', 1, 'HTTPS uses port…', '["80", "443", "22", "53"]'::jsonb, 1, 'HTTPS is 443.'),
  ('ca-net-01', 2, 'Which assigns IP addresses automatically?', '["DNS", "DHCP", "RDP", "SMTP"]'::jsonb, 1, 'DHCP hands out IP leases.'),
  ('ca-net-01', 3, 'RDP (Remote Desktop) uses port…', '["22", "3389", "443", "25"]'::jsonb, 1, 'RDP is TCP 3389.'),
  ('ca-net-02', 1, 'Twisted-pair copper uses which connector?', '["RJ-11", "RJ-45", "SC", "BNC"]'::jsonb, 1, 'RJ-45 terminates twisted-pair Ethernet.'),
  ('ca-net-02', 2, 'For the longest distance, choose…', '["Cat 5e", "Multi-mode fiber", "Single-mode fiber", "Coax"]'::jsonb, 2, 'Single-mode fiber carries longest.'),
  ('ca-net-02', 3, 'Max recommended copper Ethernet run is about…', '["10 m", "100 m", "1 km", "500 m"]'::jsonb, 1, '~100 m before signal degrades.'),
  ('ca-net-03', 1, 'The strongest listed Wi-Fi security is…', '["WEP", "WPA", "WPA2", "WPA3"]'::jsonb, 3, 'WPA3 is the current strongest.'),
  ('ca-net-03', 2, 'Which band offers more range (less speed)?', '["5 GHz", "2.4 GHz", "6 GHz", "60 GHz"]'::jsonb, 1, '2.4 GHz reaches farther.'),
  ('ca-net-03', 3, 'First thing to change on a new router…', '["Wall color", "Default admin password", "Nothing", "The cable"]'::jsonb, 1, 'Change default admin credentials immediately.'),
  ('ca-net-04', 1, 'Which device connects LAN devices by MAC address?', '["Router", "Switch", "Modem", "Firewall"]'::jsonb, 1, 'A switch forwards by MAC on the LAN.'),
  ('ca-net-04', 2, 'Power over Ethernet (PoE) is useful for…', '["Cooling", "APs and IP cameras", "Monitors", "Printers only"]'::jsonb, 1, 'PoE powers APs/cameras over the data cable.'),
  ('ca-net-04', 3, 'Which connects two different networks?', '["Switch", "Router", "Hub", "Repeater"]'::jsonb, 1, 'Routers route between networks.'),
  ('ca-net-05', 1, 'NAT lets…', '["Names resolve", "Many private IPs share one public IP", "Wi-Fi work", "Disks mirror"]'::jsonb, 1, 'NAT maps private IPs to a public one.'),
  ('ca-net-05', 2, 'A VLAN provides…', '["Encryption", "Logical network separation", "More storage", "Faster CPU"]'::jsonb, 1, 'VLANs segment a network logically.'),
  ('ca-net-05', 3, '169.254.x.x indicates…', '["Static IP", "No DHCP (APIPA)", "A VPN", "Loopback"]'::jsonb, 1, 'APIPA means no DHCP lease.'),
  ('ca-net-06', 1, 'The fastest, typically symmetrical option is…', '["DSL", "Cable", "Fiber", "Satellite"]'::jsonb, 2, 'Fiber is fastest and symmetrical.'),
  ('ca-net-06', 2, 'Which has the highest latency?', '["Fiber", "Cable", "Satellite", "DSL"]'::jsonb, 2, 'Satellite has high latency.'),
  ('ca-net-06', 3, 'DSL runs over…', '["Coax", "Phone lines", "Fiber", "Cellular"]'::jsonb, 1, 'DSL uses telephone lines.'),
  ('ca-net-07', 1, 'SMB (file sharing) uses port…', '["445", "3389", "53", "25"]'::jsonb, 0, 'SMB is 445.'),
  ('ca-net-07', 2, 'Telnet is insecure; its secure replacement is…', '["FTP", "SSH", "HTTP", "POP3"]'::jsonb, 1, 'SSH replaces Telnet.'),
  ('ca-net-07', 3, 'LDAP uses port…', '["389", "443", "110", "23"]'::jsonb, 0, 'LDAP is 389.'),
  ('ca-mc-01', 1, 'Laptop RAM modules are called…', '["DIMM", "SODIMM", "NVMe", "RJ-45"]'::jsonb, 1, 'Laptops use smaller SODIMM modules.'),
  ('ca-mc-01', 2, 'Sharing a phone''s cellular data to a laptop is…', '["Tethering/hotspot", "DNS", "RDP", "NAT"]'::jsonb, 0, 'Tethering/hotspot shares the connection.'),
  ('ca-mc-01', 3, 'Best protection for a lost phone''s data…', '["Louder ringtone", "Remote wipe + encryption", "Bigger screen", "New SIM"]'::jsonb, 1, 'Remote wipe and encryption protect data.'),
  ('ca-mc-02', 1, 'A bare-metal (Type 1) hypervisor…', '["Runs on an OS", "Runs directly on hardware", "Is a browser", "Needs no CPU"]'::jsonb, 1, 'Type 1 runs directly on hardware.'),
  ('ca-mc-02', 2, 'VirtualBox on your Windows laptop is…', '["Type 1", "Type 2", "A firewall", "A NIC"]'::jsonb, 1, 'Hosted on an OS = Type 2.'),
  ('ca-mc-02', 3, 'Which BIOS feature must be enabled for VMs?', '["Secure Boot only", "CPU virtualization (VT-x/AMD-V)", "RAID", "Fast boot"]'::jsonb, 1, 'Hardware virtualization must be enabled.'),
  ('ca-mc-03', 1, 'Microsoft 365 (finished apps) is…', '["IaaS", "PaaS", "SaaS", "On-prem"]'::jsonb, 2, 'Ready-to-use apps = SaaS.'),
  ('ca-mc-03', 2, 'Renting a bare VM in the cloud is…', '["IaaS", "SaaS", "PaaS", "LAN"]'::jsonb, 0, 'Infrastructure (VMs) = IaaS.'),
  ('ca-mc-03', 3, '''Scale up/down on demand'' describes…', '["Elasticity", "Latency", "A firewall", "A driver"]'::jsonb, 0, 'Elasticity is on-demand scaling.'),
  ('ca-mc-04', 1, 'Which protocol keeps mail synced across devices?', '["POP3", "IMAP", "SMTP-only", "FTP"]'::jsonb, 1, 'IMAP syncs across devices.'),
  ('ca-mc-04', 2, 'Secure IMAP uses port…', '["143", "993", "110", "25"]'::jsonb, 1, 'IMAP over TLS is 993.'),
  ('ca-mc-04', 3, 'Pairing a Bluetooth headset requires…', '["An IP", "Pairing/PIN", "A VLAN", "NAT"]'::jsonb, 1, 'Bluetooth devices pair (often with a PIN).'),
  ('ca-mc-05', 1, 'Which centrally enforces mobile security policy?', '["DNS", "MDM", "NAT", "RAID"]'::jsonb, 1, 'MDM manages/secures devices.'),
  ('ca-mc-05', 2, 'Best protection for a lost phone''s data…', '["Louder ring", "Remote wipe + encryption", "New case", "Bigger battery"]'::jsonb, 1, 'Remote wipe + encryption protect data.'),
  ('ca-mc-05', 3, 'BYOD work/personal separation uses…', '["Containerization", "RAID", "VGA", "PoE"]'::jsonb, 0, 'Containerization isolates work data.'),
  ('ca-mc-06', 1, 'Laptop memory modules are…', '["DIMM", "SODIMM", "DDR only", "NVMe"]'::jsonb, 1, 'Laptops use SODIMM.'),
  ('ca-mc-06', 2, 'Before internal laptop work you should…', '["Nothing", "Power off + ESD precautions", "Increase brightness", "Update apps"]'::jsonb, 1, 'Power down and use ESD protection.'),
  ('ca-mc-06', 3, 'A docking station provides…', '["More CPU", "Additional ports/connectivity", "RAID", "A GPU"]'::jsonb, 1, 'Docks expand ports/connectivity.'),
  ('ca-mc-07', 1, 'Under IaaS the customer manages…', '["Nothing", "The OS and up", "The datacenter", "The hypervisor"]'::jsonb, 1, 'IaaS customers manage the OS upward.'),
  ('ca-mc-07', 2, '''Pay only for what you use'' is…', '["Elasticity", "Measured service", "Latency", "A private cloud"]'::jsonb, 1, 'Measured/metered service.'),
  ('ca-mc-07', 3, 'SaaS means the provider manages…', '["Nothing", "Almost everything", "Only hardware", "Only the app UI"]'::jsonb, 1, 'Provider manages most of the stack.'),
  ('ca-os-01', 1, 'Windows'' primary file system is…', '["FAT32", "NTFS", "ext4", "APFS"]'::jsonb, 1, 'NTFS is Windows'' default.'),
  ('ca-os-01', 2, 'A clean install…', '["Keeps all apps", "Wipes and installs fresh", "Only updates drivers", "Is an upgrade"]'::jsonb, 1, 'Clean install wipes the target.'),
  ('ca-os-01', 3, 'Best file system for a cross-platform USB drive…', '["NTFS", "ext4", "exFAT", "APFS"]'::jsonb, 2, 'exFAT works across OSes for large files.'),
  ('ca-os-02', 1, 'Disable a startup app with…', '["Device Manager", "Task Manager", "Disk Management", "Event Viewer"]'::jsonb, 1, 'Task Manager''s Startup tab.'),
  ('ca-os-02', 2, 'Update a hardware driver in…', '["Task Manager", "Device Manager", "Control Panel > Sound", "Notepad"]'::jsonb, 1, 'Device Manager manages drivers.'),
  ('ca-os-02', 3, 'UAC prompts exist to…', '["Slow you down", "Require elevation for admin changes", "Play sounds", "Update apps"]'::jsonb, 1, 'UAC gates administrative actions.'),
  ('ca-os-03', 1, 'Which lists a directory in Windows CMD?', '["ls", "dir", "cat", "pwd"]'::jsonb, 1, 'dir lists files in CMD.'),
  ('ca-os-03', 2, 'Repair corrupted system files with…', '["chkdsk", "sfc /scannow", "ping", "dir"]'::jsonb, 1, 'sfc /scannow verifies/repairs system files.'),
  ('ca-os-03', 3, 'Show full network configuration with…', '["ping", "ipconfig /all", "tracert", "netstat"]'::jsonb, 1, 'ipconfig /all shows adapter details.'),
  ('ca-os-04', 1, 'The macOS backup tool is…', '["File History", "Time Machine", "rsync only", "OneDrive"]'::jsonb, 1, 'Time Machine backs up macOS.'),
  ('ca-os-04', 2, 'Install a package on Ubuntu with…', '["yum install", "apt install", "brew only", "choco"]'::jsonb, 1, 'apt is Debian/Ubuntu''s manager.'),
  ('ca-os-04', 3, 'Elevate a single Linux command with…', '["run", "sudo", "admin", "elevate"]'::jsonb, 1, 'sudo runs a command as root.'),
  ('ca-os-05', 1, 'A static IP is set when…', '["Always", "DHCP is unavailable or a server needs a fixed address", "Never", "Only on laptops"]'::jsonb, 1, 'Servers/printers often need fixed IPs.'),
  ('ca-os-05', 2, 'Combining Share + NTFS permissions, the effective right is…', '["Most permissive", "Most restrictive", "Share only", "NTFS only"]'::jsonb, 1, 'The most restrictive of the two applies.'),
  ('ca-os-05', 3, 'Remote Desktop uses port…', '["22", "3389", "443", "80"]'::jsonb, 1, 'RDP is 3389.'),
  ('ca-os-06', 1, 'UAC exists to…', '["Speed boot", "Require elevation for admin changes", "Play sounds", "Map drives"]'::jsonb, 1, 'UAC gates administrative actions.'),
  ('ca-os-06', 2, 'Assigning permissions to groups (not individuals)…', '["Is slower", "Simplifies management", "Removes security", "Needs RAID"]'::jsonb, 1, 'Groups scale permission management.'),
  ('ca-os-06', 3, 'Least privilege means users get…', '["Full admin", "Only needed access", "No access", "Random access"]'::jsonb, 1, 'Only the access required.'),
  ('ca-os-07', 1, 'Editing the registry uses…', '["msconfig", "regedit", "cmd", "mmc"]'::jsonb, 1, 'regedit edits the registry.'),
  ('ca-os-07', 2, 'Managing Windows services uses…', '["services.msc", "notepad", "regedit", "dxdiag"]'::jsonb, 0, 'services.msc manages services.'),
  ('ca-os-07', 3, 'Win+R opens the…', '["BIOS", "Run box", "Task Manager", "Registry"]'::jsonb, 1, 'Run launches tools by name.'),
  ('ca-sec-01', 1, 'Ransomware…', '["Speeds the PC", "Encrypts files for payment", "Updates drivers", "Is hardware"]'::jsonb, 1, 'Ransomware extorts by encrypting data.'),
  ('ca-sec-01', 2, 'A fake email to steal credentials is…', '["Phishing", "A trojan", "A worm", "Spam filter"]'::jsonb, 0, 'That''s phishing (social engineering).'),
  ('ca-sec-01', 3, 'The most common attack vector is…', '["The CPU", "The human user", "The PSU", "The monitor"]'::jsonb, 1, 'Users are the top target.'),
  ('ca-sec-02', 1, 'The biggest single account-security win is…', '["A louder alarm", "Multi-factor authentication", "A bigger monitor", "More RAM"]'::jsonb, 1, 'MFA sharply reduces compromise.'),
  ('ca-sec-02', 2, 'Least privilege means…', '["Admin for everyone", "Only the access needed", "No passwords", "Open firewall"]'::jsonb, 1, 'Grant minimum necessary access.'),
  ('ca-sec-02', 3, 'Before disposing of a drive you should…', '["Paint it", "Securely wipe/destroy it", "Email it", "Nothing"]'::jsonb, 1, 'Wipe or destroy to prevent data recovery.'),
  ('ca-sec-03', 1, 'A cable lock protects against…', '["Malware", "Laptop theft", "Phishing", "Power surges"]'::jsonb, 1, 'Physical theft of the device.'),
  ('ca-sec-03', 2, 'The 3-2-1 rule refers to…', '["Passwords", "Backups", "Ports", "Cables"]'::jsonb, 1, '3 copies, 2 media, 1 offsite backups.'),
  ('ca-sec-03', 3, 'Physically destroying a drive by magnetic field is…', '["Wiping", "Degaussing", "Encrypting", "Imaging"]'::jsonb, 1, 'Degaussing erases magnetically.'),
  ('ca-sec-04', 1, 'The strongest listed Wi-Fi security is…', '["WEP", "WPA", "WPA2-TKIP", "WPA3"]'::jsonb, 3, 'WPA3 is strongest.'),
  ('ca-sec-04', 2, 'Enterprise Wi-Fi auth commonly uses…', '["A single PSK", "RADIUS/802.1X", "No auth", "MAC only"]'::jsonb, 1, '802.1X/RADIUS authenticates each user.'),
  ('ca-sec-04', 3, 'MFA combines factors like…', '["Two passwords", "Password + phone code", "Two usernames", "Two SSIDs"]'::jsonb, 1, 'Different factor types (know/have/are).'),
  ('ca-sec-05', 1, 'Step 2 of malware removal is…', '["Educate user", "Quarantine the system", "Reimage", "Buy AV"]'::jsonb, 1, 'Quarantine to stop spread.'),
  ('ca-sec-05', 2, 'You disable System Restore to…', '["Save space", "Avoid preserving malware in restore points", "Speed boot", "Free RAM"]'::jsonb, 1, 'So infected snapshots aren''t kept.'),
  ('ca-sec-05', 3, 'The final step is always…', '["Reboot", "Educate the end user", "Format", "Escalate"]'::jsonb, 1, 'User education prevents recurrence.'),
  ('ca-sec-06', 1, 'Phishing aimed at executives is…', '["Vishing", "Whaling", "Smishing", "Tailgating"]'::jsonb, 1, 'Whaling targets high-value execs.'),
  ('ca-sec-06', 2, 'Intercepting traffic between two parties is…', '["DoS", "Man-in-the-middle", "Phishing", "Zero-day"]'::jsonb, 1, 'MITM intercepts communications.'),
  ('ca-sec-06', 3, 'A DDoS attack aims to…', '["Steal a password", "Overwhelm a service", "Encrypt files", "Clone a drive"]'::jsonb, 1, 'DDoS exhausts a service''s capacity.'),
  ('ca-sec-07', 1, 'MFA requires…', '["Two passwords", "2+ different factor types", "Two usernames", "One PIN"]'::jsonb, 1, 'Different factor types (know/have/are).'),
  ('ca-sec-07', 2, 'Permissions assigned via roles is…', '["ACL", "RBAC", "MFA", "SSO"]'::jsonb, 1, 'Role-based access control.'),
  ('ca-sec-07', 3, 'Least privilege grants…', '["Full admin", "Only what''s needed", "No access", "Random access"]'::jsonb, 1, 'Only the access required.'),
  ('ca-ts-01', 1, 'The first step is…', '["Fix it", "Identify the problem", "Document", "Reboot"]'::jsonb, 1, 'Start by identifying the problem.'),
  ('ca-ts-01', 2, 'Verifying functionality happens…', '["First", "Before testing", "After implementing the fix", "Never"]'::jsonb, 2, 'Verify after implementing the solution.'),
  ('ca-ts-01', 3, 'The final step is always…', '["Reboot", "Document findings", "Buy hardware", "Escalate"]'::jsonb, 1, 'Document the outcome.'),
  ('ca-ts-02', 1, 'A clicking hard drive means…', '["It''s fine", "Imminent failure \u2014 back up", "Low RAM", "A virus"]'::jsonb, 1, 'Clicking indicates mechanical failure.'),
  ('ca-ts-02', 2, 'Random shutdowns under load suggest…', '["Overheating/PSU", "A DNS issue", "Wrong wallpaper", "A full mailbox"]'::jsonb, 0, 'Heat or a failing PSU.'),
  ('ca-ts-02', 3, 'No display first steps…', '["Reinstall Windows", "Reseat GPU/RAM, check cable/input", "Replace CPU", "Format disk"]'::jsonb, 1, 'Check seating and the video cable/input.'),
  ('ca-ts-03', 1, 'First check for a slow PC…', '["Buy new PC", "Startup apps, disk space, malware", "Repaint case", "Replace monitor"]'::jsonb, 1, 'Startup load, disk/RAM, and malware.'),
  ('ca-ts-03', 2, 'Repeated pop-ups and redirects suggest…', '["A GPU issue", "Malware", "A dead PSU", "Low volume"]'::jsonb, 1, 'Likely malware — scan the system.'),
  ('ca-ts-03', 3, 'A non-booting Windows PC → try…', '["New RAM only", "Safe mode / Startup Repair", "Reinstall Office", "Change wallpaper"]'::jsonb, 1, 'Use safe mode and Startup Repair.'),
  ('ca-ts-04', 1, 'A 169.254 address means…', '["Static IP", "No DHCP", "A VPN", "Loopback"]'::jsonb, 1, 'APIPA = no DHCP lease.'),
  ('ca-ts-04', 2, 'Ping by IP works but names fail →', '["Bad cable", "DNS issue", "Dead NIC", "Low RAM"]'::jsonb, 1, 'Name resolution (DNS) is failing.'),
  ('ca-ts-04', 3, 'Which tool shows the path/hops to a host?', '["ping", "tracert", "ipconfig", "chkdsk"]'::jsonb, 1, 'tracert traces the route.'),
  ('ca-ts-05', 1, 'A stuck print queue is cleared by…', '["Reinstalling Windows", "Restarting the Print Spooler", "New toner", "A reboot only"]'::jsonb, 1, 'Restart the Print Spooler service.'),
  ('ca-ts-05', 2, 'Faded laser output usually means…', '["Low toner / dirty drum", "A DNS issue", "Bad RAM", "Wrong driver only"]'::jsonb, 0, 'Low toner or a dirty drum.'),
  ('ca-ts-05', 3, 'Offline for everyone points to…', '["One PC''s driver", "The printer/network", "A user password", "The monitor"]'::jsonb, 1, 'A shared outage is printer/network-side.'),
  ('ca-ts-06', 1, 'Rapid battery drain is often caused by…', '["A DNS issue", "Background apps / aging battery", "RAID", "A firewall"]'::jsonb, 1, 'Background apps or a worn battery.'),
  ('ca-ts-06', 2, 'Pop-ups + high data use on mobile suggest…', '["A GPU fault", "Malware/adware", "Low volume", "A dead SIM"]'::jsonb, 1, 'Likely malware/adware — scan/remove.'),
  ('ca-ts-06', 3, 'For no Wi-Fi on a phone, first try…', '["Reinstall OS", "Toggle airplane mode / reset network", "Replace screen", "New SIM"]'::jsonb, 1, 'Toggle radios / reset network settings.'),
  ('ca-ts-07', 1, 'Minimal-driver boot for diagnosis is…', '["Safe Mode", "Fast boot", "UEFI", "BIOS"]'::jsonb, 0, 'Safe Mode loads minimal drivers.'),
  ('ca-ts-07', 2, 'Rebuild boot config with…', '["sfc", "bootrec /rebuildbcd", "chkdsk", "ping"]'::jsonb, 1, 'bootrec /rebuildbcd repairs BCD.'),
  ('ca-ts-07', 3, 'A BSOD stop code helps you…', '["Nothing", "Identify the cause", "Speed the PC", "Update apps"]'::jsonb, 1, 'The stop code points to the fault.');
