-- 0048_seed_scripting_lessons.sql — P29 Scripting lessons. Idempotent.
insert into public.curriculum_lessons (id, slug, title, track, xp, sort_order) values
  ('sc-ps-01', 'basics', 'PowerShell Basics', 'scripting', 55, 6001),
  ('sc-ps-02', 'objects-pipeline', 'Objects & the Pipeline', 'scripting', 60, 6002),
  ('sc-ps-03', 'variables-data', 'Variables, Operators & Data', 'scripting', 55, 6003),
  ('sc-ps-04', 'flow-loops', 'Flow Control & Loops', 'scripting', 55, 6004),
  ('sc-ps-05', 'functions-scripts', 'Functions & Scripts', 'scripting', 60, 6005),
  ('sc-ps-06', 'automation', 'Practical Automation', 'scripting', 65, 6006),
  ('sc-ps-07', 'error-handling', 'Error Handling & Debugging', 'scripting', 60, 6007),
  ('sc-ps-08', 'remoting-modules', 'Remoting & Modules', 'scripting', 60, 6008),
  ('sc-ps-09', 'real-scripts', 'Real-World Scripts', 'scripting', 70, 6009),
  ('sc-ps-10', 'files-folders', 'Files & Folder Automation', 'scripting', 60, 6010),
  ('sc-ps-11', 'services-processes', 'Services & Processes', 'scripting', 60, 6011),
  ('sc-ps-12', 'events-registry', 'Event Logs & Registry', 'scripting', 60, 6012),
  ('sc-ps-13', 'networking', 'Networking with PowerShell', 'scripting', 60, 6013),
  ('sc-ps-14', 'ad-users', 'Active Directory & User Management', 'scripting', 65, 6014),
  ('sc-ps-15', 'scheduled-wmi', 'Scheduled Tasks & WMI/CIM', 'scripting', 60, 6015),
  ('sc-ps-16', 'data-formats', 'CSV, JSON & XML', 'scripting', 60, 6016),
  ('sc-ps-17', 'capstone', 'Capstone: Automated Health Report', 'scripting', 80, 6017),
  ('sc-ps-18', 'rest-apis', 'REST APIs with PowerShell', 'scripting', 60, 6018),
  ('sc-ps-19', 'log-analysis', 'Log Analysis', 'scripting', 60, 6019),
  ('sc-ps-20', 'monitoring', 'Monitoring Scripts', 'scripting', 60, 6020),
  ('sc-ps-21', 'backup-automation', 'Backup Automation', 'scripting', 60, 6021),
  ('sc-ps-22', 'group-policy', 'Group Policy Automation', 'scripting', 60, 6022),
  ('sc-ps-23', 'troubleshooting', 'Troubleshooting Toolkit', 'scripting', 60, 6023),
  ('sc-ps-24', 'modules', 'Building Reusable Modules', 'scripting', 65, 6024),
  ('sc-ps-25', 'capstone-onboarding', 'Capstone: Onboarding Automation', 'scripting', 85, 6025),
  ('sc-py-01', 'basics', 'Python Basics', 'scripting', 55, 6026),
  ('sc-py-02', 'data-structures', 'Data Types & Structures', 'scripting', 60, 6027),
  ('sc-py-03', 'control-flow', 'Control Flow & Loops', 'scripting', 55, 6028),
  ('sc-py-04', 'functions-modules', 'Functions & Modules', 'scripting', 60, 6029),
  ('sc-py-05', 'files-errors', 'Files & Error Handling', 'scripting', 60, 6030),
  ('sc-py-06', 'automation', 'IT Automation with Python', 'scripting', 65, 6031),
  ('sc-py-07', 'regex', 'Regular Expressions', 'scripting', 60, 6032),
  ('sc-py-08', 'apis', 'Working with APIs', 'scripting', 60, 6033),
  ('sc-py-09', 'log-parsing', 'Log Parsing & a Mini-Project', 'scripting', 70, 6034),
  ('sc-py-10', 'lists-comprehensions', 'Lists & Comprehensions', 'scripting', 60, 6035),
  ('sc-py-11', 'dicts-sets', 'Dictionaries & Sets', 'scripting', 60, 6036),
  ('sc-py-12', 'csv', 'Working with CSV', 'scripting', 60, 6037),
  ('sc-py-13', 'json', 'Working with JSON', 'scripting', 55, 6038),
  ('sc-py-14', 'xml', 'Working with XML', 'scripting', 55, 6039),
  ('sc-py-15', 'apis-advanced', 'REST APIs: Auth, Pagination & Errors', 'scripting', 65, 6040),
  ('sc-py-16', 'ssh-paramiko', 'SSH Automation with Paramiko', 'scripting', 65, 6041),
  ('sc-py-17', 'networking', 'Network Automation', 'scripting', 60, 6042),
  ('sc-py-18', 'monitoring', 'Monitoring with psutil', 'scripting', 60, 6043),
  ('sc-py-19', 'email-automation', 'Email Automation', 'scripting', 60, 6044),
  ('sc-py-20', 'file-automation', 'File & Folder Automation', 'scripting', 60, 6045),
  ('sc-py-21', 'report-generation', 'Report Generation', 'scripting', 60, 6046),
  ('sc-py-22', 'ticket-automation', 'Ticket Automation', 'scripting', 65, 6047),
  ('sc-py-23', 'helpdesk-automation', 'Help Desk Automation Projects', 'scripting', 65, 6048),
  ('sc-py-24', 'sysadmin-project', 'System Administration Project', 'scripting', 70, 6049),
  ('sc-py-25', 'capstone', 'Capstone: Server Health Monitor', 'scripting', 85, 6050)
on conflict (id) do update set slug=excluded.slug, title=excluded.title, track=excluded.track, xp=excluded.xp, sort_order=excluded.sort_order;
