-- 0049_seed_scripting_quizzes.sql — P29 Scripting quizzes. Idempotent.
insert into public.lesson_quizzes (lesson_id, pass_pct, bonus_xp) values
  ('sc-ps-01', 70, 30),
  ('sc-ps-02', 70, 30),
  ('sc-ps-03', 70, 30),
  ('sc-ps-04', 70, 30),
  ('sc-ps-05', 70, 30),
  ('sc-ps-06', 70, 30),
  ('sc-ps-07', 70, 30),
  ('sc-ps-08', 70, 30),
  ('sc-ps-09', 70, 30),
  ('sc-ps-10', 70, 30),
  ('sc-ps-11', 70, 30),
  ('sc-ps-12', 70, 30),
  ('sc-ps-13', 70, 30),
  ('sc-ps-14', 70, 30),
  ('sc-ps-15', 70, 30),
  ('sc-ps-16', 70, 30),
  ('sc-ps-17', 70, 30),
  ('sc-ps-18', 70, 30),
  ('sc-ps-19', 70, 30),
  ('sc-ps-20', 70, 30),
  ('sc-ps-21', 70, 30),
  ('sc-ps-22', 70, 30),
  ('sc-ps-23', 70, 30),
  ('sc-ps-24', 70, 30),
  ('sc-ps-25', 70, 30),
  ('sc-py-01', 70, 30),
  ('sc-py-02', 70, 30),
  ('sc-py-03', 70, 30),
  ('sc-py-04', 70, 30),
  ('sc-py-05', 70, 30),
  ('sc-py-06', 70, 30),
  ('sc-py-07', 70, 30),
  ('sc-py-08', 70, 30),
  ('sc-py-09', 70, 30),
  ('sc-py-10', 70, 30),
  ('sc-py-11', 70, 30),
  ('sc-py-12', 70, 30),
  ('sc-py-13', 70, 30),
  ('sc-py-14', 70, 30),
  ('sc-py-15', 70, 30),
  ('sc-py-16', 70, 30),
  ('sc-py-17', 70, 30),
  ('sc-py-18', 70, 30),
  ('sc-py-19', 70, 30),
  ('sc-py-20', 70, 30),
  ('sc-py-21', 70, 30),
  ('sc-py-22', 70, 30),
  ('sc-py-23', 70, 30),
  ('sc-py-24', 70, 30),
  ('sc-py-25', 70, 30)
on conflict (lesson_id) do update set pass_pct=excluded.pass_pct, bonus_xp=excluded.bonus_xp;

delete from public.quiz_questions where lesson_id in ('sc-ps-01', 'sc-ps-02', 'sc-ps-03', 'sc-ps-04', 'sc-ps-05', 'sc-ps-06', 'sc-ps-07', 'sc-ps-08', 'sc-ps-09', 'sc-ps-10', 'sc-ps-11', 'sc-ps-12', 'sc-ps-13', 'sc-ps-14', 'sc-ps-15', 'sc-ps-16', 'sc-ps-17', 'sc-ps-18', 'sc-ps-19', 'sc-ps-20', 'sc-ps-21', 'sc-ps-22', 'sc-ps-23', 'sc-ps-24', 'sc-ps-25', 'sc-py-01', 'sc-py-02', 'sc-py-03', 'sc-py-04', 'sc-py-05', 'sc-py-06', 'sc-py-07', 'sc-py-08', 'sc-py-09', 'sc-py-10', 'sc-py-11', 'sc-py-12', 'sc-py-13', 'sc-py-14', 'sc-py-15', 'sc-py-16', 'sc-py-17', 'sc-py-18', 'sc-py-19', 'sc-py-20', 'sc-py-21', 'sc-py-22', 'sc-py-23', 'sc-py-24', 'sc-py-25');

insert into public.quiz_questions (lesson_id, sort, prompt, options, correct_index, explanation) values
  ('sc-ps-01', 1, 'PowerShell commands follow the form…', '["Noun-Verb", "Verb-Noun", "just verbs", "random"]'::jsonb, 1, 'Cmdlets are Verb-Noun, e.g. Get-Process.'),
  ('sc-ps-01', 2, 'Which discovers available commands?', '["Get-Help", "Get-Command", "Write-Host", "Exit"]'::jsonb, 1, 'Get-Command lists/searches cmdlets.'),
  ('sc-ps-01', 3, 'To see usage examples for a cmdlet use…', '["Get-Help -Examples", "Get-Member", "Clear-Host", "Get-Date"]'::jsonb, 0, 'Get-Help <cmd> -Examples shows usage.'),
  ('sc-ps-02', 1, 'The pipeline passes what between cmdlets?', '["Plain text", "Objects", "Files", "Bytes"]'::jsonb, 1, 'PowerShell pipes rich objects.'),
  ('sc-ps-02', 2, 'Which filters objects by a condition?', '["Select-Object", "Where-Object", "Sort-Object", "Format-Table"]'::jsonb, 1, 'Where-Object filters by condition.'),
  ('sc-ps-02', 3, 'To see an object''s properties/methods, pipe to…', '["Get-Help", "Get-Member", "Get-Command", "Out-Null"]'::jsonb, 1, 'Get-Member reveals the object''s members.'),
  ('sc-ps-03', 1, 'Equality in PowerShell is written…', '["==", "-eq", "=", "eq"]'::jsonb, 1, '-eq tests equality (= assigns).'),
  ('sc-ps-03', 2, 'An array literal uses…', '["{ }", "@( )", "[ ]", "< >"]'::jsonb, 1, '@( ) creates an array.'),
  ('sc-ps-03', 3, 'A key/value collection is a…', '["array", "hashtable", "string", "tuple"]'::jsonb, 1, '@{} is a hashtable.'),
  ('sc-ps-04', 1, 'Inside ForEach-Object, the current item is…', '["$it", "$_", "$this", "$item"]'::jsonb, 1, '$_ (or $PSItem) is the current object.'),
  ('sc-ps-04', 2, 'Which handles multiple discrete cases cleanly?', '["for", "switch", "while", "break"]'::jsonb, 1, 'switch matches multiple cases.'),
  ('sc-ps-04', 3, 'foreach ($x in $coll) iterates…', '["once", "over each element", "backwards only", "never"]'::jsonb, 1, 'It runs the block per element.'),
  ('sc-ps-05', 1, 'Function parameters are declared with…', '["args()", "param()", "def", "input()"]'::jsonb, 1, 'param() defines function parameters.'),
  ('sc-ps-05', 2, 'PowerShell script files use the extension…', '["-.sh", "-.ps1", "-.py", "-.bat"]'::jsonb, 1, '.ps1 is a PowerShell script.'),
  ('sc-ps-05', 3, 'Scripts won''t run due to…', '["Low RAM", "Execution policy", "No mouse", "DNS"]'::jsonb, 1, 'Execution policy can block scripts.'),
  ('sc-ps-06', 1, 'Export objects to CSV with…', '["Write-Host", "Export-Csv", "Out-Null", "Format-Table"]'::jsonb, 1, 'Export-Csv writes objects to CSV.'),
  ('sc-ps-06', 2, 'Recurring automation on Windows uses…', '["Task Scheduler", "Paint", "Notepad", "DNS"]'::jsonb, 0, 'Task Scheduler runs scripts on a schedule.'),
  ('sc-ps-06', 3, 'Select-Object -First 5 returns…', '["last 5", "first 5 objects", "all", "none"]'::jsonb, 1, 'It takes the first 5 objects.'),
  ('sc-ps-07', 1, 'Which makes a cmdlet error catchable by try/catch?', '["-Force", "-ErrorAction Stop", "-WhatIf", "-Confirm"]'::jsonb, 1, 'Non-terminating errors need -ErrorAction Stop to be caught.'),
  ('sc-ps-07', 2, 'Code that must always run goes in…', '["try", "catch", "finally", "trap"]'::jsonb, 2, 'finally always executes.'),
  ('sc-ps-07', 3, 'The most recent error is in…', '["$LastError", "$Error[0]", "$?", "$_"]'::jsonb, 1, '$Error[0] holds the latest error.'),
  ('sc-ps-08', 1, 'Which runs a scriptblock on a remote host?', '["Enter-Host", "Invoke-Command", "Run-Remote", "Get-Session"]'::jsonb, 1, 'Invoke-Command -ComputerName runs remotely.'),
  ('sc-ps-08', 2, 'Third-party modules install from…', '["the BIOS", "PowerShell Gallery", "Task Scheduler", "the registry"]'::jsonb, 1, 'Install-Module pulls from PSGallery.'),
  ('sc-ps-08', 3, 'A reusable, persistent remote connection is a…', '["job", "PSSession", "pipe", "cmdlet"]'::jsonb, 1, 'New-PSSession creates a reusable session.'),
  ('sc-ps-09', 1, 'A required parameter uses…', '["[Optional]", "[Parameter(Mandatory)]", "[Switch]", "[AllowNull]"]'::jsonb, 1, '[Parameter(Mandatory)] forces a value.'),
  ('sc-ps-09', 2, 'A safe dry-run is enabled by supporting…', '["-Force", "-WhatIf", "-Quiet", "-Silent"]'::jsonb, 1, '-WhatIf previews without acting.'),
  ('sc-ps-09', 3, 'Recurring script execution is handled by…', '["Task Scheduler", "Notepad", "the pipeline", "Get-Help"]'::jsonb, 0, 'Task Scheduler runs scripts on a schedule.'),
  ('sc-ps-10', 1, 'List files recursively with…', '["Get-Item", "Get-ChildItem -Recurse", "dir /s only", "Find-File"]'::jsonb, 1, 'Get-ChildItem -Recurse walks subfolders.'),
  ('sc-ps-10', 2, 'Filter to files over 1MB uses…', '["Where-Object Length -gt 1MB", "Select big", "-Large", "Sort-Size"]'::jsonb, 0, 'Where-Object filters on the Length property.'),
  ('sc-ps-10', 3, '(Get-Date).AddDays(-30) gives…', '["30 days ahead", "30 days ago", "today", "an error"]'::jsonb, 1, 'Negative days subtract from now.'),
  ('sc-ps-11', 1, 'Restart a service with…', '["Reset-Service", "Restart-Service", "Cycle-Service", "Bounce-Service"]'::jsonb, 1, 'Restart-Service stops then starts it.'),
  ('sc-ps-11', 2, 'Kill a process by name…', '["Stop-Process -Name", "End-Task", "Kill-Process", "Remove-Process"]'::jsonb, 0, 'Stop-Process -Name <n> -Force.'),
  ('sc-ps-11', 3, 'Set a service to auto-start via…', '["Set-Service -StartupType Automatic", "Auto-Service", "Enable-Service", "Start-Type"]'::jsonb, 0, 'Set-Service -StartupType Automatic.'),
  ('sc-ps-12', 1, 'Modern event querying uses…', '["Get-WinEvent", "Read-Log", "Get-Text", "Event-View"]'::jsonb, 0, 'Get-WinEvent is the modern cmdlet.'),
  ('sc-ps-12', 2, 'Registry is accessed via which drive prefix?', '["C:\\", "HKLM:\\ / HKCU:\\", "REG:\\", "SYS:\\"]'::jsonb, 1, 'PowerShell exposes the registry as HKLM:/HKCU: drives.'),
  ('sc-ps-12', 3, 'Level=2 in a System log filter means…', '["Info", "Warning", "Error", "Verbose"]'::jsonb, 2, 'Level 2 = Error.'),
  ('sc-ps-13', 1, 'Ping in PowerShell is…', '["Ping-Host", "Test-Connection", "Send-Ping", "Net-Ping"]'::jsonb, 1, 'Test-Connection sends ICMP echo.'),
  ('sc-ps-13', 2, 'Test a specific TCP port with…', '["Test-NetConnection -Port", "Test-Port", "Get-Port", "Check-Port"]'::jsonb, 0, 'Test-NetConnection -Port checks a port.'),
  ('sc-ps-13', 3, 'Resolve a name to IP with…', '["Resolve-DnsName", "Get-DNS", "Lookup-Name", "Find-Host"]'::jsonb, 0, 'Resolve-DnsName queries DNS.'),
  ('sc-ps-14', 1, 'Find locked-out accounts with…', '["Search-ADAccount -LockedOut", "Get-Locked", "Find-Lock", "AD-Locked"]'::jsonb, 0, 'Search-ADAccount -LockedOut lists them.'),
  ('sc-ps-14', 2, 'Add a user to a group via…', '["Add-ADGroupMember", "Join-Group", "Set-Group", "Group-Add"]'::jsonb, 0, 'Add-ADGroupMember -Members.'),
  ('sc-ps-14', 3, 'Offboarding disables an account with…', '["Remove-ADUser", "Disable-ADAccount", "Stop-ADUser", "Lock-Account"]'::jsonb, 1, 'Disable-ADAccount disables without deleting.'),
  ('sc-ps-15', 1, 'Register a recurring task with…', '["Register-ScheduledTask", "Add-Task", "New-Cron", "Schedule-Run"]'::jsonb, 0, 'Register-ScheduledTask creates it.'),
  ('sc-ps-15', 2, 'Modern replacement for Get-WmiObject is…', '["Get-CimInstance", "Get-WMI2", "Get-System", "Get-Info"]'::jsonb, 0, 'Get-CimInstance is the modern cmdlet.'),
  ('sc-ps-15', 3, 'Win32_LogicalDisk exposes…', '["CPU temp", "Disk space", "AD users", "Event logs"]'::jsonb, 1, 'It reports disk size/free space.'),
  ('sc-ps-16', 1, 'Read a CSV into objects with…', '["Import-Csv", "Read-Csv", "Get-Csv", "Open-Csv"]'::jsonb, 0, 'Import-Csv parses rows into objects.'),
  ('sc-ps-16', 2, 'Parse JSON text with…', '["ConvertFrom-Json", "Parse-Json", "Read-Json", "Get-Json"]'::jsonb, 0, 'ConvertFrom-Json builds objects.'),
  ('sc-ps-16', 3, 'Export objects to CSV with…', '["Export-Csv -NoTypeInformation", "Save-Csv", "Write-Csv", "Out-Csv"]'::jsonb, 0, 'Export-Csv writes objects to CSV.'),
  ('sc-ps-17', 1, 'Rounding free bytes to GB uses…', '["[math]::Round($x/1GB,1)", "/1000", "Round-GB", "ToGB()"]'::jsonb, 0, 'Divide by 1GB and [math]::Round.'),
  ('sc-ps-17', 2, 'The report is made recurring by…', '["Register-ScheduledTask", "a while loop", "manual runs", "Task-Loop"]'::jsonb, 0, 'Schedule it with Register-ScheduledTask.'),
  ('sc-ps-17', 3, 'Robust scripts wrap logic in…', '["try/catch + logging", "nothing", "comments only", "a GUI"]'::jsonb, 0, 'Error handling + logging make it production-safe.'),
  ('sc-ps-18', 1, 'Which auto-parses JSON into objects?', '["Invoke-WebRequest", "Invoke-RestMethod", "Get-Web", "Fetch-Url"]'::jsonb, 1, 'Invoke-RestMethod parses JSON responses.'),
  ('sc-ps-18', 2, 'A POST body is usually sent as…', '["plain text", "JSON via ConvertTo-Json", "CSV", "XML only"]'::jsonb, 1, 'Convert a hashtable to JSON for the body.'),
  ('sc-ps-18', 3, 'Auth tokens go in the…', '["URL only", "Headers", "Body", "Filename"]'::jsonb, 1, 'Authorization header carries the token.'),
  ('sc-ps-19', 1, 'Grep-like search in PowerShell is…', '["Find-Text", "Select-String", "Search-Log", "Match-Line"]'::jsonb, 1, 'Select-String matches patterns in text.'),
  ('sc-ps-19', 2, 'Tally values by frequency with…', '["Group-Object", "Count-Object", "Sum-Object", "Tally"]'::jsonb, 0, 'Group-Object buckets by value.'),
  ('sc-ps-19', 3, 'Regex capture groups are accessed via…', '["$_.Matches.Groups", "$_.Text", "$_.Line only", "$_.Value[0]"]'::jsonb, 0, 'Matches.Groups holds captures.'),
  ('sc-ps-20', 1, 'Free space % comes from…', '["FreeSpace / Size * 100", "FreeSpace only", "Size - 100", "random"]'::jsonb, 0, 'Free/Size*100 gives the percentage.'),
  ('sc-ps-20', 2, 'A monitor reacts when a value crosses a…', '["color", "threshold", "font", "port"]'::jsonb, 1, 'Thresholds trigger alerts.'),
  ('sc-ps-20', 3, 'Monitors are typically run…', '["once manually", "on a schedule", "never", "at install only"]'::jsonb, 1, 'Scheduled runs catch issues early.'),
  ('sc-ps-21', 1, 'Create a zip archive with…', '["Compress-Archive", "Zip-Item", "New-Zip", "Archive-File"]'::jsonb, 0, 'Compress-Archive builds a .zip.'),
  ('sc-ps-21', 2, 'Dated filenames use…', '["Get-Date -Format", "Now()", "Date-Stamp", "Time-Tag"]'::jsonb, 0, 'Get-Date -Format yyyyMMdd.'),
  ('sc-ps-21', 3, 'Retention is enforced by deleting files older than…', '["a threshold date", "never", "1 hour", "the newest"]'::jsonb, 0, 'Remove archives past the retention window.'),
  ('sc-ps-22', 1, 'List all GPOs with…', '["Get-GPO -All", "Get-Policy", "List-GPO", "GPO-All"]'::jsonb, 0, 'Get-GPO -All enumerates them.'),
  ('sc-ps-22', 2, 'Export a GPO to HTML with…', '["Get-GPOReport -ReportType Html", "Export-GPO", "Save-GPO", "GPO-Html"]'::jsonb, 0, 'Get-GPOReport -ReportType Html.'),
  ('sc-ps-22', 3, 'Applied policy on a client is shown by…', '["gpresult /r", "gpo /list", "policy /show", "rsop /r"]'::jsonb, 0, 'gpresult /r lists applied GPOs.'),
  ('sc-ps-23', 1, 'Preview a destructive command with…', '["-WhatIf", "-Force", "-Quiet", "-Yes"]'::jsonb, 0, '-WhatIf shows what would happen.'),
  ('sc-ps-23', 2, 'Traceable step-by-step output uses…', '["-Verbose", "-Silent", "-Debug off", "-Fast"]'::jsonb, 0, '-Verbose emits progress detail.'),
  ('sc-ps-23', 3, 'Uptime comes from Win32_OperatingSystem''s…', '["LastBootUpTime", "Uptime", "BootDate", "StartTime"]'::jsonb, 0, 'LastBootUpTime gives boot time.'),
  ('sc-ps-24', 1, 'A PowerShell module file uses the extension…', '["-.ps1", ".psm1", ".mod", "-.dll"]'::jsonb, 1, '.psm1 is a script module.'),
  ('sc-ps-24', 2, 'Expose functions from a module with…', '["Export-ModuleMember", "Publish-Function", "Show-Function", "Export-Func"]'::jsonb, 0, 'Export-ModuleMember -Function.'),
  ('sc-ps-24', 3, 'Load a module with…', '["Import-Module", "Load-Module", "Use-Module", "Add-Module"]'::jsonb, 0, 'Import-Module brings it into the session.'),
  ('sc-ps-25', 1, 'Bulk input for onboarding comes from…', '["a GUI", "Import-Csv", "manual typing", "the registry"]'::jsonb, 1, 'Import-Csv feeds the hire list.'),
  ('sc-ps-25', 2, 'Per-row failures are captured with…', '["try/catch", "ignore", "reboot", "-Force"]'::jsonb, 0, 'try/catch records each row''s outcome.'),
  ('sc-ps-25', 3, 'Results are saved with…', '["Export-Csv", "print", "Write-Host only", "nothing"]'::jsonb, 0, 'Export-Csv writes the run report.'),
  ('sc-py-01', 1, 'Python blocks are defined by…', '["Braces { }", "Indentation", "Semicolons", "Parentheses"]'::jsonb, 1, 'Indentation defines blocks in Python.'),
  ('sc-py-01', 2, 'An f-string is written…', '["f''{x}''", "$x", "%x", "{{x}}"]'::jsonb, 0, 'f''...{var}...'' interpolates values.'),
  ('sc-py-01', 3, 'Run a script file with…', '["run script", "python script.py", "exec()", "./python"]'::jsonb, 1, 'python script.py executes the file.'),
  ('sc-py-02', 1, 'Which is an immutable sequence?', '["list", "tuple", "dict", "set"]'::jsonb, 1, 'Tuples are immutable.'),
  ('sc-py-02', 2, 'Key/value pairs are stored in a…', '["list", "dict", "tuple", "set"]'::jsonb, 1, 'dict holds key/value pairs.'),
  ('sc-py-02', 3, 'len(x) returns…', '["the type", "the length/count", "the first item", "None"]'::jsonb, 1, 'len() gives the number of items.'),
  ('sc-py-03', 1, 'range(5) produces…', '["1..5", "0..4", "0..5", "5 only"]'::jsonb, 1, 'range(5) is 0,1,2,3,4.'),
  ('sc-py-03', 2, 'Equality in Python is…', '["-eq", "==", "=", "eq"]'::jsonb, 1, '== tests equality (= assigns).'),
  ('sc-py-03', 3, 'To skip to the next loop iteration use…', '["break", "continue", "pass", "exit"]'::jsonb, 1, 'continue skips to the next iteration.'),
  ('sc-py-04', 1, 'A function is defined with…', '["function", "def", "func", "sub"]'::jsonb, 1, 'def defines a function.'),
  ('sc-py-04', 2, 'Third-party packages are installed with…', '["import", "pip install", "download", "apt"]'::jsonb, 1, 'pip install adds packages.'),
  ('sc-py-04', 3, 'Which is part of Python''s standard library?', '["requests", "json", "numpy", "flask"]'::jsonb, 1, 'json ships with Python; requests is third-party.'),
  ('sc-py-05', 1, 'The safe way to open files is…', '["open() then hope", "with open(...) as f", "file()", "read()"]'::jsonb, 1, 'with auto-closes the file.'),
  ('sc-py-05', 2, 'Handle a runtime error with…', '["if/else", "try/except", "switch", "assert only"]'::jsonb, 1, 'try/except handles exceptions.'),
  ('sc-py-05', 3, 'Opening with mode ''w''…', '["reads", "writes (truncates)", "appends", "fails"]'::jsonb, 1, '''w'' opens for writing, truncating.'),
  ('sc-py-06', 1, 'Run an external command from Python with…', '["os.open", "subprocess.run", "print", "import"]'::jsonb, 1, 'subprocess.run executes commands.'),
  ('sc-py-06', 2, 'Parse a JSON API response with…', '["r.text only", "r.json()", "r.bytes", "r.raw"]'::jsonb, 1, 'response.json() parses JSON.'),
  ('sc-py-06', 3, 'A good automation pattern is…', '["random edits", "read \u2192 transform \u2192 output", "delete files", "guess"]'::jsonb, 1, 'Input → transform → output is the core pattern.'),
  ('sc-py-07', 1, 'Which returns all matches as a list?', '["re.match", "re.findall", "re.split only", "re.compile"]'::jsonb, 1, 're.findall returns all matches.'),
  ('sc-py-07', 2, 'A capture group is written with…', '["[ ]", "( )", "{ }", "< >"]'::jsonb, 1, '( ) captures a group.'),
  ('sc-py-07', 3, '\d matches a…', '["letter", "digit", "space", "word"]'::jsonb, 1, '\d matches a digit.'),
  ('sc-py-08', 1, 'Parse a JSON API body with…', '["r.text", "r.json()", "r.raw", "r.body"]'::jsonb, 1, 'response.json() parses JSON.'),
  ('sc-py-08', 2, 'A 401 status means…', '["Success", "Auth problem", "Not found", "Rate limited"]'::jsonb, 1, '401 is unauthorized.'),
  ('sc-py-08', 3, 'raise_for_status() does what?', '["Nothing", "Raises on HTTP error", "Prints", "Retries"]'::jsonb, 1, 'It raises an exception on 4xx/5xx.'),
  ('sc-py-09', 1, 'Counting occurrences is easiest with…', '["a list", "collections.Counter", "a tuple", "a set"]'::jsonb, 1, 'Counter tallies occurrences.'),
  ('sc-py-09', 2, 'most_common() returns items…', '["randomly", "ordered by frequency", "alphabetically", "reversed"]'::jsonb, 1, 'Ordered from most to least frequent.'),
  ('sc-py-09', 3, 'The core automation pattern here is…', '["read \u2192 extract \u2192 aggregate \u2192 report", "delete logs", "guess", "reboot"]'::jsonb, 0, 'Read, extract, aggregate, output.'),
  ('sc-py-10', 1, 'Add to the end of a list with…', '[".add()", ".append()", ".push()", ".insert() only"]'::jsonb, 1, 'list.append() adds an item.'),
  ('sc-py-10', 2, '[x*2 for x in nums] is a…', '["loop", "comprehension", "function", "dict"]'::jsonb, 1, 'That''s a list comprehension.'),
  ('sc-py-10', 3, 'hosts[-1] returns the…', '["first", "last", "length", "error"]'::jsonb, 1, 'Negative index counts from the end.'),
  ('sc-py-11', 1, 'Safe key access with a default uses…', '["[]", ".get()", ".find()", ".key()"]'::jsonb, 1, '.get(key, default) avoids KeyError.'),
  ('sc-py-11', 2, 'Unique items are stored in a…', '["list", "set", "tuple", "str"]'::jsonb, 1, 'A set holds unique values.'),
  ('sc-py-11', 3, 'Set intersection uses…', '["|", "&", "-", "^"]'::jsonb, 1, '& gives common elements.'),
  ('sc-py-12', 1, 'Read rows as dicts with…', '["csv.DictReader", "csv.reader only", "open()", "json.load"]'::jsonb, 0, 'DictReader keys by header.'),
  ('sc-py-12', 2, 'Always open CSV files with…', '["newline=''''", "binary", "append", "no args"]'::jsonb, 0, 'newline='''' avoids blank rows on Windows.'),
  ('sc-py-12', 3, 'Write a header row with…', '["writeheader()", "header()", "writerow(''h'')", "top()"]'::jsonb, 0, 'DictWriter.writeheader() emits headers.'),
  ('sc-py-13', 1, 'Parse a JSON string with…', '["json.loads", "json.read", "json.parse", "load_json"]'::jsonb, 0, 'json.loads parses a string.'),
  ('sc-py-13', 2, 'Read JSON from a file with…', '["json.load(f)", "json.loads(f)", "f.json()", "read_json"]'::jsonb, 0, 'json.load reads from a file object.'),
  ('sc-py-13', 3, 'Pretty-print JSON with…', '["indent=", "pretty=True", "format()", "tab()"]'::jsonb, 0, 'json.dumps(..., indent=2).'),
  ('sc-py-14', 1, 'Parse an XML file with…', '["ET.parse", "ET.json", "xml.read", "parse_xml"]'::jsonb, 0, 'ElementTree.parse loads a file.'),
  ('sc-py-14', 2, 'Find matching child elements with…', '["findall()", "search()", "grep()", "query()"]'::jsonb, 0, 'Element.findall() returns matches.'),
  ('sc-py-14', 3, 'An attribute value is read with…', '[".get()", ".attr", ".value", ".text"]'::jsonb, 0, 'element.get(''attr'').'),
  ('sc-py-15', 1, 'Stop a script on HTTP errors with…', '["raise_for_status()", "try only", "ignore", "r.ok print"]'::jsonb, 0, 'raise_for_status() raises on 4xx/5xx.'),
  ('sc-py-15', 2, 'Prevent hanging calls with…', '["timeout=", "wait=", "sleep()", "block=False"]'::jsonb, 0, 'Pass timeout= to requests.'),
  ('sc-py-15', 3, 'Pagination usually loops until…', '["no next page", "one call", "an error", "forever"]'::jsonb, 0, 'Stop when there''s no next page/cursor.'),
  ('sc-py-16', 1, 'The Python SSH library is…', '["paramiko", "ssh2", "netssh", "pyssh only"]'::jsonb, 0, 'Paramiko is the standard SSH lib.'),
  ('sc-py-16', 2, 'Run a remote command with…', '["exec_command", "run()", "shell()", "cmd()"]'::jsonb, 0, 'SSHClient.exec_command().'),
  ('sc-py-16', 3, 'Preferred remote auth is…', '["password in code", "SSH keys", "no auth", "telnet"]'::jsonb, 1, 'Key-based auth is more secure.'),
  ('sc-py-17', 1, 'Low-level TCP checks use the…', '["socket", "http", "json", "os"]'::jsonb, 0, 'The socket module.'),
  ('sc-py-17', 2, 'connect_ex returns 0 when…', '["closed", "the port is open", "error", "timeout"]'::jsonb, 1, '0 means the connection succeeded.'),
  ('sc-py-17', 3, 'Run an external ping with…', '["subprocess.run", "os.ping", "net.ping", "socket.ping"]'::jsonb, 0, 'subprocess.run invokes the OS command.'),
  ('sc-py-18', 1, 'Live system metrics come from…', '["psutil", "os only", "sys", "socket"]'::jsonb, 0, 'psutil exposes CPU/mem/disk.'),
  ('sc-py-18', 2, 'Disk usage percent is…', '["disk_usage(path).percent", "df()", "disk.pct", "usage()"]'::jsonb, 0, 'psutil.disk_usage(path).percent.'),
  ('sc-py-18', 3, 'psutil runs on…', '["Windows only", "Linux only", "both", "neither"]'::jsonb, 2, 'It''s cross-platform.'),
  ('sc-py-19', 1, 'Send email in Python with…', '["smtplib", "emaillib", "mailer", "sendmail()"]'::jsonb, 0, 'smtplib sends over SMTP.'),
  ('sc-py-19', 2, 'Encrypt the SMTP session with…', '["starttls()", "secure()", "ssl_on", "encrypt()"]'::jsonb, 0, 'starttls() upgrades to TLS.'),
  ('sc-py-19', 3, 'Build the message with…', '["EmailMessage", "dict", "str only", "MailObj"]'::jsonb, 0, 'email.message.EmailMessage.'),
  ('sc-py-20', 1, 'The modern path API is…', '["pathlib", "os.path only", "filelib", "dirlib"]'::jsonb, 0, 'pathlib.Path is the modern API.'),
  ('sc-py-20', 2, 'Copy a file with…', '["shutil.copy", "os.copy", "file.copy", "cp()"]'::jsonb, 0, 'shutil.copy() copies files.'),
  ('sc-py-20', 3, 'Match files by pattern with…', '["glob()", "find()", "match()", "ls()"]'::jsonb, 0, 'Path.glob(''*.ext'').'),
  ('sc-py-21', 1, 'Write many dict rows with…', '["writerows()", "writeall()", "dump()", "save()"]'::jsonb, 0, 'DictWriter.writerows().'),
  ('sc-py-21', 2, 'A quick web-viewable report format is…', '["HTML", "EXE", "ISO", "BIN"]'::jsonb, 0, 'HTML renders in any browser.'),
  ('sc-py-21', 3, 'Reports become valuable when they''re…', '["hidden", "delivered/scheduled", "deleted", "manual"]'::jsonb, 1, 'Automated delivery drives impact.'),
  ('sc-py-22', 1, 'Create a resource via API with…', '["POST", "GET", "DELETE", "HEAD"]'::jsonb, 0, 'POST creates a new ticket.'),
  ('sc-py-22', 2, 'The new ticket''s id comes from…', '["the response JSON", "the URL only", "a guess", "the headers only"]'::jsonb, 0, 'Read it from r.json().'),
  ('sc-py-22', 3, 'Partial updates typically use…', '["PATCH", "GET", "OPTIONS", "TRACE"]'::jsonb, 0, 'PATCH updates fields.'),
  ('sc-py-23', 1, 'Bulk help-desk actions are driven from…', '["a CSV/list", "one manual entry", "the registry", "a screenshot"]'::jsonb, 0, 'Feed actions from a CSV/list.'),
  ('sc-py-23', 2, 'A high-ROI target for automation is…', '["a rare 1x task", "a frequent repetitive task", "a creative task", "a meeting"]'::jsonb, 1, 'Frequent, repetitive tasks pay back fastest.'),
  ('sc-py-23', 3, 'Auto-triage tags tickets by…', '["keyword/rules", "random", "color", "size"]'::jsonb, 0, 'Keyword/rule matching classifies tickets.'),
  ('sc-py-24', 1, 'Per-host failures should be…', '["ignored", "caught and recorded", "fatal", "retried forever"]'::jsonb, 1, 'Catch errors so one bad host doesn''t stop the run.'),
  ('sc-py-24', 2, 'Remote disk info is gathered via…', '["paramiko + df", "local os only", "a GUI", "ping"]'::jsonb, 0, 'SSH runs df on each host.'),
  ('sc-py-24', 3, 'Results are delivered as…', '["a CSV/report", "nothing", "print once", "a reboot"]'::jsonb, 0, 'Export a CSV/report.'),
  ('sc-py-25', 1, 'Cross-platform metrics come from…', '["psutil", "os.stat", "socket", "json"]'::jsonb, 0, 'psutil reads CPU/mem/disk.'),
  ('sc-py-25', 2, 'History is appended to CSV using mode…', '["''a''", "''w''", "''r''", "''x''"]'::jsonb, 0, '''a'' appends without truncating.'),
  ('sc-py-25', 3, 'A production monitor should be…', '["run once", "scheduled + alerting", "manual only", "disabled"]'::jsonb, 1, 'Schedule it and alert on breaches.');
