-- 0055_seed_helpdesk_t01_quizzes.sql — P33 Help Desk Tier 0/1 quizzes. Idempotent.
insert into public.lesson_quizzes (lesson_id, pass_pct, bonus_xp) values
  ('hd-ess-01', 70, 30),
  ('hd-ess-02', 70, 30),
  ('hd-ess-03', 70, 30),
  ('hd-ess-04', 70, 30),
  ('hd-ess-05', 70, 30),
  ('hd-eve-01', 70, 30),
  ('hd-eve-02', 70, 30),
  ('hd-eve-03', 70, 30),
  ('hd-eve-04', 70, 30),
  ('hd-eve-05', 70, 30),
  ('hd-t1-01', 70, 30),
  ('hd-t1-02', 70, 30),
  ('hd-t1-03', 70, 30),
  ('hd-t1-04', 70, 30),
  ('hd-t1-05', 70, 30)
on conflict (lesson_id) do update set pass_pct=excluded.pass_pct, bonus_xp=excluded.bonus_xp;

delete from public.quiz_questions where lesson_id in ('hd-ess-01', 'hd-ess-02', 'hd-ess-03', 'hd-ess-04', 'hd-ess-05', 'hd-eve-01', 'hd-eve-02', 'hd-eve-03', 'hd-eve-04', 'hd-eve-05', 'hd-t1-01', 'hd-t1-02', 'hd-t1-03', 'hd-t1-04', 'hd-t1-05');

insert into public.quiz_questions (lesson_id, sort, prompt, options, correct_index, explanation) values
  ('hd-ess-01', 1, 'Tier 1 support is…', '["the deepest specialists", "the first human contact for common issues", "self-service only", "management"]'::jsonb, 1, 'Tier 1 handles first-contact common fixes.'),
  ('hd-ess-01', 2, 'Issues beyond your scope should be…', '["ignored", "escalated with notes", "closed", "deleted"]'::jsonb, 1, 'Escalate with context.'),
  ('hd-ess-01', 3, 'Employers value help-desk techs for…', '["silence", "communication + attitude", "typing speed only", "hardware only"]'::jsonb, 1, 'Soft skills matter as much as technical.'),
  ('hd-ess-02', 1, 'The first step on any contact is…', '["start fixing", "listen and confirm the issue", "escalate", "close it"]'::jsonb, 1, 'Understand before acting.'),
  ('hd-ess-02', 2, 'With a frustrated user you should…', '["match their anger", "acknowledge + focus on next steps", "hang up", "blame them"]'::jsonb, 1, 'Acknowledge and move to action.'),
  ('hd-ess-02', 3, 'Good communication means avoiding…', '["empathy", "jargon", "updates", "clarity"]'::jsonb, 1, 'Avoid jargon users don''t know.'),
  ('hd-ess-03', 1, 'Elevated access should be used…', '["freely", "only for the task at hand", "for curiosity", "to browse files"]'::jsonb, 1, 'Least privilege applies to techs too.'),
  ('hd-ess-03', 2, 'When you make a mistake you should…', '["hide it", "own and fix it", "blame a user", "ignore it"]'::jsonb, 1, 'Accountability builds trust.'),
  ('hd-ess-03', 3, 'User data must be…', '["shared", "respected/protected", "posted", "copied"]'::jsonb, 1, 'Protect privacy and follow policy.'),
  ('hd-ess-04', 1, 'Good ticket notes let…', '["only you continue", "the next tech continue", "no one continue", "managers only"]'::jsonb, 1, 'Anyone should be able to pick it up.'),
  ('hd-ess-04', 2, 'KB articles should be titled by…', '["internal code", "the symptom users search", "the tech''s name", "date"]'::jsonb, 1, 'Match how users describe it.'),
  ('hd-ess-04', 3, 'A KB article''s leverage is that it…', '["is hidden", "resolves issues repeatedly", "expires fast", "is private"]'::jsonb, 1, 'Reused many times via self-service.'),
  ('hd-ess-05', 1, 'Priority is derived from…', '["impact \u00d7 urgency", "ticket age", "alphabetical", "random"]'::jsonb, 0, 'Impact and urgency set priority.'),
  ('hd-ess-05', 2, 'A site-wide outage is typically…', '["P4", "P1", "closed", "low"]'::jsonb, 1, 'Broad, urgent = P1.'),
  ('hd-ess-05', 3, 'SLAs define…', '["response/resolution targets", "salaries", "hardware", "passwords"]'::jsonb, 0, 'Agreed time targets by priority.'),
  ('hd-eve-01', 1, 'Before any reset you must…', '["skip verification", "verify identity", "email the password", "reboot"]'::jsonb, 1, 'Always verify identity first.'),
  ('hd-eve-01', 2, 'MFA combines…', '["two passwords", "different factor types", "two emails", "nothing"]'::jsonb, 1, 'Know + have/are.'),
  ('hd-eve-01', 3, 'A reset password should be sent…', '["in plain email", "never in clear text", "via chat", "on a sticky note"]'::jsonb, 1, 'Never transmit in clear text.'),
  ('hd-eve-02', 1, 'A stuck print queue is cleared by…', '["reinstalling Windows", "restarting Print Spooler", "new toner", "a reboot only"]'::jsonb, 1, 'Restart the Print Spooler.'),
  ('hd-eve-02', 2, 'Offline for everyone points to…', '["one PC", "the printer/network", "a password", "the monitor"]'::jsonb, 1, 'Shared outage = printer/network side.'),
  ('hd-eve-02', 3, 'Faded output often means…', '["low toner", "DNS", "bad RAM", "a virus"]'::jsonb, 0, 'Low toner/consumables.'),
  ('hd-eve-03', 1, 'Before VPN troubleshooting, confirm…', '["new laptop", "the user has internet", "AD reset", "Office reinstall"]'::jsonb, 1, 'No internet, no VPN.'),
  ('hd-eve-03', 2, 'Connected but names don''t resolve →', '["bad monitor", "DNS/routing", "low RAM", "dead NIC"]'::jsonb, 1, 'Likely DNS over the tunnel.'),
  ('hd-eve-03', 3, 'Remote-control a user''s PC only…', '["silently", "with consent", "after hours", "never"]'::jsonb, 1, 'Always get consent.'),
  ('hd-eve-04', 1, 'Best first tool for delivery issues…', '["reboot Outlook", "message trace", "new mailbox", "reset password"]'::jsonb, 1, 'Message trace shows the path.'),
  ('hd-eve-04', 2, 'Missing mail may be caught by…', '["rules/junk/quarantine", "the CPU", "DNS only", "the printer"]'::jsonb, 0, 'Check rules, junk, quarantine.'),
  ('hd-eve-04', 3, 'A corrupt Outlook profile is fixed by…', '["new PC", "rebuilding the profile", "new license", "BIOS reset"]'::jsonb, 1, 'Rebuild the mail profile.'),
  ('hd-eve-05', 1, 'Incognito working but normal failing suggests…', '["server down", "cache/extension", "dead NIC", "bad RAM"]'::jsonb, 1, 'Stale cache or an extension.'),
  ('hd-eve-05', 2, 'Certificate/date errors can stem from…', '["the system clock", "toner", "the mouse", "DNS only"]'::jsonb, 0, 'A wrong clock breaks TLS validation.'),
  ('hd-eve-05', 3, 'Failing across all browsers/machines is likely…', '["client-side", "server-side", "the keyboard", "the monitor"]'::jsonb, 1, 'Escalate as server-side.'),
  ('hd-t1-01', 1, 'Minimal-driver diagnostic boot is…', '["Safe Mode", "Fast Boot", "UEFI", "BIOS"]'::jsonb, 0, 'Safe Mode loads minimal drivers.'),
  ('hd-t1-01', 2, 'First checks for a slow PC…', '["buy new PC", "startup apps/disk/malware", "repaint", "new monitor"]'::jsonb, 1, 'Startup load, disk/RAM, malware.'),
  ('hd-t1-01', 3, 'Clues to app errors live in…', '["Event Viewer", "Paint", "the BIOS", "the router"]'::jsonb, 0, 'Event Viewer logs errors.'),
  ('hd-t1-02', 1, 'A yellow ! in Device Manager means…', '["healthy", "a driver/hardware problem", "low disk", "a virus"]'::jsonb, 1, 'It flags a device problem.'),
  ('hd-t1-02', 2, 'A device broken right after an update →', '["new PC", "roll back the driver", "reinstall Windows", "replace RAM"]'::jsonb, 1, 'Roll back the driver.'),
  ('hd-t1-02', 3, 'Drivers should come from…', '["random sites", "the vendor/OEM", "email", "a USB found in the lot"]'::jsonb, 1, 'Use vendor/OEM drivers.'),
  ('hd-t1-03', 1, 'Updates primarily provide…', '["wallpaper", "security + bug fixes", "more RAM", "new hardware"]'::jsonb, 1, 'Security patches and fixes.'),
  ('hd-t1-03', 2, 'A stuck update may need…', '["a new CPU", "resetting Update components", "a new mouse", "BIOS reset"]'::jsonb, 1, 'Reset Windows Update components.'),
  ('hd-t1-03', 3, 'Unpatched systems are…', '["safest", "the top malware target", "fastest", "fine"]'::jsonb, 1, 'Prime targets for attackers.'),
  ('hd-t1-04', 1, 'RDP uses port…', '["22", "3389", "443", "80"]'::jsonb, 1, 'RDP is TCP 3389.'),
  ('hd-t1-04', 2, 'RDP should be reached…', '["over the open internet", "through a VPN", "via email", "via USB"]'::jsonb, 1, 'Tunnel it through a VPN.'),
  ('hd-t1-04', 3, 'Remote-assist sessions require…', '["nothing", "user consent", "a reboot", "admin only"]'::jsonb, 1, 'Get user consent.'),
  ('hd-t1-05', 1, 'Combined Share + NTFS yields the…', '["most permissive", "most restrictive", "share only", "NTFS only"]'::jsonb, 1, 'The most restrictive wins.'),
  ('hd-t1-05', 2, 'Access is best granted via…', '["individual users", "security groups", "email", "the registry"]'::jsonb, 1, 'Groups scale and audit better.'),
  ('hd-t1-05', 3, 'Surprise denials often come from…', '["broken inheritance", "the monitor", "toner", "DNS"]'::jsonb, 0, 'Broken permission inheritance.');
